// Dumps cel-go's checker_test.go test table as Swift source for Tests/CELTests/CheckerTests.swift.
//
// This file is copied into third_party/cel-go/checker by gen.sh, run as a test of package checker (so it can
// read the unexported testCases table and options), and removed again.

package checker

import (
	"fmt"
	"os"
	"strings"
	"testing"

	"cel.dev/cel-go/common/types"
)

func TestDumpCheckerCasesAsSwift(t *testing.T) {
	out := os.Getenv("CHECKER_CASES_OUT")
	if out == "" {
		t.Skip("CHECKER_CASES_OUT not set")
	}
	var b strings.Builder
	b.WriteString("// Generated by tools/checker-cases from cel-go v0.32.0 checker/checker_test.go. Do not edit.\n\n")
	b.WriteString("@testable import CEL\n\n")
	b.WriteString("extension CheckerCase {\n  static let all: [CheckerCase] = [\n")
	for i, tc := range testCases(t) {
		opts := &options{crossTypeNumericComparisons: true}
		if len(tc.opts) != 0 {
			opts = &options{}
			for _, o := range tc.opts {
				_ = o(opts)
			}
		}
		fmt.Fprintf(&b, "    CheckerCase(\n      index: %d,\n      in: %s,\n", i, swiftString(tc.in))
		if tc.out != "" {
			fmt.Fprintf(&b, "      out: %s,\n", swiftString(tc.out))
		}
		if tc.outType != nil {
			fmt.Fprintf(&b, "      outType: %s,\n", swiftType(tc.outType))
		}
		if tc.container != "" {
			fmt.Fprintf(&b, "      container: %s,\n", swiftString(tc.container))
		}
		if tc.err != "" {
			fmt.Fprintf(&b, "      err: %s,\n", swiftString(tc.err))
		}
		if tc.disableStdEnv {
			b.WriteString("      disableStdEnv: true,\n")
		}
		if !opts.crossTypeNumericComparisons {
			b.WriteString("      crossTypeNumericComparisons: false,\n")
		}
		if tc.env.optionalSyntax {
			b.WriteString("      optionalSyntax: true,\n")
		}
		if tc.env.variadicASTs {
			b.WriteString("      variadicASTs: true,\n")
		}
		if tc.env.jsonFieldNames {
			b.WriteString("      jsonFieldNames: true,\n")
		}
		if len(tc.env.idents) != 0 {
			b.WriteString("      idents: [\n")
			for _, id := range tc.env.idents {
				fmt.Fprintf(&b, "        VariableDecl(name: %s, type: %s),\n", swiftString(id.Name()), swiftType(id.Type()))
			}
			b.WriteString("      ],\n")
		}
		if len(tc.env.functions) != 0 {
			b.WriteString("      functions: [\n")
			for _, fn := range tc.env.functions {
				fmt.Fprintf(&b, "        try! FunctionDecl(%s, options: [\n", swiftString(fn.Name()))
				for _, o := range fn.OverloadDecls() {
					ctor := "overload"
					if o.IsMemberFunction() {
						ctor = "memberOverload"
					}
					args := make([]string, 0, len(o.ArgTypes()))
					for _, a := range o.ArgTypes() {
						args = append(args, swiftType(a))
					}
					fmt.Fprintf(&b, "          .%s(%s, argTypes: [%s], resultType: %s),\n",
						ctor, swiftString(o.ID()), strings.Join(args, ", "), swiftType(o.ResultType()))
				}
				b.WriteString("        ]),\n")
			}
			b.WriteString("      ],\n")
		}
		s := b.String()
		b.Reset()
		b.WriteString(strings.TrimSuffix(s, ",\n") + "),\n")
	}
	b.WriteString("  ]\n}\n")
	if err := os.WriteFile(out, []byte(b.String()), 0o644); err != nil {
		t.Fatal(err)
	}
}

func swiftString(s string) string {
	if strings.Contains(s, "\n") || strings.Contains(s, `"`) || strings.Contains(s, `\`) {
		return "#\"\"\"\n" + s + "\n\"\"\"#"
	}
	return `"` + s + `"`
}

func swiftType(t *types.Type) string {
	if strings.HasPrefix(t.DeclaredTypeName(), "wrapper(") {
		return fmt.Sprintf(".wrapper(%s)", swiftKind(t))
	}
	return swiftKind(t)
}

func swiftKind(t *types.Type) string {
	params := t.Parameters()
	switch t.Kind() {
	case types.AnyKind:
		return ".any"
	case types.BoolKind:
		return ".bool"
	case types.BytesKind:
		return ".bytes"
	case types.DoubleKind:
		return ".double"
	case types.DurationKind:
		return ".duration"
	case types.DynKind:
		return ".dyn"
	case types.ErrorKind:
		return ".error"
	case types.IntKind:
		return ".int"
	case types.ListKind:
		return fmt.Sprintf(".list(%s)", swiftType(params[0]))
	case types.MapKind:
		return fmt.Sprintf(".map(key: %s, value: %s)", swiftType(params[0]), swiftType(params[1]))
	case types.NullTypeKind:
		return ".null"
	case types.OpaqueKind:
		ps := make([]string, 0, len(params))
		for _, p := range params {
			ps = append(ps, swiftType(p))
		}
		return fmt.Sprintf(".opaque(name: %q, parameters: [%s])", t.TypeName(), strings.Join(ps, ", "))
	case types.StringKind:
		return ".string"
	case types.StructKind:
		return fmt.Sprintf(".object(%q)", t.TypeName())
	case types.TimestampKind:
		return ".timestamp"
	case types.TypeKind:
		if len(params) == 0 {
			return ".type(nil)"
		}
		return fmt.Sprintf(".type(%s)", swiftType(params[0]))
	case types.TypeParamKind:
		return fmt.Sprintf(".typeParam(%q)", t.TypeName())
	case types.UintKind:
		return ".uint"
	}
	panic(fmt.Sprintf("unsupported type %v", t))
}
