// swift-tools-version: 6.0
import PackageDescription

let package = Package(
  name: "cel-swift",
  platforms: [.macOS(.v13), .iOS(.v16)],
  products: [
    .library(name: "CEL", targets: ["CEL"]),
    .library(name: "CELExtensions", targets: ["CELExtensions"]),
    .library(name: "CELPolicy", targets: ["CELPolicy"]),
    .library(name: "CELTest", targets: ["CELTest"]),
    .library(name: "CELProtobuf", targets: ["CELProtobuf"]),
    .library(name: "CELSwift", targets: ["CELSwift"]),
    .executable(name: "protoc-gen-cel-swift", targets: ["protoc-gen-cel-swift"]),
    .executable(name: "cel-swift", targets: ["cel-swift"]),
  ],
  dependencies: [
    // 1.38 requires Swift 6.1; stay on 1.37.x while the floor is 6.0.
    .package(url: "https://github.com/apple/swift-protobuf.git", .upToNextMinor(from: "1.37.0")),
    .package(url: "https://github.com/jpsim/Yams.git", from: "6.2.2"),
  ],
  targets: [
    .target(
      name: "CEL",
      dependencies: ["CELRegex"],
      swiftSettings: [.swiftLanguageMode(.v6)]
    ),
    // Generated from third_party/cel-spec by tools/gen-protos.sh. Not a product.
    .target(
      name: "CELSpecProtos",
      dependencies: ["CEL", "CELProtobuf", .product(name: "SwiftProtobuf", package: "swift-protobuf")],
      swiftSettings: [.swiftLanguageMode(.v6)]
    ),
    .target(
      name: "CELProtobuf",
      dependencies: ["CEL", .product(name: "SwiftProtobuf", package: "swift-protobuf")],
      swiftSettings: [.swiftLanguageMode(.v6)]
    ),
    .executableTarget(
      name: "protoc-gen-cel-swift",
      dependencies: [.product(name: "SwiftProtobufPluginLibrary", package: "swift-protobuf")],
      swiftSettings: [.swiftLanguageMode(.v6)]
    ),
    // cel-go's test protos (test/proto2pb, test/proto3pb), generated by tools/gen-protos.sh. Not a product.
    .target(
      name: "CELGoTestProtos",
      dependencies: ["CEL", "CELProtobuf", .product(name: "SwiftProtobuf", package: "swift-protobuf")],
      swiftSettings: [.swiftLanguageMode(.v6)]
    ),
    .testTarget(
      name: "CELProtobufTests",
      dependencies: [
        "CEL", "CELProtobuf", "CELSpecProtos", "CELGoTestProtos",
        .product(name: "SwiftProtobuf", package: "swift-protobuf"),
      ],
      swiftSettings: [.swiftLanguageMode(.v6)]
    ),
    .target(
      name: "CELPolicy",
      dependencies: ["CEL", "CELExtensions", .product(name: "Yams", package: "Yams")],
      swiftSettings: [.swiftLanguageMode(.v6)]
    ),
    .target(
      name: "CELTest",
      dependencies: ["CEL", "CELPolicy"],
      swiftSettings: [.swiftLanguageMode(.v6)]
    ),
    // The cel-swift command line tool: eval, check, parse, repl (see Sources/cel-swift/Command.swift).
    .executableTarget(
      name: "cel-swift",
      dependencies: ["CEL", "CELExtensions", "CELCommandLine"],
      swiftSettings: [.swiftLanguageMode(.v6)]
    ),
    // Parse/check/plan/eval benchmarks against cel-go: tools/bench/run.sh
    .executableTarget(
      name: "CELBenchmarks",
      dependencies: ["CEL", "CELExtensions"],
      path: "Benchmarks/CELBenchmarks",
      swiftSettings: [.swiftLanguageMode(.v6)]
    ),
    .testTarget(
      name: "CELTests",
      dependencies: ["CEL", "CELExtensions", "CELProtobuf", "CELGoTestProtos"],
      exclude: ["ParserFixtures", "PartialFixtures"],
      swiftSettings: [.swiftLanguageMode(.v6)]
    ),
    .testTarget(
      name: "CELConformanceTests",
      dependencies: [
        "CEL",
        "CELExtensions",
        "CELProtobuf",
        "CELSpecProtos",
        .product(name: "SwiftProtobuf", package: "swift-protobuf"),
      ],
      exclude: ["skip.txt", "passing.txt"],
      swiftSettings: [.swiftLanguageMode(.v6)]
    ),
    // Differential tests against cel-go through tools/oracle; see the test file header.
    .testTarget(
      name: "CELDifferentialTests",
      dependencies: [
        "CEL", "CELExtensions", "CELProtobuf", "CELSpecProtos",
        .product(name: "SwiftProtobuf", package: "swift-protobuf"),
      ],
      exclude: ["regressions.jsonl"],
      swiftSettings: [.swiftLanguageMode(.v6)]
    ),
    .testTarget(
      name: "CELPolicyTests",
      dependencies: ["CEL", "CELPolicy", "CELProtobuf", "CELGoTestProtos"],
      exclude: ["Goldens"],
      swiftSettings: [.swiftLanguageMode(.v6)]
    ),
    .testTarget(
      name: "CELTestTests",
      dependencies: ["CEL", "CELTest", "CELPolicy", "CELCommandLine"],
      swiftSettings: [.swiftLanguageMode(.v6)]
    ),
    // `cel-swift policy test` and the cel-go test fixtures, shared with CELTestTests. Not a product.
    .target(
      name: "CELCommandLine",
      dependencies: ["CEL", "CELPolicy", "CELTest", "CELProtobuf", "CELGoTestProtos"],
      swiftSettings: [.swiftLanguageMode(.v6)]
    ),
    .target(
      name: "CELExtensions",
      dependencies: ["CEL", "CELRegex"],
      swiftSettings: [.swiftLanguageMode(.v6)]
    ),
    .testTarget(
      name: "CELExtensionsTests",
      dependencies: ["CEL", "CELExtensions"],
      resources: [.copy("Resources")],
      swiftSettings: [.swiftLanguageMode(.v6)]
    ),
    // Idiomatic Swift over CEL and CELPolicy: Codable facts and results, schemas from Swift types,
    // typed functions and programs. See docs/ergonomics.md.
    .target(
      name: "CELSwift",
      dependencies: ["CEL", "CELPolicy"],
      swiftSettings: [.swiftLanguageMode(.v6)]
    ),
    .testTarget(
      name: "CELSwiftTests",
      dependencies: ["CEL", "CELPolicy", "CELSwift"],
      swiftSettings: [.swiftLanguageMode(.v6)]
    ),
    .target(
      name: "CELRegex",
      swiftSettings: [.swiftLanguageMode(.v6)]
    ),
    .testTarget(
      name: "CELRegexTests",
      dependencies: ["CELRegex"],
      resources: [.copy("Resources")],
      swiftSettings: [.swiftLanguageMode(.v6)]
    ),
  ]
)

// libFuzzer targets, only with CEL_FUZZ=1 (Linux, `-sanitize=fuzzer`); see Fuzz/README.md.
if Context.environment["CEL_FUZZ"] == "1" {
  package.targets.append(.target(name: "CELFuzzDriver"))
  package.targets.append(
    .target(
      name: "CELFuzzSupport",
      dependencies: ["CEL", "CELProtobuf", "CELSpecProtos"],
      swiftSettings: [.swiftLanguageMode(.v6)]
    ))
  for name in ["cel-fuzz-parser", "cel-fuzz-checker", "cel-fuzz-evaluator"] {
    package.targets.append(
      .executableTarget(
        name: name,
        dependencies: ["CELFuzzDriver", "CELFuzzSupport"],
        swiftSettings: [.swiftLanguageMode(.v6), .unsafeFlags(["-parse-as-library"])]
      ))
  }
  // Replays inputs through the target bodies without libFuzzer (any platform), for leak checks.
  package.targets.append(
    .executableTarget(
      name: "cel-fuzz-leakcheck", dependencies: ["CELFuzzSupport"], swiftSettings: [.swiftLanguageMode(.v6)]))
}
