// Command test-types writes the message field tables and enum values of the protobuf test types
// (cel-go's google.expr.proto2/proto3 TestAllTypes and the cel-spec conformance TestAllTypes, with all
// the files they import) as Swift source, so Swift tests can type-check against them without a protobuf
// runtime. Field types are what cel-go's registry reports to the checker.
//
// Usage (from the repository root):
//
//	(cd tools/test-types && go run .) > Tests/CELTests/Fixtures/TestTypeTables.swift
//	(cd tools/test-types && go run . -name ConformanceTypeTables -import CEL \
//	    -prefix cel.expr.conformance.,google.protobuf.) > Tests/CELConformanceTests/ConformanceTypeTables.swift
package main

import (
	"flag"
	"fmt"
	"os"
	"sort"
	"strings"

	"cel.dev/cel-go/common/types"
	"cel.dev/cel-go/common/types/pb"
	proto2pb "cel.dev/cel-go/test/proto2pb"
	proto3pb "cel.dev/cel-go/test/proto3pb"
	test2pb "cel.dev/expr/conformance/proto2"
	test3pb "cel.dev/expr/conformance/proto3"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"
)

func main() {
	enumName := flag.String("name", "TestTypeTables", "name of the generated Swift enum")
	importLine := flag.String("import", "@testable import CEL", "import line of the generated file")
	prefixes := flag.String("prefix", "", "comma-separated type and enum name prefixes to keep (default all)")
	flag.Parse()
	keep := func(name string) bool {
		if *prefixes == "" {
			return true
		}
		for _, p := range strings.Split(*prefixes, ",") {
			if strings.HasPrefix(name, p) {
				return true
			}
		}
		return false
	}
	msgs := []proto.Message{
		&proto2pb.TestAllTypes{}, &proto3pb.TestAllTypes{},
		&test2pb.TestAllTypes{}, &test2pb.Proto2ExtensionScopedMessage{}, &test3pb.TestAllTypes{},
	}
	reg, err := types.NewRegistry(types.ProtoTypeDefs(msgs...))
	if err != nil {
		fail(err)
	}
	db := pb.NewDb()
	// Register every file the messages' files import, as types.ProtoTypeDefs does, and collect the
	// extension fields declared anywhere in them by extended message.
	extensions := map[string][]protoreflect.ExtensionDescriptor{}
	seen := map[string]bool{}
	var register func(fd protoreflect.FileDescriptor)
	register = func(fd protoreflect.FileDescriptor) {
		if seen[fd.Path()] {
			return
		}
		seen[fd.Path()] = true
		if _, err := db.RegisterDescriptor(fd); err != nil {
			fail(err)
		}
		if err := reg.RegisterDescriptor(fd); err != nil {
			fail(err)
		}
		collectExtensions(fd.Extensions(), extensions)
		collectMessageExtensions(fd.Messages(), extensions)
		for i := 0; i < fd.Imports().Len(); i++ {
			register(fd.Imports().Get(i).FileDescriptor)
		}
	}
	for _, m := range msgs {
		register(m.ProtoReflect().Descriptor().ParentFile())
	}
	typeNames := map[string]bool{}
	enumValues := map[string]int64{}
	for _, fd := range db.FileDescriptions() {
		for _, tn := range fd.GetTypeNames() {
			if keep(tn) {
				typeNames[tn] = true
			}
		}
		for _, en := range fd.GetEnumNames() {
			if !keep(en) {
				continue
			}
			ed, _ := fd.GetEnumDescription(en)
			enumValues[en] = int64(ed.Value())
		}
	}
	names := sortedKeys(typeNames)

	var b strings.Builder
	b.WriteString("// Generated by tools/test-types from cel-go v0.32.0 and cel-spec v0.25.3. Do not edit.\n")
	b.WriteString("//\n// Field tables of the protobuf test messages (cel-go google.expr.proto2/proto3.test and cel-spec\n")
	b.WriteString("// cel.expr.conformance TestAllTypes, plus everything they import), as cel-go's registry types them.\n\n")
	fmt.Fprintf(&b, "%s\n\n", *importLine)
	fmt.Fprintf(&b, "enum %s {\n", *enumName)
	b.WriteString("  struct Field {\n    let name: String\n    let jsonName: String\n    let type: CELType\n  }\n\n")
	b.WriteString("  static let messages: [String: [Field]] = [\n")
	for _, tn := range names {
		td, _ := db.DescribeType(tn)
		fmt.Fprintf(&b, "    %q: [\n", tn)
		fieldNames, _ := reg.FindStructFieldNames(tn)
		sort.Strings(fieldNames)
		for _, fn := range fieldNames {
			ft, found := reg.FindStructFieldType(tn, fn)
			if !found {
				fail(fmt.Errorf("no field %s.%s", tn, fn))
			}
			fdesc, _ := td.FieldByName(fn)
			fmt.Fprintf(&b, "      Field(name: %q, jsonName: %q, type: %s),\n", fn, fdesc.JSONName(), swiftType(ft.Type))
		}
		var extNames []string
		for _, ext := range extensions[tn] {
			extNames = append(extNames, string(ext.FullName()))
		}
		sort.Strings(extNames)
		for _, en := range extNames {
			ft, found := reg.FindStructFieldType(tn, en)
			if !found {
				fail(fmt.Errorf("no extension field %s.%s", tn, en))
			}
			fmt.Fprintf(&b, "      Field(name: %q, jsonName: %q, type: %s),\n", en, en, swiftType(ft.Type))
		}
		b.WriteString("    ],\n")
	}
	b.WriteString("  ]\n\n")
	b.WriteString("  static let enumValues: [String: Int64] = [\n")
	for _, en := range sortedKeys(enumValues) {
		fmt.Fprintf(&b, "    %q: %d,\n", en, enumValues[en])
	}
	b.WriteString("  ]\n}\n")
	os.Stdout.WriteString(b.String())
}

func collectExtensions(exts protoreflect.ExtensionDescriptors, out map[string][]protoreflect.ExtensionDescriptor) {
	for i := 0; i < exts.Len(); i++ {
		ext := exts.Get(i)
		name := string(ext.ContainingMessage().FullName())
		out[name] = append(out[name], ext)
	}
}

func collectMessageExtensions(msgs protoreflect.MessageDescriptors, out map[string][]protoreflect.ExtensionDescriptor) {
	for i := 0; i < msgs.Len(); i++ {
		collectExtensions(msgs.Get(i).Extensions(), out)
		collectMessageExtensions(msgs.Get(i).Messages(), out)
	}
}

func swiftType(t *types.Type) string {
	if strings.HasPrefix(t.DeclaredTypeName(), "wrapper(") {
		return fmt.Sprintf(".wrapper(%s)", kindType(t))
	}
	return kindType(t)
}

func kindType(t *types.Type) string {
	switch t.Kind() {
	case types.AnyKind:
		return ".any"
	case types.BoolKind:
		return ".bool"
	case types.BytesKind:
		return ".bytes"
	case types.DoubleKind:
		return ".double"
	case types.DurationKind:
		return ".duration"
	case types.DynKind:
		return ".dyn"
	case types.IntKind:
		return ".int"
	case types.ListKind:
		return fmt.Sprintf(".list(%s)", swiftType(t.Parameters()[0]))
	case types.MapKind:
		return fmt.Sprintf(".map(key: %s, value: %s)", swiftType(t.Parameters()[0]), swiftType(t.Parameters()[1]))
	case types.NullTypeKind:
		return ".null"
	case types.StringKind:
		return ".string"
	case types.StructKind:
		return fmt.Sprintf(".object(%q)", t.TypeName())
	case types.TimestampKind:
		return ".timestamp"
	case types.UintKind:
		return ".uint"
	}
	fail(fmt.Errorf("unsupported field type %v", t))
	return ""
}

func sortedKeys[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "test-types:", err)
	os.Exit(1)
}
