// Copyright 2018 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Test support ported from cel-go parser/parser_test.go (adorners, RelativeSource) plus fixture loading.
// Fixtures in Tests/CELTests/ParserFixtures are generated by tools/parsedump from cel-go itself.

import Foundation
import Testing

@testable import CEL

enum ParserFixtures {
  static func url(_ name: String) -> URL {
    URL(fileURLWithPath: #filePath).deletingLastPathComponent().appendingPathComponent("ParserFixtures")
      .appendingPathComponent(name)
  }

  static func load<T: Decodable>(_ name: String, as type: T.Type) -> T {
    do {
      let data = try Data(contentsOf: url(name))
      return try JSONDecoder().decode(T.self, from: data)
    } catch {
      fatalError("cannot load fixture \(name): \(error)")
    }
  }
}

/// cel-go's `test.Compare`: equality ignoring all whitespace.
func stripWhitespace(_ s: String) -> String {
  String(String.UnicodeScalarView(s.unicodeScalars.filter { !" \n\t\r".unicodeScalars.contains($0) }))
}

/// The `kindAndIDAdorner` of cel-go's parser tests: `^#<id>:<proto kind>#`, or the macro function name.
struct KindAndIDAdorner: DebugAdorner {
  /// cel-go's TestParse uses the adorner without source info, so macro calls are not resolved.
  var sourceInfo: SourceInfo? = nil

  func metadata(for element: DebugElement) -> String {
    switch element {
    case .expr(let e):
      if let macroCall = sourceInfo?.macroCall(e.id), let call = macroCall.asCall {
        return "^#\(e.id):\(call.function)#"
      }
      let valType: String
      switch e.kind {
      case .call: valType = "*expr.Expr_CallExpr"
      case .comprehension: valType = "*expr.Expr_ComprehensionExpr"
      case .ident: valType = "*expr.Expr_IdentExpr"
      case .literal(let c):
        switch c {
        case .bool: valType = "*expr.Constant_BoolValue"
        case .bytes: valType = "*expr.Constant_BytesValue"
        case .double: valType = "*expr.Constant_DoubleValue"
        case .int: valType = "*expr.Constant_Int64Value"
        case .null: valType = "*expr.Constant_NullValue"
        case .string: valType = "*expr.Constant_StringValue"
        case .uint: valType = "*expr.Constant_Uint64Value"
        }
      case .list: valType = "*expr.Expr_ListExpr"
      case .map, .struct: valType = "*expr.Expr_StructExpr"
      case .select: valType = "*expr.Expr_SelectExpr"
      case .unspecified: valType = ""
      }
      return "^#\(e.id):\(valType)#"
    case .entry(let e):
      return "^#\(e.id):*expr.Expr_CreateStruct_Entry#"
    }
  }
}

/// The `locationAdorner` of cel-go's parser tests: `^#<id>[<line>,<column>]#`.
struct LocationAdorner: DebugAdorner {
  let sourceInfo: SourceInfo

  func metadata(for element: DebugElement) -> String {
    let loc = sourceInfo.startLocation(element.id)
    return "^#\(element.id)[\(loc.line),\(loc.column)]#"
  }
}

/// cel-go's `convertMacroCallsToString`.
func macroCallsString(_ sourceInfo: SourceInfo) -> String {
  sourceInfo.macroCalls.keys.sorted(by: >).compactMap { key -> String? in
    guard let call = sourceInfo.macroCalls[key]?.asCall else {
      return nil
    }
    let callWithID: Expr
    if let target = call.target {
      callWithID = .memberCall(id: key, function: call.function, target: target, args: call.args)
    } else {
      callWithID = .call(id: key, function: call.function, args: call.args)
    }
    return ExprDebug.toAdornedDebugString(callWithID, adorner: KindAndIDAdorner(sourceInfo: sourceInfo))
  }.joined(separator: ",\n")
}

/// An embedded source element within a larger source (cel-go parser_test.go `RelativeSource`).
struct RelativeSource: Source {
  let source: TextSource
  let localSource: TextSource
  let absoluteLocation: Location

  var content: String { localSource.content }
  var scalars: [Unicode.Scalar] { localSource.scalars }
  var description: String { source.description }
  var lineOffsets: [Int32] { source.lineOffsets }

  func locationOffset(_ location: Location) -> Int32? {
    source.locationOffset(location)
  }

  func offsetLocation(_ offset: Int32) -> Location? {
    guard let absOffset = source.locationOffset(absoluteLocation) else {
      return nil
    }
    return source.offsetLocation(absOffset + offset)
  }

  func newLocation(line: Int, column: Int) -> Location {
    source.newLocation(line: line, column: column)
  }

  func snippet(line: Int) -> String? {
    source.snippet(line: line)
  }
}

/// A parse result recorded from cel-go by tools/parsedump.
struct ParseRecord: Decodable, Sendable, CustomStringConvertible {
  struct MacroCall: Decodable, Sendable {
    let id: Int64
    let debug: String
  }

  let file: String?
  let name: String?
  let expr: String
  let config: Int
  let debug: String?
  let offsets: [[Int64]]?
  let macroCalls: [MacroCall]?
  let errors: String?

  var description: String {
    if let file, let name {
      return "\(file)/\(name)"
    }
    return expr
  }

  /// The parser configurations of tools/parsedump.
  func parser() throws -> Parser {
    switch config {
    case 0:
      return try Parser(
        .macros(Macro.allMacros), .enableOptionalSyntax(true), .enableIdentEscapeSyntax(true),
        .populateMacroCalls(true))
    case 1:
      return try Parser(
        .macros(Macro.allMacros), .maxRecursionDepth(32), .errorRecoveryLimit(4),
        .errorRecoveryLookaheadTokenLimit(4), .populateMacroCalls(true))
    default:
      return try Parser(
        .enableOptionalSyntax(true), .enableIdentEscapeSyntax(true), .populateMacroCalls(true))
    }
  }

  /// Parses the expression and returns the first difference to cel-go, or nil when identical.
  func mismatch() throws -> String? {
    let (ast, errors) = try parser().parse(TextSource(expr))
    if !errors.isEmpty || self.errors != nil {
      let got = errors.isEmpty ? "" : errors.toDisplayString()
      let want = self.errors ?? ""
      return got == want ? nil : "errors differ:\n got: \(got)\nwant: \(want)"
    }
    let info = ast.sourceInfo
    let gotDebug = ExprDebug.toAdornedDebugString(ast.expr, adorner: KindAndIDAdorner(sourceInfo: info))
    if gotDebug != debug {
      return "debug differs:\n got: \(gotDebug)\nwant: \(debug ?? "")"
    }
    let gotOffsets = info.offsetRanges.keys.sorted().map { id -> [Int64] in
      let o = info.offsetRanges[id] ?? OffsetRange(start: 0, stop: 0)
      return [id, Int64(o.start), Int64(o.stop)]
    }
    if gotOffsets != (offsets ?? []) {
      return "offsets differ:\n got: \(gotOffsets)\nwant: \(offsets ?? [])"
    }
    let gotCalls = info.macroCalls.keys.sorted().map { id in
      "\(id): \(ExprDebug.toDebugStringWithIDs(info.macroCalls[id] ?? .unspecified(id: 0)))"
    }
    let wantCalls = (macroCalls ?? []).map { "\($0.id): \($0.debug)" }
    if gotCalls != wantCalls {
      return "macro calls differ:\n got: \(gotCalls)\nwant: \(wantCalls)"
    }
    return nil
  }
}

/// A row of cel-go's TestUnparse table (parser/unparser_test.go).
struct UnparserTestCase: Decodable, Sendable, CustomTestStringConvertible {
  let name: String
  let `in`: String
  let out: String?
  let requiresMacroCalls: Bool?
  let options: [String]?

  var testDescription: String { name }
}
