// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by protoc-gen-cel-swift.
// Source: google/protobuf/any.proto

import CEL
import SwiftProtobuf

/// The CEL description of `google/protobuf/any.proto`, for `ProtobufTypes`.
let Google_Protobuf_Any_CELFile = ProtobufFile(
  path: "google/protobuf/any.proto",
  messageTypes: [
    ProtobufMessageType(Google_Protobuf_Any.self, fields: _celFields_Google_Protobuf_Any()),
  ],
  enumTypes: [
  ],
  extensions: [
  ],
  dependencies: []
)

fileprivate func _celFields_Google_Protobuf_Any() -> [ProtobufField<Google_Protobuf_Any>] {
  var fields: [ProtobufField<Google_Protobuf_Any>] = []
  fields.reserveCapacity(2)
  fields.append(.singular("type_url", number: 1, \Google_Protobuf_Any.typeURL, .string))
  fields.append(.singular("value", number: 2, \Google_Protobuf_Any.value, .bytes))
  return fields
}
