// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by protoc-gen-cel-swift.
// Source: google/protobuf/duration.proto

import CEL
import SwiftProtobuf

/// The CEL description of `google/protobuf/duration.proto`, for `ProtobufTypes`.
let Google_Protobuf_Duration_CELFile = ProtobufFile(
  path: "google/protobuf/duration.proto",
  messageTypes: [
    ProtobufMessageType(Google_Protobuf_Duration.self, fields: _celFields_Google_Protobuf_Duration()),
  ],
  enumTypes: [
  ],
  extensions: [
  ],
  dependencies: []
)

fileprivate func _celFields_Google_Protobuf_Duration() -> [ProtobufField<Google_Protobuf_Duration>] {
  var fields: [ProtobufField<Google_Protobuf_Duration>] = []
  fields.reserveCapacity(2)
  fields.append(.singular("seconds", number: 1, \Google_Protobuf_Duration.seconds, .int64))
  fields.append(.singular("nanos", number: 2, \Google_Protobuf_Duration.nanos, .int32))
  return fields
}
