// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by protoc-gen-cel-swift.
// Source: google/protobuf/field_mask.proto

import CEL
import SwiftProtobuf

/// The CEL description of `google/protobuf/field_mask.proto`, for `ProtobufTypes`.
let Google_Protobuf_FieldMask_CELFile = ProtobufFile(
  path: "google/protobuf/field_mask.proto",
  messageTypes: [
    ProtobufMessageType(Google_Protobuf_FieldMask.self, fields: _celFields_Google_Protobuf_FieldMask()),
  ],
  enumTypes: [
  ],
  extensions: [
  ],
  dependencies: []
)

fileprivate func _celFields_Google_Protobuf_FieldMask() -> [ProtobufField<Google_Protobuf_FieldMask>] {
  var fields: [ProtobufField<Google_Protobuf_FieldMask>] = []
  fields.reserveCapacity(1)
  fields.append(.repeated("paths", number: 1, \Google_Protobuf_FieldMask.paths, .string))
  return fields
}
