// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by protoc-gen-cel-swift.
// Source: google/protobuf/wrappers.proto

import CEL
import SwiftProtobuf

/// The CEL description of `google/protobuf/wrappers.proto`, for `ProtobufTypes`.
let Google_Protobuf_Wrappers_CELFile = ProtobufFile(
  path: "google/protobuf/wrappers.proto",
  messageTypes: [
    ProtobufMessageType(Google_Protobuf_DoubleValue.self, fields: _celFields_Google_Protobuf_DoubleValue()),
    ProtobufMessageType(Google_Protobuf_FloatValue.self, fields: _celFields_Google_Protobuf_FloatValue()),
    ProtobufMessageType(Google_Protobuf_Int64Value.self, fields: _celFields_Google_Protobuf_Int64Value()),
    ProtobufMessageType(Google_Protobuf_UInt64Value.self, fields: _celFields_Google_Protobuf_UInt64Value()),
    ProtobufMessageType(Google_Protobuf_Int32Value.self, fields: _celFields_Google_Protobuf_Int32Value()),
    ProtobufMessageType(Google_Protobuf_UInt32Value.self, fields: _celFields_Google_Protobuf_UInt32Value()),
    ProtobufMessageType(Google_Protobuf_BoolValue.self, fields: _celFields_Google_Protobuf_BoolValue()),
    ProtobufMessageType(Google_Protobuf_StringValue.self, fields: _celFields_Google_Protobuf_StringValue()),
    ProtobufMessageType(Google_Protobuf_BytesValue.self, fields: _celFields_Google_Protobuf_BytesValue()),
  ],
  enumTypes: [
  ],
  extensions: [
  ],
  dependencies: []
)

fileprivate func _celFields_Google_Protobuf_DoubleValue() -> [ProtobufField<Google_Protobuf_DoubleValue>] {
  var fields: [ProtobufField<Google_Protobuf_DoubleValue>] = []
  fields.reserveCapacity(1)
  fields.append(.singular("value", number: 1, \Google_Protobuf_DoubleValue.value, .double))
  return fields
}

fileprivate func _celFields_Google_Protobuf_FloatValue() -> [ProtobufField<Google_Protobuf_FloatValue>] {
  var fields: [ProtobufField<Google_Protobuf_FloatValue>] = []
  fields.reserveCapacity(1)
  fields.append(.singular("value", number: 1, \Google_Protobuf_FloatValue.value, .float))
  return fields
}

fileprivate func _celFields_Google_Protobuf_Int64Value() -> [ProtobufField<Google_Protobuf_Int64Value>] {
  var fields: [ProtobufField<Google_Protobuf_Int64Value>] = []
  fields.reserveCapacity(1)
  fields.append(.singular("value", number: 1, \Google_Protobuf_Int64Value.value, .int64))
  return fields
}

fileprivate func _celFields_Google_Protobuf_UInt64Value() -> [ProtobufField<Google_Protobuf_UInt64Value>] {
  var fields: [ProtobufField<Google_Protobuf_UInt64Value>] = []
  fields.reserveCapacity(1)
  fields.append(.singular("value", number: 1, \Google_Protobuf_UInt64Value.value, .uint64))
  return fields
}

fileprivate func _celFields_Google_Protobuf_Int32Value() -> [ProtobufField<Google_Protobuf_Int32Value>] {
  var fields: [ProtobufField<Google_Protobuf_Int32Value>] = []
  fields.reserveCapacity(1)
  fields.append(.singular("value", number: 1, \Google_Protobuf_Int32Value.value, .int32))
  return fields
}

fileprivate func _celFields_Google_Protobuf_UInt32Value() -> [ProtobufField<Google_Protobuf_UInt32Value>] {
  var fields: [ProtobufField<Google_Protobuf_UInt32Value>] = []
  fields.reserveCapacity(1)
  fields.append(.singular("value", number: 1, \Google_Protobuf_UInt32Value.value, .uint32))
  return fields
}

fileprivate func _celFields_Google_Protobuf_BoolValue() -> [ProtobufField<Google_Protobuf_BoolValue>] {
  var fields: [ProtobufField<Google_Protobuf_BoolValue>] = []
  fields.reserveCapacity(1)
  fields.append(.singular("value", number: 1, \Google_Protobuf_BoolValue.value, .bool))
  return fields
}

fileprivate func _celFields_Google_Protobuf_StringValue() -> [ProtobufField<Google_Protobuf_StringValue>] {
  var fields: [ProtobufField<Google_Protobuf_StringValue>] = []
  fields.reserveCapacity(1)
  fields.append(.singular("value", number: 1, \Google_Protobuf_StringValue.value, .string))
  return fields
}

fileprivate func _celFields_Google_Protobuf_BytesValue() -> [ProtobufField<Google_Protobuf_BytesValue>] {
  var fields: [ProtobufField<Google_Protobuf_BytesValue>] = []
  fields.reserveCapacity(1)
  fields.append(.singular("value", number: 1, \Google_Protobuf_BytesValue.value, .bytes))
  return fields
}
