#!/usr/bin/env python3
"""Generates Tests/CELTests/Fixtures/RuntimeCostFixtures.swift from cel-go via tools/oracle.

For every expression below, records cel-go's result and actual runtime cost (cel.CostTracking) in checked
and parse-only mode, so the interpreter's runtime cost port (interpreter/runtimecost.go) is pinned to
cel-go's numbers.

Usage (from the repository root):
  (cd tools/oracle && go build -o /tmp/cel-oracle .)
  python3 tools/cost-fixtures/gen_cost_fixtures.py /tmp/cel-oracle > Tests/CELTests/Fixtures/RuntimeCostFixtures.swift
"""
import json
import subprocess
import sys

EXPRS = [
    '"Hello World!"',
    "1 + 1", "1 - 1", "2 * 3", "6 / 3", "7 % 3", "-(1)", "!true",
    "1 < 2", "1 <= 2", "2 > 1", "2 >= 1", "1 == 2", "1 != 2",
    "true ? 1 : 2", "false ? 1 : 2", "true || false", "false || false", "true && false", "false && true",
    "[1, 2, 3]", "{'a': 1, 'b': 2, 'c': 3}", "[1, 2, 3][1]", "{'a': 1}['a']", "{'a': {'b': 2}}.a.b",
    "has({'a': 1}.a)", "has({'a': {'b': 1}}.a.b)", "{'a': 1}.?a", "{'a': 1}.?b.orValue(2)",
    "2 in [1, 2, 3]", "'a' in {'a': 1}", "size('123')", "'123'.size()", "size([1, 2])",
    "'12345678901234567890' == '123456789012345678901234567890'",
    "'abc' < 'abd'", "b'abc' < b'abd'", "'hello' + ' world'", "b'hello' + b' world'",
    "'hello world'.contains('o w')", "'hello world'.startsWith('hello')", "'hello world'.endsWith('world')",
    "'hello world'.matches('w.r')", "matches('123', '[0-9]+')",
    "string(1)", "string(b'abc')", "bytes('abc')", "int('42')", "double('1.5')", "uint(1)",
    "duration('1s')", "timestamp('2020-01-01T00:00:00Z')", "timestamp('2020-01-01T00:00:00Z').getFullYear()",
    "type(1) == int", "dyn(1) + 1",
    "[1, 2, 3].all(x, x > 0)", "[1, 2, 3].exists(x, x > 2)", "[1, 2, 3].exists_one(x, x > 2)",
    "[1, 2, 3].map(x, x * 2)", "[1, 2, 3].map(x, x > 1, x * 2)", "[1, 2, 3].filter(x, x > 1)",
    "[1, 2, 3].all(x, [x].all(y, y > 0))", "{'a': 1, 'b': 2}.all(k, k != 'c')",
    "[[1, 2], [3]].map(l, l.size())", "[1, 2, 3].map(x, [x, x]).size()",
    "['a', 'bb', 'ccc'].filter(s, s.size() > 1).map(s, s + '!')",
    "[1, 2, 3, 4, 5].map(x, x * 2).filter(y, y > 4).size() == 3",
    "{'k': [1, 2, 3]}.k.exists(x, x == 2) && {'k': 'v'}.k.startsWith('v')",
    "([1, 2] + [3])[2]", "[1, 2] + [3] == [1, 2, 3]", "{'a': [1, 2]}.a[1] + 1",
    "1/0 != 0 || true", "[1, 2][5] == 1 || true",
    "[?{'a': 1}.?a, ?{}.?b]", "{?'a': optional.of(1), ?'b': optional.none()}",
    "optional.of(1).hasValue()", "optional.none().orValue(3)", "optional.of(2).value() + 1",
]


def run(oracle, exprs, check):
    reqs = "".join(
        json.dumps({"id": str(i), "kind": "eval", "check": check, "expr": e,
                    "config": {"extensions": [{"name": "optional"}]}}) + "\n"
        for i, e in enumerate(exprs))
    out = subprocess.run([oracle], input=reqs, capture_output=True, text=True, check=True).stdout
    results = {}
    for line in out.splitlines():
        d = json.loads(line)
        results[int(d["id"])] = d
    return results


def swift_string(s):
    return json.dumps(s)


def main():
    oracle = sys.argv[1]
    checked = run(oracle, EXPRS, True)
    unchecked = run(oracle, EXPRS, False)
    print("// Generated by tools/cost-fixtures/gen_cost_fixtures.py from cel-go v0.32.0 via tools/oracle.")
    print("// Do not edit by hand.")
    print()
    print("/// (expression, checked cost, parse-only cost, cel-go result is an error)")
    print("let runtimeCostFixtures: [(String, UInt64, UInt64, Bool)] = [")
    for i, e in enumerate(EXPRS):
        c, u = checked[i], unchecked[i]
        if "oracle_error" in c or "error" in c or "oracle_error" in u or "error" in u:
            sys.stderr.write(f"skipping {e}: {c} {u}\n")
            continue
        is_err = "error" in c["result"]
        print(f"  ({swift_string(e)}, {c['cost']}, {u['cost']}, {'true' if is_err else 'false'}),")
    print("]")


if __name__ == "__main__":
    main()
