// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: cel/expr/conformance/test/suite.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Unit tests and end-to-end conformance tests.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// A test suite is a collection of tests designed to evaluate the correctness of
/// a CEL policy, a CEL expression or the conformance of a CEL implementation to
/// the standard specification.
package struct Cel_Expr_Conformance_Test_TestSuite: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The name of the test suite.
  package var name: String = String()

  /// Description of the test suite.
  package var description_p: String = String()

  /// Test sections of the test suite.
  /// Each section represents a behavior to be tested.
  package var sections: [Cel_Expr_Conformance_Test_TestSection] = []

  package var unknownFields = SwiftProtobuf.UnknownStorage()

  package init() {}
}

/// A collection of related test cases.
package struct Cel_Expr_Conformance_Test_TestSection: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Name of the test section.
  package var name: String = String()

  /// Description of the test section.
  package var description_p: String = String()

  /// Test cases of the test section.
  /// Each test case represents a test scenario.
  package var tests: [Cel_Expr_Conformance_Test_TestCase] = []

  package var unknownFields = SwiftProtobuf.UnknownStorage()

  package init() {}
}

/// A test to validate a CEL policy or expression. The test case encompasses
/// evaluation of the compiled expression using the provided input bindings and
/// asserting the result against the expected result.
/// It can also validate a raw CEL expression string through parse, check and
/// eval stages, making use of the augmenting CEL environment if provided.
package struct Cel_Expr_Conformance_Test_TestCase: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Name of the test case.
  package var name: String = String()

  /// A description of the test.
  package var description_p: String = String()

  /// The text of the CEL expression.
  package var expr: String = String()

  /// Serialized environment to be used for compilation and evaluation of the
  /// CEL expression for the current test case.
  /// This option allows validating the same expression against multiple
  /// environments.
  package var env: Cel_Expr_Conformance_Environment {
    get {_env ?? Cel_Expr_Conformance_Environment()}
    set {_env = newValue}
  }
  /// Returns true if `env` has been explicitly set.
  package var hasEnv: Bool {self._env != nil}
  /// Clears the value of `env`. Subsequent reads from it will return its default value.
  package mutating func clearEnv() {self._env = nil}

  /// A map representing a variable binding where the key is the name of the
  /// input variable.
  package var input: Dictionary<String,Cel_Expr_Conformance_Test_InputValue> = [:]

  /// Input in the form of a context proto for the test case.
  /// Note: Only one of `input_bindings` and `input_context` can be provided. Providing
  /// both should result in an error.
  package var inputContext: Cel_Expr_Conformance_Test_InputContext {
    get {_inputContext ?? Cel_Expr_Conformance_Test_InputContext()}
    set {_inputContext = newValue}
  }
  /// Returns true if `inputContext` has been explicitly set.
  package var hasInputContext: Bool {self._inputContext != nil}
  /// Clears the value of `inputContext`. Subsequent reads from it will return its default value.
  package mutating func clearInputContext() {self._inputContext = nil}

  /// Expected result of the test case.
  package var output: Cel_Expr_Conformance_Test_TestOutput {
    get {_output ?? Cel_Expr_Conformance_Test_TestOutput()}
    set {_output = newValue}
  }
  /// Returns true if `output` has been explicitly set.
  package var hasOutput: Bool {self._output != nil}
  /// Clears the value of `output`. Subsequent reads from it will return its default value.
  package mutating func clearOutput() {self._output = nil}

  /// If specified validates that the deduced type at check time matches
  /// If the result kind is not set and this field is set, the test is considered
  /// "check-only".
  package var deducedType: Cel_Expr_Type {
    get {_deducedType ?? Cel_Expr_Type()}
    set {_deducedType = newValue}
  }
  /// Returns true if `deducedType` has been explicitly set.
  package var hasDeducedType: Bool {self._deducedType != nil}
  /// Clears the value of `deducedType`. Subsequent reads from it will return its default value.
  package mutating func clearDeducedType() {self._deducedType = nil}

  /// Bypass the type-checking and only attempt to evaluate the parsed
  /// expression.
  package var disableCheck: Bool = false

  package var unknownFields = SwiftProtobuf.UnknownStorage()

  package init() {}

  fileprivate var _env: Cel_Expr_Conformance_Environment? = nil
  fileprivate var _inputContext: Cel_Expr_Conformance_Test_InputContext? = nil
  fileprivate var _output: Cel_Expr_Conformance_Test_TestOutput? = nil
  fileprivate var _deducedType: Cel_Expr_Type? = nil
}

/// Input context proto for the test case
package struct Cel_Expr_Conformance_Test_InputContext: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The type of input context for the test case
  package var inputContextKind: Cel_Expr_Conformance_Test_InputContext.OneOf_InputContextKind? = nil

  /// A context message represents an input kind in the form of a proto
  /// message whose type is defined at runtime.
  package var contextMessage: SwiftProtobuf.Google_Protobuf_Any {
    get {
      if case .contextMessage(let v)? = inputContextKind {return v}
      return SwiftProtobuf.Google_Protobuf_Any()
    }
    set {inputContextKind = .contextMessage(newValue)}
  }

  /// A context expression representing a context proto variable. The
  /// fields of the input proto.Messages are used as top-level variables within
  /// an Activation. The expression is evaluated using the cel environment
  /// configured for the test suite.
  package var contextExpr: String {
    get {
      if case .contextExpr(let v)? = inputContextKind {return v}
      return String()
    }
    set {inputContextKind = .contextExpr(newValue)}
  }

  package var unknownFields = SwiftProtobuf.UnknownStorage()

  /// The type of input context for the test case
  package enum OneOf_InputContextKind: Equatable, Sendable {
    /// A context message represents an input kind in the form of a proto
    /// message whose type is defined at runtime.
    case contextMessage(SwiftProtobuf.Google_Protobuf_Any)
    /// A context expression representing a context proto variable. The
    /// fields of the input proto.Messages are used as top-level variables within
    /// an Activation. The expression is evaluated using the cel environment
    /// configured for the test suite.
    case contextExpr(String)

  }

  package init() {}
}

/// The input value for a variable binding
package struct Cel_Expr_Conformance_Test_InputValue: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The type of input value that can be used for a variable binding
  package var kind: Cel_Expr_Conformance_Test_InputValue.OneOf_Kind? = nil

  /// A simple literal value for a variable binding
  package var value: Cel_Expr_Value {
    get {
      if case .value(let v)? = kind {return v}
      return Cel_Expr_Value()
    }
    set {kind = .value(newValue)}
  }

  /// An expression which evaluates to the value of the variable binding.
  /// The expression is evaluated using the same runtime environment as the
  /// one used for evaluating the expression under test.
  package var expr: String {
    get {
      if case .expr(let v)? = kind {return v}
      return String()
    }
    set {kind = .expr(newValue)}
  }

  package var unknownFields = SwiftProtobuf.UnknownStorage()

  /// The type of input value that can be used for a variable binding
  package enum OneOf_Kind: Equatable, Sendable {
    /// A simple literal value for a variable binding
    case value(Cel_Expr_Value)
    /// An expression which evaluates to the value of the variable binding.
    /// The expression is evaluated using the same runtime environment as the
    /// one used for evaluating the expression under test.
    case expr(String)

  }

  package init() {}
}

/// Expected result of the test case.
package struct Cel_Expr_Conformance_Test_TestOutput: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Type of expected result of the test case.
  package var resultKind: Cel_Expr_Conformance_Test_TestOutput.OneOf_ResultKind? = nil

  /// A normal value, which must match the evaluation result exactly via value
  /// equality semantics. This coincides with proto equality, except for:
  /// *   maps are order-agnostic
  /// *   a floating point NaN should match any NaN
  package var resultValue: Cel_Expr_Value {
    get {
      if case .resultValue(let v)? = resultKind {return v}
      return Cel_Expr_Value()
    }
    set {resultKind = .resultValue(newValue)}
  }

  /// An expression to be evaluated using the cel environment configured for
  /// the test suite. The result of this expression must match the result of
  /// the test case.
  package var resultExpr: String {
    get {
      if case .resultExpr(let v)? = resultKind {return v}
      return String()
    }
    set {resultKind = .resultExpr(newValue)}
  }

  /// An error evaluation result set. Success if we match all of the errors in
  /// the set.
  package var evalError: Cel_Expr_ErrorSet {
    get {
      if case .evalError(let v)? = resultKind {return v}
      return Cel_Expr_ErrorSet()
    }
    set {resultKind = .evalError(newValue)}
  }

  /// An unknown evaluation result.
  package var unknown: Cel_Expr_UnknownSet {
    get {
      if case .unknown(let v)? = resultKind {return v}
      return Cel_Expr_UnknownSet()
    }
    set {resultKind = .unknown(newValue)}
  }

  package var unknownFields = SwiftProtobuf.UnknownStorage()

  /// Type of expected result of the test case.
  package enum OneOf_ResultKind: Equatable, Sendable {
    /// A normal value, which must match the evaluation result exactly via value
    /// equality semantics. This coincides with proto equality, except for:
    /// *   maps are order-agnostic
    /// *   a floating point NaN should match any NaN
    case resultValue(Cel_Expr_Value)
    /// An expression to be evaluated using the cel environment configured for
    /// the test suite. The result of this expression must match the result of
    /// the test case.
    case resultExpr(String)
    /// An error evaluation result set. Success if we match all of the errors in
    /// the set.
    case evalError(Cel_Expr_ErrorSet)
    /// An unknown evaluation result.
    case unknown(Cel_Expr_UnknownSet)

  }

  package init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "cel.expr.conformance.test"

extension Cel_Expr_Conformance_Test_TestSuite: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = _protobuf_package + ".TestSuite"
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}description\0\u{1}sections\0")

  public var isInitialized: Bool {
    if !SwiftProtobuf.Internal.areAllInitialized(self.sections) {return false}
    return true
  }

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.description_p) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.sections) }()
      default: break
      }
    }
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if !self.description_p.isEmpty {
      try visitor.visitSingularStringField(value: self.description_p, fieldNumber: 2)
    }
    if !self.sections.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.sections, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Cel_Expr_Conformance_Test_TestSuite, rhs: Cel_Expr_Conformance_Test_TestSuite) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.description_p != rhs.description_p {return false}
    if lhs.sections != rhs.sections {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Cel_Expr_Conformance_Test_TestSection: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = _protobuf_package + ".TestSection"
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}description\0\u{1}tests\0")

  public var isInitialized: Bool {
    if !SwiftProtobuf.Internal.areAllInitialized(self.tests) {return false}
    return true
  }

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.description_p) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.tests) }()
      default: break
      }
    }
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if !self.description_p.isEmpty {
      try visitor.visitSingularStringField(value: self.description_p, fieldNumber: 2)
    }
    if !self.tests.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.tests, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Cel_Expr_Conformance_Test_TestSection, rhs: Cel_Expr_Conformance_Test_TestSection) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.description_p != rhs.description_p {return false}
    if lhs.tests != rhs.tests {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Cel_Expr_Conformance_Test_TestCase: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = _protobuf_package + ".TestCase"
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}description\0\u{1}expr\0\u{1}env\0\u{1}input\0\u{3}input_context\0\u{1}output\0\u{3}deduced_type\0\u{3}disable_check\0")

  public var isInitialized: Bool {
    if let v = self._env, !v.isInitialized {return false}
    return true
  }

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.description_p) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.expr) }()
      case 4: try { try decoder.decodeSingularMessageField(value: &self._env) }()
      case 5: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufString,Cel_Expr_Conformance_Test_InputValue>.self, value: &self.input) }()
      case 6: try { try decoder.decodeSingularMessageField(value: &self._inputContext) }()
      case 7: try { try decoder.decodeSingularMessageField(value: &self._output) }()
      case 8: try { try decoder.decodeSingularMessageField(value: &self._deducedType) }()
      case 9: try { try decoder.decodeSingularBoolField(value: &self.disableCheck) }()
      default: break
      }
    }
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if !self.description_p.isEmpty {
      try visitor.visitSingularStringField(value: self.description_p, fieldNumber: 2)
    }
    if !self.expr.isEmpty {
      try visitor.visitSingularStringField(value: self.expr, fieldNumber: 3)
    }
    try { if let v = self._env {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    } }()
    if !self.input.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufString,Cel_Expr_Conformance_Test_InputValue>.self, value: self.input, fieldNumber: 5)
    }
    try { if let v = self._inputContext {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    } }()
    try { if let v = self._output {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
    } }()
    try { if let v = self._deducedType {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
    } }()
    if self.disableCheck != false {
      try visitor.visitSingularBoolField(value: self.disableCheck, fieldNumber: 9)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Cel_Expr_Conformance_Test_TestCase, rhs: Cel_Expr_Conformance_Test_TestCase) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.description_p != rhs.description_p {return false}
    if lhs.expr != rhs.expr {return false}
    if lhs._env != rhs._env {return false}
    if lhs.input != rhs.input {return false}
    if lhs._inputContext != rhs._inputContext {return false}
    if lhs._output != rhs._output {return false}
    if lhs._deducedType != rhs._deducedType {return false}
    if lhs.disableCheck != rhs.disableCheck {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Cel_Expr_Conformance_Test_InputContext: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = _protobuf_package + ".InputContext"
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}context_message\0\u{3}context_expr\0")

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: SwiftProtobuf.Google_Protobuf_Any?
        var hadOneofValue = false
        if let current = self.inputContextKind {
          hadOneofValue = true
          if case .contextMessage(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.inputContextKind = .contextMessage(v)
        }
      }()
      case 2: try {
        var v: String?
        try decoder.decodeSingularStringField(value: &v)
        if let v = v {
          if self.inputContextKind != nil {try decoder.handleConflictingOneOf()}
          self.inputContextKind = .contextExpr(v)
        }
      }()
      default: break
      }
    }
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.inputContextKind {
    case .contextMessage?: try {
      guard case .contextMessage(let v)? = self.inputContextKind else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .contextExpr?: try {
      guard case .contextExpr(let v)? = self.inputContextKind else { preconditionFailure() }
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Cel_Expr_Conformance_Test_InputContext, rhs: Cel_Expr_Conformance_Test_InputContext) -> Bool {
    if lhs.inputContextKind != rhs.inputContextKind {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Cel_Expr_Conformance_Test_InputValue: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = _protobuf_package + ".InputValue"
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}value\0\u{1}expr\0")

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Cel_Expr_Value?
        var hadOneofValue = false
        if let current = self.kind {
          hadOneofValue = true
          if case .value(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.kind = .value(v)
        }
      }()
      case 2: try {
        var v: String?
        try decoder.decodeSingularStringField(value: &v)
        if let v = v {
          if self.kind != nil {try decoder.handleConflictingOneOf()}
          self.kind = .expr(v)
        }
      }()
      default: break
      }
    }
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.kind {
    case .value?: try {
      guard case .value(let v)? = self.kind else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .expr?: try {
      guard case .expr(let v)? = self.kind else { preconditionFailure() }
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Cel_Expr_Conformance_Test_InputValue, rhs: Cel_Expr_Conformance_Test_InputValue) -> Bool {
    if lhs.kind != rhs.kind {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Cel_Expr_Conformance_Test_TestOutput: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = _protobuf_package + ".TestOutput"
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{4}\u{8}result_value\0\u{3}result_expr\0\u{3}eval_error\0\u{1}unknown\0")

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 8: try {
        var v: Cel_Expr_Value?
        var hadOneofValue = false
        if let current = self.resultKind {
          hadOneofValue = true
          if case .resultValue(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.resultKind = .resultValue(v)
        }
      }()
      case 9: try {
        var v: String?
        try decoder.decodeSingularStringField(value: &v)
        if let v = v {
          if self.resultKind != nil {try decoder.handleConflictingOneOf()}
          self.resultKind = .resultExpr(v)
        }
      }()
      case 10: try {
        var v: Cel_Expr_ErrorSet?
        var hadOneofValue = false
        if let current = self.resultKind {
          hadOneofValue = true
          if case .evalError(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.resultKind = .evalError(v)
        }
      }()
      case 11: try {
        var v: Cel_Expr_UnknownSet?
        var hadOneofValue = false
        if let current = self.resultKind {
          hadOneofValue = true
          if case .unknown(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.resultKind = .unknown(v)
        }
      }()
      default: break
      }
    }
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.resultKind {
    case .resultValue?: try {
      guard case .resultValue(let v)? = self.resultKind else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
    }()
    case .resultExpr?: try {
      guard case .resultExpr(let v)? = self.resultKind else { preconditionFailure() }
      try visitor.visitSingularStringField(value: v, fieldNumber: 9)
    }()
    case .evalError?: try {
      guard case .evalError(let v)? = self.resultKind else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 10)
    }()
    case .unknown?: try {
      guard case .unknown(let v)? = self.resultKind else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 11)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Cel_Expr_Conformance_Test_TestOutput, rhs: Cel_Expr_Conformance_Test_TestOutput) -> Bool {
    if lhs.resultKind != rhs.resultKind {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
