// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: cel/expr/conformance/env_config.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Representation of a CEL Environment, defining what features and extensions
/// are available for conformance testing.
package struct Cel_Expr_Conformance_Environment: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Name of the environment
  package var name: String {
    get {_storage._name}
    set {_uniqueStorage()._name = newValue}
  }

  /// Description for the current environment
  package var description_p: String {
    get {_storage._description_p}
    set {_uniqueStorage()._description_p = newValue}
  }

  /// Sets the namespace (container) for the expression.
  /// This is used to simplify resolution.
  /// For example with container
  ///   `google.rpc.context`
  ///  an identifier of `google.rpc.context.AttributeContext` could be referred
  ///  to simply as `AttributeContext` in the CEL expression.
  package var container: String {
    get {_storage._container}
    set {_uniqueStorage()._container = newValue}
  }

  /// List of abbreviations to be added to the CEL environment
  package var imports: [Cel_Expr_Conformance_Environment.Import] {
    get {_storage._imports}
    set {_uniqueStorage()._imports = newValue}
  }

  /// Set of options to subset a subsettable library
  package var stdlib: Cel_Expr_Conformance_LibrarySubset {
    get {_storage._stdlib ?? Cel_Expr_Conformance_LibrarySubset()}
    set {_uniqueStorage()._stdlib = newValue}
  }
  /// Returns true if `stdlib` has been explicitly set.
  package var hasStdlib: Bool {_storage._stdlib != nil}
  /// Clears the value of `stdlib`. Subsequent reads from it will return its default value.
  package mutating func clearStdlib() {_uniqueStorage()._stdlib = nil}

  /// List of extensions to enable in the CEL environment.
  package var extensions: [Cel_Expr_Conformance_Extension] {
    get {_storage._extensions}
    set {_uniqueStorage()._extensions = newValue}
  }

  /// If set, adds a context declaration from a proto message.
  ///
  /// Context messages have all of their top-level fields available as variables
  /// in the type checker.
  package var contextVariable: Cel_Expr_Conformance_Environment.ContextVariable {
    get {_storage._contextVariable ?? Cel_Expr_Conformance_Environment.ContextVariable()}
    set {_uniqueStorage()._contextVariable = newValue}
  }
  /// Returns true if `contextVariable` has been explicitly set.
  package var hasContextVariable: Bool {_storage._contextVariable != nil}
  /// Clears the value of `contextVariable`. Subsequent reads from it will return its default value.
  package mutating func clearContextVariable() {_uniqueStorage()._contextVariable = nil}

  /// List of declarations to be configured in the CEL environment.
  ///
  /// Note: The CEL environment can be configured with either the
  /// context_variable or a set of ident_decls provided as part of declarations.
  /// Providing both will result in an error.
  package var declarations: [Cel_Expr_Decl] {
    get {_storage._declarations}
    set {_uniqueStorage()._declarations = newValue}
  }

  /// List of validators for validating the parsed ast.
  package var validators: [Cel_Expr_Conformance_Validator] {
    get {_storage._validators}
    set {_uniqueStorage()._validators = newValue}
  }

  /// List of feature flags to be enabled or disabled.
  package var features: [Cel_Expr_Conformance_Feature] {
    get {_storage._features}
    set {_uniqueStorage()._features = newValue}
  }

  /// Disables including the declarations from the standard CEL environment.
  ///
  /// NOTE: Do not disable the standard CEL declarations unless you are aware of
  /// the implications and have discussed your use case on cel-discuss@
  /// or with the members of the cel-governance-team@
  ///
  /// Deprecated: Use LibrarySubset to disable standard cel declarations instead:
  ///   stdlib = LibrarySubset{ disable: true }
  package var disableStandardCelDeclarations: Bool {
    get {_storage._disableStandardCelDeclarations}
    set {_uniqueStorage()._disableStandardCelDeclarations = newValue}
  }

  /// If provided, uses the provided FileDescriptorSet to extend types available
  /// the CEL expression. All "well-known" protobuf messages (google.protobuf.*)
  /// are known to the CEL compiler, but all others must be provided for type
  /// checking.
  package var messageTypeExtension: SwiftProtobuf.Google_Protobuf_FileDescriptorSet {
    get {_storage._messageTypeExtension ?? SwiftProtobuf.Google_Protobuf_FileDescriptorSet()}
    set {_uniqueStorage()._messageTypeExtension = newValue}
  }
  /// Returns true if `messageTypeExtension` has been explicitly set.
  package var hasMessageTypeExtension: Bool {_storage._messageTypeExtension != nil}
  /// Clears the value of `messageTypeExtension`. Subsequent reads from it will return its default value.
  package mutating func clearMessageTypeExtension() {_uniqueStorage()._messageTypeExtension = nil}

  /// When macro call tracking is enabled, the resulting SourceInfo in the
  /// CheckedExpr will contain a collection of expressions representing the
  /// function calls which were replaced by macros.
  ///
  /// Deprecated: Use Feature to enable macro call tracking
  ///  Feature{ name: "cel.feature.macro_call_tracking", enabled: true }
  package var enableMacroCallTracking: Bool {
    get {_storage._enableMacroCallTracking}
    set {_uniqueStorage()._enableMacroCallTracking = newValue}
  }

  package var unknownFields = SwiftProtobuf.UnknownStorage()

  /// Import represents a type name that will be abbreviated by its simple name
  /// making it easier to reference simple type names from packages other than
  /// the expression container.
  /// For ex:
  ///   Import{name: 'google.rpc.Status'}
  /// The above import will ensure that `google.rpc.Status` is available by the
  /// simple name `Status` within CEL expressions.
  package struct Import: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// Qualified type name which will be abbreviated
    package var name: String = String()

    package var unknownFields = SwiftProtobuf.UnknownStorage()

    package init() {}
  }

  /// ContextVariable represents a message type to be made available as a
  /// context variable to the CEL environment.
  package struct ContextVariable: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// Fully qualified type name of the context proto.
    package var typeName: String = String()

    package var unknownFields = SwiftProtobuf.UnknownStorage()

    package init() {}
  }

  package init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

/// Represents a named validator with an optional map-based configuration object.
/// Naming convention followed by validators:
///   <domain>.validator.<validator_name>
/// For ex:
///   `cel.validator.timestamp`
///
/// Note: the map-keys must directly correspond to the internal representation of
/// the original validator, and should only use primitive scalar types as values
/// at this time.
package struct Cel_Expr_Conformance_Validator: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  package var name: String = String()

  /// Additional configurations to be included as part of the validation
  package var config: Dictionary<String,SwiftProtobuf.Google_Protobuf_Value> = [:]

  package var unknownFields = SwiftProtobuf.UnknownStorage()

  package init() {}
}

/// Represents a named boolean feature flag supported by CEL.
/// Naming convention followed by features:
///   <domain>.feature.<feature_name>
/// For ex:
///   `cel.feature.cross_type_numeric_comparisons`
package struct Cel_Expr_Conformance_Feature: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Name of the feature flag.
  package var name: String = String()

  /// State of the feature flab.
  package var enabled: Bool = false

  package var unknownFields = SwiftProtobuf.UnknownStorage()

  package init() {}
}

/// Extension represents a versioned extension library reference to enable in the
/// CEL environment.
package struct Cel_Expr_Conformance_Extension: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Name of the extension library.
  package var name: String = String()

  /// Version of the extension library.
  package var version: String = String()

  package var unknownFields = SwiftProtobuf.UnknownStorage()

  package init() {}
}

/// LibrarySubset indicates a subset of the macros and functions supported by a
/// subsettable library.
package struct Cel_Expr_Conformance_LibrarySubset: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Indicates whether the library has been disabled, typically only
  /// used for default-enabled libraries like stdlib.
  package var disabled: Bool = false

  /// Disables macros for the given library.
  package var disableMacros: Bool = false

  /// Specifies a set of macro function names to include in the subset.
  package var includeMacros: [String] = []

  /// Specifies a set of macro function names to exclude from the subset.
  /// Note: if IncludeMacros is non-empty, then ExcludeFunctions is ignored.
  package var excludeMacros: [String] = []

  /// Specifies a set of functions to include in the subset.
  ///
  /// Note: the overloads specified in the subset need only specify their ID.
  /// Note: if IncludeFunctions is non-empty, then ExcludeFunctions is ignored.
  package var includeFunctions: [Cel_Expr_Decl] = []

  /// Specifies the set of functions to exclude from the subset.
  ///
  /// Note: the overloads specified in the subset need only specify their ID.
  package var excludeFunctions: [Cel_Expr_Decl] = []

  package var unknownFields = SwiftProtobuf.UnknownStorage()

  package init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "cel.expr.conformance"

extension Cel_Expr_Conformance_Environment: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = _protobuf_package + ".Environment"
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}description\0\u{1}container\0\u{1}imports\0\u{1}stdlib\0\u{1}extensions\0\u{3}context_variable\0\u{1}declarations\0\u{1}validators\0\u{1}features\0\u{3}disable_standard_cel_declarations\0\u{3}message_type_extension\0\u{3}enable_macro_call_tracking\0")

  fileprivate class _StorageClass {
    var _name: String = String()
    var _description_p: String = String()
    var _container: String = String()
    var _imports: [Cel_Expr_Conformance_Environment.Import] = []
    var _stdlib: Cel_Expr_Conformance_LibrarySubset? = nil
    var _extensions: [Cel_Expr_Conformance_Extension] = []
    var _contextVariable: Cel_Expr_Conformance_Environment.ContextVariable? = nil
    var _declarations: [Cel_Expr_Decl] = []
    var _validators: [Cel_Expr_Conformance_Validator] = []
    var _features: [Cel_Expr_Conformance_Feature] = []
    var _disableStandardCelDeclarations: Bool = false
    var _messageTypeExtension: SwiftProtobuf.Google_Protobuf_FileDescriptorSet? = nil
    var _enableMacroCallTracking: Bool = false

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _name = source._name
      _description_p = source._description_p
      _container = source._container
      _imports = source._imports
      _stdlib = source._stdlib
      _extensions = source._extensions
      _contextVariable = source._contextVariable
      _declarations = source._declarations
      _validators = source._validators
      _features = source._features
      _disableStandardCelDeclarations = source._disableStandardCelDeclarations
      _messageTypeExtension = source._messageTypeExtension
      _enableMacroCallTracking = source._enableMacroCallTracking
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public var isInitialized: Bool {
    return withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if let v = _storage._messageTypeExtension, !v.isInitialized {return false}
      return true
    }
  }

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularStringField(value: &_storage._name) }()
        case 2: try { try decoder.decodeSingularStringField(value: &_storage._description_p) }()
        case 3: try { try decoder.decodeSingularStringField(value: &_storage._container) }()
        case 4: try { try decoder.decodeRepeatedMessageField(value: &_storage._imports) }()
        case 5: try { try decoder.decodeSingularMessageField(value: &_storage._stdlib) }()
        case 6: try { try decoder.decodeRepeatedMessageField(value: &_storage._extensions) }()
        case 7: try { try decoder.decodeSingularMessageField(value: &_storage._contextVariable) }()
        case 8: try { try decoder.decodeRepeatedMessageField(value: &_storage._declarations) }()
        case 9: try { try decoder.decodeRepeatedMessageField(value: &_storage._validators) }()
        case 10: try { try decoder.decodeRepeatedMessageField(value: &_storage._features) }()
        case 11: try { try decoder.decodeSingularBoolField(value: &_storage._disableStandardCelDeclarations) }()
        case 12: try { try decoder.decodeSingularMessageField(value: &_storage._messageTypeExtension) }()
        case 13: try { try decoder.decodeSingularBoolField(value: &_storage._enableMacroCallTracking) }()
        default: break
        }
      }
    }
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if !_storage._name.isEmpty {
        try visitor.visitSingularStringField(value: _storage._name, fieldNumber: 1)
      }
      if !_storage._description_p.isEmpty {
        try visitor.visitSingularStringField(value: _storage._description_p, fieldNumber: 2)
      }
      if !_storage._container.isEmpty {
        try visitor.visitSingularStringField(value: _storage._container, fieldNumber: 3)
      }
      if !_storage._imports.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._imports, fieldNumber: 4)
      }
      try { if let v = _storage._stdlib {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
      } }()
      if !_storage._extensions.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._extensions, fieldNumber: 6)
      }
      try { if let v = _storage._contextVariable {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
      } }()
      if !_storage._declarations.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._declarations, fieldNumber: 8)
      }
      if !_storage._validators.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._validators, fieldNumber: 9)
      }
      if !_storage._features.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._features, fieldNumber: 10)
      }
      if _storage._disableStandardCelDeclarations != false {
        try visitor.visitSingularBoolField(value: _storage._disableStandardCelDeclarations, fieldNumber: 11)
      }
      try { if let v = _storage._messageTypeExtension {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 12)
      } }()
      if _storage._enableMacroCallTracking != false {
        try visitor.visitSingularBoolField(value: _storage._enableMacroCallTracking, fieldNumber: 13)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Cel_Expr_Conformance_Environment, rhs: Cel_Expr_Conformance_Environment) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._name != rhs_storage._name {return false}
        if _storage._description_p != rhs_storage._description_p {return false}
        if _storage._container != rhs_storage._container {return false}
        if _storage._imports != rhs_storage._imports {return false}
        if _storage._stdlib != rhs_storage._stdlib {return false}
        if _storage._extensions != rhs_storage._extensions {return false}
        if _storage._contextVariable != rhs_storage._contextVariable {return false}
        if _storage._declarations != rhs_storage._declarations {return false}
        if _storage._validators != rhs_storage._validators {return false}
        if _storage._features != rhs_storage._features {return false}
        if _storage._disableStandardCelDeclarations != rhs_storage._disableStandardCelDeclarations {return false}
        if _storage._messageTypeExtension != rhs_storage._messageTypeExtension {return false}
        if _storage._enableMacroCallTracking != rhs_storage._enableMacroCallTracking {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Cel_Expr_Conformance_Environment.Import: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = Cel_Expr_Conformance_Environment.protoMessageName + ".Import"
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0")

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      default: break
      }
    }
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Cel_Expr_Conformance_Environment.Import, rhs: Cel_Expr_Conformance_Environment.Import) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Cel_Expr_Conformance_Environment.ContextVariable: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = Cel_Expr_Conformance_Environment.protoMessageName + ".ContextVariable"
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}type_name\0")

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.typeName) }()
      default: break
      }
    }
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.typeName.isEmpty {
      try visitor.visitSingularStringField(value: self.typeName, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Cel_Expr_Conformance_Environment.ContextVariable, rhs: Cel_Expr_Conformance_Environment.ContextVariable) -> Bool {
    if lhs.typeName != rhs.typeName {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Cel_Expr_Conformance_Validator: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = _protobuf_package + ".Validator"
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}config\0")

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.Google_Protobuf_Value>.self, value: &self.config) }()
      default: break
      }
    }
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if !self.config.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.Google_Protobuf_Value>.self, value: self.config, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Cel_Expr_Conformance_Validator, rhs: Cel_Expr_Conformance_Validator) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.config != rhs.config {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Cel_Expr_Conformance_Feature: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = _protobuf_package + ".Feature"
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}enabled\0")

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.enabled) }()
      default: break
      }
    }
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if self.enabled != false {
      try visitor.visitSingularBoolField(value: self.enabled, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Cel_Expr_Conformance_Feature, rhs: Cel_Expr_Conformance_Feature) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.enabled != rhs.enabled {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Cel_Expr_Conformance_Extension: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = _protobuf_package + ".Extension"
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}version\0")

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.version) }()
      default: break
      }
    }
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if !self.version.isEmpty {
      try visitor.visitSingularStringField(value: self.version, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Cel_Expr_Conformance_Extension, rhs: Cel_Expr_Conformance_Extension) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.version != rhs.version {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Cel_Expr_Conformance_LibrarySubset: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = _protobuf_package + ".LibrarySubset"
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}disabled\0\u{3}disable_macros\0\u{3}include_macros\0\u{3}exclude_macros\0\u{3}include_functions\0\u{3}exclude_functions\0")

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.disabled) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.disableMacros) }()
      case 3: try { try decoder.decodeRepeatedStringField(value: &self.includeMacros) }()
      case 4: try { try decoder.decodeRepeatedStringField(value: &self.excludeMacros) }()
      case 5: try { try decoder.decodeRepeatedMessageField(value: &self.includeFunctions) }()
      case 6: try { try decoder.decodeRepeatedMessageField(value: &self.excludeFunctions) }()
      default: break
      }
    }
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.disabled != false {
      try visitor.visitSingularBoolField(value: self.disabled, fieldNumber: 1)
    }
    if self.disableMacros != false {
      try visitor.visitSingularBoolField(value: self.disableMacros, fieldNumber: 2)
    }
    if !self.includeMacros.isEmpty {
      try visitor.visitRepeatedStringField(value: self.includeMacros, fieldNumber: 3)
    }
    if !self.excludeMacros.isEmpty {
      try visitor.visitRepeatedStringField(value: self.excludeMacros, fieldNumber: 4)
    }
    if !self.includeFunctions.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.includeFunctions, fieldNumber: 5)
    }
    if !self.excludeFunctions.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.excludeFunctions, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Cel_Expr_Conformance_LibrarySubset, rhs: Cel_Expr_Conformance_LibrarySubset) -> Bool {
    if lhs.disabled != rhs.disabled {return false}
    if lhs.disableMacros != rhs.disableMacros {return false}
    if lhs.includeMacros != rhs.includeMacros {return false}
    if lhs.excludeMacros != rhs.excludeMacros {return false}
    if lhs.includeFunctions != rhs.includeFunctions {return false}
    if lhs.excludeFunctions != rhs.excludeFunctions {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
