// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: cel/expr/checked.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Copyright 2023 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// A CEL expression which has been successfully type checked.
package struct Cel_Expr_CheckedExpr: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// A map from expression ids to resolved references.
  ///
  /// The following entries are in this table:
  ///
  /// - An Ident or Select expression is represented here if it resolves to a
  ///   declaration. For instance, if `a.b.c` is represented by
  ///   `select(select(id(a), b), c)`, and `a.b` resolves to a declaration,
  ///   while `c` is a field selection, then the reference is attached to the
  ///   nested select expression (but not to the id or or the outer select).
  ///   In turn, if `a` resolves to a declaration and `b.c` are field selections,
  ///   the reference is attached to the ident expression.
  /// - Every Call expression has an entry here, identifying the function being
  ///   called.
  /// - Every CreateStruct expression for a message has an entry, identifying
  ///   the message.
  package var referenceMap: Dictionary<Int64,Cel_Expr_Reference> = [:]

  /// A map from expression ids to types.
  ///
  /// Every expression node which has a type different than DYN has a mapping
  /// here. If an expression has type DYN, it is omitted from this map to save
  /// space.
  package var typeMap: Dictionary<Int64,Cel_Expr_Type> = [:]

  /// The source info derived from input that generated the parsed `expr` and
  /// any optimizations made during the type-checking pass.
  package var sourceInfo: Cel_Expr_SourceInfo {
    get {_sourceInfo ?? Cel_Expr_SourceInfo()}
    set {_sourceInfo = newValue}
  }
  /// Returns true if `sourceInfo` has been explicitly set.
  package var hasSourceInfo: Bool {self._sourceInfo != nil}
  /// Clears the value of `sourceInfo`. Subsequent reads from it will return its default value.
  package mutating func clearSourceInfo() {self._sourceInfo = nil}

  /// The expr version indicates the major / minor version number of the `expr`
  /// representation.
  ///
  /// The most common reason for a version change will be to indicate to the CEL
  /// runtimes that transformations have been performed on the expr during static
  /// analysis. In some cases, this will save the runtime the work of applying
  /// the same or similar transformations prior to evaluation.
  package var exprVersion: String = String()

  /// The checked expression. Semantically equivalent to the parsed `expr`, but
  /// may have structural differences.
  package var expr: Cel_Expr_Expr {
    get {_expr ?? Cel_Expr_Expr()}
    set {_expr = newValue}
  }
  /// Returns true if `expr` has been explicitly set.
  package var hasExpr: Bool {self._expr != nil}
  /// Clears the value of `expr`. Subsequent reads from it will return its default value.
  package mutating func clearExpr() {self._expr = nil}

  package var unknownFields = SwiftProtobuf.UnknownStorage()

  package init() {}

  fileprivate var _sourceInfo: Cel_Expr_SourceInfo? = nil
  fileprivate var _expr: Cel_Expr_Expr? = nil
}

/// Represents a CEL type.
package struct Cel_Expr_Type: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The kind of type.
  package var typeKind: OneOf_TypeKind? {
    get {return _storage._typeKind}
    set {_uniqueStorage()._typeKind = newValue}
  }

  /// Dynamic type.
  package var dyn: SwiftProtobuf.Google_Protobuf_Empty {
    get {
      if case .dyn(let v)? = _storage._typeKind {return v}
      return SwiftProtobuf.Google_Protobuf_Empty()
    }
    set {_uniqueStorage()._typeKind = .dyn(newValue)}
  }

  /// Null value.
  package var null: SwiftProtobuf.Google_Protobuf_NullValue {
    get {
      if case .null(let v)? = _storage._typeKind {return v}
      return .nullValue
    }
    set {_uniqueStorage()._typeKind = .null(newValue)}
  }

  /// Primitive types: `true`, `1u`, `-2.0`, `'string'`, `b'bytes'`.
  package var primitive: Cel_Expr_Type.PrimitiveType {
    get {
      if case .primitive(let v)? = _storage._typeKind {return v}
      return .unspecified
    }
    set {_uniqueStorage()._typeKind = .primitive(newValue)}
  }

  /// Wrapper of a primitive type, e.g. `google.protobuf.Int64Value`.
  package var wrapper: Cel_Expr_Type.PrimitiveType {
    get {
      if case .wrapper(let v)? = _storage._typeKind {return v}
      return .unspecified
    }
    set {_uniqueStorage()._typeKind = .wrapper(newValue)}
  }

  /// Well-known protobuf type such as `google.protobuf.Timestamp`.
  package var wellKnown: Cel_Expr_Type.WellKnownType {
    get {
      if case .wellKnown(let v)? = _storage._typeKind {return v}
      return .unspecified
    }
    set {_uniqueStorage()._typeKind = .wellKnown(newValue)}
  }

  /// Parameterized list with elements of `list_type`, e.g. `list<timestamp>`.
  package var listType: Cel_Expr_Type.ListType {
    get {
      if case .listType(let v)? = _storage._typeKind {return v}
      return Cel_Expr_Type.ListType()
    }
    set {_uniqueStorage()._typeKind = .listType(newValue)}
  }

  /// Parameterized map with typed keys and values.
  package var mapType: Cel_Expr_Type.MapType {
    get {
      if case .mapType(let v)? = _storage._typeKind {return v}
      return Cel_Expr_Type.MapType()
    }
    set {_uniqueStorage()._typeKind = .mapType(newValue)}
  }

  /// Function type.
  package var function: Cel_Expr_Type.FunctionType {
    get {
      if case .function(let v)? = _storage._typeKind {return v}
      return Cel_Expr_Type.FunctionType()
    }
    set {_uniqueStorage()._typeKind = .function(newValue)}
  }

  /// Protocol buffer message type.
  ///
  /// The `message_type` string specifies the qualified message type name. For
  /// example, `google.type.PhoneNumber`.
  package var messageType: String {
    get {
      if case .messageType(let v)? = _storage._typeKind {return v}
      return String()
    }
    set {_uniqueStorage()._typeKind = .messageType(newValue)}
  }

  /// Type param type.
  ///
  /// The `type_param` string specifies the type parameter name, e.g. `list<E>`
  /// would be a `list_type` whose element type was a `type_param` type
  /// named `E`.
  package var typeParam: String {
    get {
      if case .typeParam(let v)? = _storage._typeKind {return v}
      return String()
    }
    set {_uniqueStorage()._typeKind = .typeParam(newValue)}
  }

  /// Type type.
  ///
  /// The `type` value specifies the target type. e.g. int is type with a
  /// target type of `Primitive.INT64`.
  package var type: Cel_Expr_Type {
    get {
      if case .type(let v)? = _storage._typeKind {return v}
      return Cel_Expr_Type()
    }
    set {_uniqueStorage()._typeKind = .type(newValue)}
  }

  /// Error type.
  ///
  /// During type-checking if an expression is an error, its type is propagated
  /// as the `ERROR` type. This permits the type-checker to discover other
  /// errors present in the expression.
  package var error: SwiftProtobuf.Google_Protobuf_Empty {
    get {
      if case .error(let v)? = _storage._typeKind {return v}
      return SwiftProtobuf.Google_Protobuf_Empty()
    }
    set {_uniqueStorage()._typeKind = .error(newValue)}
  }

  /// Abstract, application defined type.
  ///
  /// An abstract type has no accessible field names, and it can only be
  /// inspected via helper / member functions.
  package var abstractType: Cel_Expr_Type.AbstractType {
    get {
      if case .abstractType(let v)? = _storage._typeKind {return v}
      return Cel_Expr_Type.AbstractType()
    }
    set {_uniqueStorage()._typeKind = .abstractType(newValue)}
  }

  package var unknownFields = SwiftProtobuf.UnknownStorage()

  /// The kind of type.
  package enum OneOf_TypeKind: Equatable, Sendable {
    /// Dynamic type.
    case dyn(SwiftProtobuf.Google_Protobuf_Empty)
    /// Null value.
    case null(SwiftProtobuf.Google_Protobuf_NullValue)
    /// Primitive types: `true`, `1u`, `-2.0`, `'string'`, `b'bytes'`.
    case primitive(Cel_Expr_Type.PrimitiveType)
    /// Wrapper of a primitive type, e.g. `google.protobuf.Int64Value`.
    case wrapper(Cel_Expr_Type.PrimitiveType)
    /// Well-known protobuf type such as `google.protobuf.Timestamp`.
    case wellKnown(Cel_Expr_Type.WellKnownType)
    /// Parameterized list with elements of `list_type`, e.g. `list<timestamp>`.
    case listType(Cel_Expr_Type.ListType)
    /// Parameterized map with typed keys and values.
    case mapType(Cel_Expr_Type.MapType)
    /// Function type.
    case function(Cel_Expr_Type.FunctionType)
    /// Protocol buffer message type.
    ///
    /// The `message_type` string specifies the qualified message type name. For
    /// example, `google.type.PhoneNumber`.
    case messageType(String)
    /// Type param type.
    ///
    /// The `type_param` string specifies the type parameter name, e.g. `list<E>`
    /// would be a `list_type` whose element type was a `type_param` type
    /// named `E`.
    case typeParam(String)
    /// Type type.
    ///
    /// The `type` value specifies the target type. e.g. int is type with a
    /// target type of `Primitive.INT64`.
    case type(Cel_Expr_Type)
    /// Error type.
    ///
    /// During type-checking if an expression is an error, its type is propagated
    /// as the `ERROR` type. This permits the type-checker to discover other
    /// errors present in the expression.
    case error(SwiftProtobuf.Google_Protobuf_Empty)
    /// Abstract, application defined type.
    ///
    /// An abstract type has no accessible field names, and it can only be
    /// inspected via helper / member functions.
    case abstractType(Cel_Expr_Type.AbstractType)

  }

  /// CEL primitive types.
  package enum PrimitiveType: SwiftProtobuf.Enum, Swift.CaseIterable {
    package typealias RawValue = Int

    /// Unspecified type.
    case unspecified // = 0

    /// Boolean type.
    case bool // = 1

    /// Int64 type.
    ///
    /// 32-bit integer values are widened to int64.
    case int64 // = 2

    /// Uint64 type.
    ///
    /// 32-bit unsigned integer values are widened to uint64.
    case uint64 // = 3

    /// Double type.
    ///
    /// 32-bit float values are widened to double values.
    case double // = 4

    /// String type.
    case string // = 5

    /// Bytes type.
    case bytes // = 6
    case UNRECOGNIZED(Int)

    package init() {
      self = .unspecified
    }

    package init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .unspecified
      case 1: self = .bool
      case 2: self = .int64
      case 3: self = .uint64
      case 4: self = .double
      case 5: self = .string
      case 6: self = .bytes
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    package var rawValue: Int {
      switch self {
      case .unspecified: return 0
      case .bool: return 1
      case .int64: return 2
      case .uint64: return 3
      case .double: return 4
      case .string: return 5
      case .bytes: return 6
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    package static let allCases: [Cel_Expr_Type.PrimitiveType] = [
      .unspecified,
      .bool,
      .int64,
      .uint64,
      .double,
      .string,
      .bytes,
    ]

  }

  /// Well-known protobuf types treated with first-class support in CEL.
  package enum WellKnownType: SwiftProtobuf.Enum, Swift.CaseIterable {
    package typealias RawValue = Int

    /// Unspecified type.
    case unspecified // = 0

    /// Well-known protobuf.Any type.
    ///
    /// Any types are a polymorphic message type. During type-checking they are
    /// treated like `DYN` types, but at runtime they are resolved to a specific
    /// message type specified at evaluation time.
    case any // = 1

    /// Well-known protobuf.Timestamp type, internally referenced as `timestamp`.
    case timestamp // = 2

    /// Well-known protobuf.Duration type, internally referenced as `duration`.
    case duration // = 3
    case UNRECOGNIZED(Int)

    package init() {
      self = .unspecified
    }

    package init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .unspecified
      case 1: self = .any
      case 2: self = .timestamp
      case 3: self = .duration
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    package var rawValue: Int {
      switch self {
      case .unspecified: return 0
      case .any: return 1
      case .timestamp: return 2
      case .duration: return 3
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    package static let allCases: [Cel_Expr_Type.WellKnownType] = [
      .unspecified,
      .any,
      .timestamp,
      .duration,
    ]

  }

  /// List type with typed elements, e.g. `list<example.proto.MyMessage>`.
  package struct ListType: @unchecked Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// The element type.
    package var elemType: Cel_Expr_Type {
      get {_storage._elemType ?? Cel_Expr_Type()}
      set {_uniqueStorage()._elemType = newValue}
    }
    /// Returns true if `elemType` has been explicitly set.
    package var hasElemType: Bool {_storage._elemType != nil}
    /// Clears the value of `elemType`. Subsequent reads from it will return its default value.
    package mutating func clearElemType() {_uniqueStorage()._elemType = nil}

    package var unknownFields = SwiftProtobuf.UnknownStorage()

    package init() {}

    fileprivate var _storage = _StorageClass.defaultInstance
  }

  /// Map type with parameterized key and value types, e.g. `map<string, int>`.
  package struct MapType: @unchecked Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// The type of the key.
    package var keyType: Cel_Expr_Type {
      get {_storage._keyType ?? Cel_Expr_Type()}
      set {_uniqueStorage()._keyType = newValue}
    }
    /// Returns true if `keyType` has been explicitly set.
    package var hasKeyType: Bool {_storage._keyType != nil}
    /// Clears the value of `keyType`. Subsequent reads from it will return its default value.
    package mutating func clearKeyType() {_uniqueStorage()._keyType = nil}

    /// The type of the value.
    package var valueType: Cel_Expr_Type {
      get {_storage._valueType ?? Cel_Expr_Type()}
      set {_uniqueStorage()._valueType = newValue}
    }
    /// Returns true if `valueType` has been explicitly set.
    package var hasValueType: Bool {_storage._valueType != nil}
    /// Clears the value of `valueType`. Subsequent reads from it will return its default value.
    package mutating func clearValueType() {_uniqueStorage()._valueType = nil}

    package var unknownFields = SwiftProtobuf.UnknownStorage()

    package init() {}

    fileprivate var _storage = _StorageClass.defaultInstance
  }

  /// Function type with result and arg types.
  package struct FunctionType: @unchecked Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// Result type of the function.
    package var resultType: Cel_Expr_Type {
      get {_storage._resultType ?? Cel_Expr_Type()}
      set {_uniqueStorage()._resultType = newValue}
    }
    /// Returns true if `resultType` has been explicitly set.
    package var hasResultType: Bool {_storage._resultType != nil}
    /// Clears the value of `resultType`. Subsequent reads from it will return its default value.
    package mutating func clearResultType() {_uniqueStorage()._resultType = nil}

    /// Argument types of the function.
    package var argTypes: [Cel_Expr_Type] {
      get {_storage._argTypes}
      set {_uniqueStorage()._argTypes = newValue}
    }

    package var unknownFields = SwiftProtobuf.UnknownStorage()

    package init() {}

    fileprivate var _storage = _StorageClass.defaultInstance
  }

  /// Application defined abstract type.
  package struct AbstractType: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// The fully qualified name of this abstract type.
    package var name: String = String()

    /// Parameter types for this abstract type.
    package var parameterTypes: [Cel_Expr_Type] = []

    package var unknownFields = SwiftProtobuf.UnknownStorage()

    package init() {}
  }

  package init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

/// Represents a declaration of a named value or function.
///
/// A declaration is part of the contract between the expression, the agent
/// evaluating that expression, and the caller requesting evaluation.
package struct Cel_Expr_Decl: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The fully qualified name of the declaration.
  ///
  /// Declarations are organized in containers and this represents the full path
  /// to the declaration in its container, as in `cel.expr.Decl`.
  ///
  /// Declarations used as
  /// [FunctionDecl.Overload][cel.expr.Decl.FunctionDecl.Overload]
  /// parameters may or may not have a name depending on whether the overload is
  /// function declaration or a function definition containing a result
  /// [Expr][cel.expr.Expr].
  package var name: String = String()

  /// Required. The declaration kind.
  package var declKind: Cel_Expr_Decl.OneOf_DeclKind? = nil

  /// Identifier declaration.
  package var ident: Cel_Expr_Decl.IdentDecl {
    get {
      if case .ident(let v)? = declKind {return v}
      return Cel_Expr_Decl.IdentDecl()
    }
    set {declKind = .ident(newValue)}
  }

  /// Function declaration.
  package var function: Cel_Expr_Decl.FunctionDecl {
    get {
      if case .function(let v)? = declKind {return v}
      return Cel_Expr_Decl.FunctionDecl()
    }
    set {declKind = .function(newValue)}
  }

  package var unknownFields = SwiftProtobuf.UnknownStorage()

  /// Required. The declaration kind.
  package enum OneOf_DeclKind: Equatable, Sendable {
    /// Identifier declaration.
    case ident(Cel_Expr_Decl.IdentDecl)
    /// Function declaration.
    case function(Cel_Expr_Decl.FunctionDecl)

  }

  /// Identifier declaration which specifies its type and optional `Expr` value.
  ///
  /// An identifier without a value is a declaration that must be provided at
  /// evaluation time. An identifier with a value should resolve to a constant,
  /// but may be used in conjunction with other identifiers bound at evaluation
  /// time.
  package struct IdentDecl: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// Required. The type of the identifier.
    package var type: Cel_Expr_Type {
      get {_type ?? Cel_Expr_Type()}
      set {_type = newValue}
    }
    /// Returns true if `type` has been explicitly set.
    package var hasType: Bool {self._type != nil}
    /// Clears the value of `type`. Subsequent reads from it will return its default value.
    package mutating func clearType() {self._type = nil}

    /// The constant value of the identifier. If not specified, the identifier
    /// must be supplied at evaluation time.
    package var value: Cel_Expr_Constant {
      get {_value ?? Cel_Expr_Constant()}
      set {_value = newValue}
    }
    /// Returns true if `value` has been explicitly set.
    package var hasValue: Bool {self._value != nil}
    /// Clears the value of `value`. Subsequent reads from it will return its default value.
    package mutating func clearValue() {self._value = nil}

    /// Documentation string for the identifier.
    ///
    /// Provide a brief description of what the variable represents and whether
    /// there are any constraints on the formatting or supported value range.
    ///
    /// Examples:
    ///
    ///    'request.auth.principal' - string which uniquely identifies an
    ///    authenticated principal. For JSON Web Tokens (JWTs), the principal
    ///    is the combination of the issuer ('iss') and subject ('sub') token
    ///    fields concatenated by a forward slash: iss + `/` + sub.
    ///
    ///    'min_cpus' - integer value indicates the minimum number of CPUs
    ///    required for a compute cluster. The 'min_cpus' value must be 
    ///    greater than zero and less than 'max_cpus' or 64 whichever is less.
    package var doc: String = String()

    package var unknownFields = SwiftProtobuf.UnknownStorage()

    package init() {}

    fileprivate var _type: Cel_Expr_Type? = nil
    fileprivate var _value: Cel_Expr_Constant? = nil
  }

  /// Function declaration specifies one or more overloads which indicate the
  /// function's parameter types and return type.
  ///
  /// Functions have no observable side-effects (there may be side-effects like
  /// logging which are not observable from CEL).
  package struct FunctionDecl: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// Required. List of function overloads, must contain at least one overload.
    package var overloads: [Cel_Expr_Decl.FunctionDecl.Overload] = []

    /// Documentation string for the function that indicates the general purpose
    /// of the function and its behavior.
    ///
    /// Documentation strings for the function should be general purpose with
    /// specific examples provided in the overload doc string.
    ///
    /// Examples:
    /// 
    ///     The 'in' operator tests whether an item exists in a collection.
    ///
    ///     The 'substring' function returns a substring of a target string.
    package var doc: String = String()

    package var unknownFields = SwiftProtobuf.UnknownStorage()

    /// An overload indicates a function's parameter types and return type, and
    /// may optionally include a function body described in terms of
    /// [Expr][cel.expr.Expr] values.
    ///
    /// Functions overloads are declared in either a function or method
    /// call-style. For methods, the `params[0]` is the expected type of the
    /// target receiver.
    ///
    /// Overloads must have non-overlapping argument types after erasure of all
    /// parameterized type variables (similar as type erasure in Java).
    package struct Overload: Sendable {
      // SwiftProtobuf.Message conformance is added in an extension below. See the
      // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
      // methods supported on all messages.

      /// Required. Globally unique overload name of the function which reflects
      /// the function name and argument types.
      ///
      /// This will be used by a [Reference][cel.expr.Reference] to
      /// indicate the `overload_id` that was resolved for the function `name`.
      package var overloadID: String = String()

      /// List of function parameter [Type][cel.expr.Type] values.
      ///
      /// Param types are disjoint after generic type parameters have been
      /// replaced with the type `DYN`. Since the `DYN` type is compatible with
      /// any other type, this means that if `A` is a type parameter, the
      /// function types `int<A>` and `int<int>` are not disjoint. Likewise,
      /// `map<string, string>` is not disjoint from `map<K, V>`.
      ///
      /// When the `result_type` of a function is a generic type param, the
      /// type param name also appears as the `type` of on at least one params.
      package var params: [Cel_Expr_Type] = []

      /// The type param names associated with the function declaration.
      ///
      /// For example, `function ex<K,V>(K key, map<K, V> map) : V` would yield
      /// the type params of `K, V`.
      package var typeParams: [String] = []

      /// Required. The result type of the function. For example, the operator
      /// `string.isEmpty()` would have `result_type` of `kind: BOOL`.
      package var resultType: Cel_Expr_Type {
        get {_resultType ?? Cel_Expr_Type()}
        set {_resultType = newValue}
      }
      /// Returns true if `resultType` has been explicitly set.
      package var hasResultType: Bool {self._resultType != nil}
      /// Clears the value of `resultType`. Subsequent reads from it will return its default value.
      package mutating func clearResultType() {self._resultType = nil}

      /// Whether the function is to be used in a method call-style `x.f(...)`
      /// of a function call-style `f(x, ...)`.
      ///
      /// For methods, the first parameter declaration, `params[0]` is the
      /// expected type of the target receiver.
      package var isInstanceFunction: Bool = false

      /// Documentation string for the overload.
      ///
      /// Provide examples of the overload behavior, preferring to use literal
      /// values as input with a comment on the return value.
      ///
      /// Examples:
      ///
      ///    // Determine whether a value of type <V> exists within a list<V>.
      ///    2 in [1, 2, 3] // returns true
      ///
      ///    // Determine whether a key of type <K> exists within a map<K,V>.
      ///    'hello' in {'hi': 'you', 'hello': 'there'}  // returns true
      ///    'help' in {'hi': 'you', 'hello': 'there'}  // returns false
      ///
      ///    // Take the substring of a string starting at a specific character
      ///    // offset (inclusive).
      ///    "tacocat".substring(1) // returns "acocat"
      ///    "tacocat".substring(20) // error
      ///
      ///    // Take the substring of a string starting at a specific character
      ///    // offset (inclusive) and ending at the given offset (exclusive).
      ///    "tacocat".substring(1, 6) // returns "acoca"
      package var doc: String = String()

      package var unknownFields = SwiftProtobuf.UnknownStorage()

      package init() {}

      fileprivate var _resultType: Cel_Expr_Type? = nil
    }

    package init() {}
  }

  package init() {}
}

/// Describes a resolved reference to a declaration.
package struct Cel_Expr_Reference: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The fully qualified name of the declaration.
  package var name: String = String()

  /// For references to functions, this is a list of `Overload.overload_id`
  /// values which match according to typing rules.
  ///
  /// If the list has more than one element, overload resolution among the
  /// presented candidates must happen at runtime because of dynamic types. The
  /// type checker attempts to narrow down this list as much as possible.
  ///
  /// Empty if this is not a reference to a
  /// [Decl.FunctionDecl][cel.expr.Decl.FunctionDecl].
  package var overloadID: [String] = []

  /// For references to constants, this may contain the value of the
  /// constant if known at compile time.
  package var value: Cel_Expr_Constant {
    get {_value ?? Cel_Expr_Constant()}
    set {_value = newValue}
  }
  /// Returns true if `value` has been explicitly set.
  package var hasValue: Bool {self._value != nil}
  /// Clears the value of `value`. Subsequent reads from it will return its default value.
  package mutating func clearValue() {self._value = nil}

  package var unknownFields = SwiftProtobuf.UnknownStorage()

  package init() {}

  fileprivate var _value: Cel_Expr_Constant? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "cel.expr"

extension Cel_Expr_CheckedExpr: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = _protobuf_package + ".CheckedExpr"
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{4}\u{2}reference_map\0\u{3}type_map\0\u{1}expr\0\u{3}source_info\0\u{3}expr_version\0")

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 2: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufInt64,Cel_Expr_Reference>.self, value: &self.referenceMap) }()
      case 3: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufInt64,Cel_Expr_Type>.self, value: &self.typeMap) }()
      case 4: try { try decoder.decodeSingularMessageField(value: &self._expr) }()
      case 5: try { try decoder.decodeSingularMessageField(value: &self._sourceInfo) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.exprVersion) }()
      default: break
      }
    }
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.referenceMap.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufInt64,Cel_Expr_Reference>.self, value: self.referenceMap, fieldNumber: 2)
    }
    if !self.typeMap.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufInt64,Cel_Expr_Type>.self, value: self.typeMap, fieldNumber: 3)
    }
    try { if let v = self._expr {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._sourceInfo {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    } }()
    if !self.exprVersion.isEmpty {
      try visitor.visitSingularStringField(value: self.exprVersion, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Cel_Expr_CheckedExpr, rhs: Cel_Expr_CheckedExpr) -> Bool {
    if lhs.referenceMap != rhs.referenceMap {return false}
    if lhs.typeMap != rhs.typeMap {return false}
    if lhs._sourceInfo != rhs._sourceInfo {return false}
    if lhs.exprVersion != rhs.exprVersion {return false}
    if lhs._expr != rhs._expr {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Cel_Expr_Type: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = _protobuf_package + ".Type"
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}dyn\0\u{1}null\0\u{1}primitive\0\u{1}wrapper\0\u{3}well_known\0\u{3}list_type\0\u{3}map_type\0\u{1}function\0\u{3}message_type\0\u{3}type_param\0\u{1}type\0\u{1}error\0\u{4}\u{2}abstract_type\0")

  fileprivate class _StorageClass {
    var _typeKind: Cel_Expr_Type.OneOf_TypeKind?

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _typeKind = source._typeKind
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try {
          var v: SwiftProtobuf.Google_Protobuf_Empty?
          var hadOneofValue = false
          if let current = _storage._typeKind {
            hadOneofValue = true
            if case .dyn(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._typeKind = .dyn(v)
          }
        }()
        case 2: try {
          var v: SwiftProtobuf.Google_Protobuf_NullValue?
          try decoder.decodeSingularEnumField(value: &v)
          if let v = v {
            if _storage._typeKind != nil {try decoder.handleConflictingOneOf()}
            _storage._typeKind = .null(v)
          }
        }()
        case 3: try {
          var v: Cel_Expr_Type.PrimitiveType?
          try decoder.decodeSingularEnumField(value: &v)
          if let v = v {
            if _storage._typeKind != nil {try decoder.handleConflictingOneOf()}
            _storage._typeKind = .primitive(v)
          }
        }()
        case 4: try {
          var v: Cel_Expr_Type.PrimitiveType?
          try decoder.decodeSingularEnumField(value: &v)
          if let v = v {
            if _storage._typeKind != nil {try decoder.handleConflictingOneOf()}
            _storage._typeKind = .wrapper(v)
          }
        }()
        case 5: try {
          var v: Cel_Expr_Type.WellKnownType?
          try decoder.decodeSingularEnumField(value: &v)
          if let v = v {
            if _storage._typeKind != nil {try decoder.handleConflictingOneOf()}
            _storage._typeKind = .wellKnown(v)
          }
        }()
        case 6: try {
          var v: Cel_Expr_Type.ListType?
          var hadOneofValue = false
          if let current = _storage._typeKind {
            hadOneofValue = true
            if case .listType(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._typeKind = .listType(v)
          }
        }()
        case 7: try {
          var v: Cel_Expr_Type.MapType?
          var hadOneofValue = false
          if let current = _storage._typeKind {
            hadOneofValue = true
            if case .mapType(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._typeKind = .mapType(v)
          }
        }()
        case 8: try {
          var v: Cel_Expr_Type.FunctionType?
          var hadOneofValue = false
          if let current = _storage._typeKind {
            hadOneofValue = true
            if case .function(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._typeKind = .function(v)
          }
        }()
        case 9: try {
          var v: String?
          try decoder.decodeSingularStringField(value: &v)
          if let v = v {
            if _storage._typeKind != nil {try decoder.handleConflictingOneOf()}
            _storage._typeKind = .messageType(v)
          }
        }()
        case 10: try {
          var v: String?
          try decoder.decodeSingularStringField(value: &v)
          if let v = v {
            if _storage._typeKind != nil {try decoder.handleConflictingOneOf()}
            _storage._typeKind = .typeParam(v)
          }
        }()
        case 11: try {
          var v: Cel_Expr_Type?
          var hadOneofValue = false
          if let current = _storage._typeKind {
            hadOneofValue = true
            if case .type(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._typeKind = .type(v)
          }
        }()
        case 12: try {
          var v: SwiftProtobuf.Google_Protobuf_Empty?
          var hadOneofValue = false
          if let current = _storage._typeKind {
            hadOneofValue = true
            if case .error(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._typeKind = .error(v)
          }
        }()
        case 14: try {
          var v: Cel_Expr_Type.AbstractType?
          var hadOneofValue = false
          if let current = _storage._typeKind {
            hadOneofValue = true
            if case .abstractType(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._typeKind = .abstractType(v)
          }
        }()
        default: break
        }
      }
    }
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      switch _storage._typeKind {
      case .dyn?: try {
        guard case .dyn(let v)? = _storage._typeKind else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      }()
      case .null?: try {
        guard case .null(let v)? = _storage._typeKind else { preconditionFailure() }
        try visitor.visitSingularEnumField(value: v, fieldNumber: 2)
      }()
      case .primitive?: try {
        guard case .primitive(let v)? = _storage._typeKind else { preconditionFailure() }
        try visitor.visitSingularEnumField(value: v, fieldNumber: 3)
      }()
      case .wrapper?: try {
        guard case .wrapper(let v)? = _storage._typeKind else { preconditionFailure() }
        try visitor.visitSingularEnumField(value: v, fieldNumber: 4)
      }()
      case .wellKnown?: try {
        guard case .wellKnown(let v)? = _storage._typeKind else { preconditionFailure() }
        try visitor.visitSingularEnumField(value: v, fieldNumber: 5)
      }()
      case .listType?: try {
        guard case .listType(let v)? = _storage._typeKind else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
      }()
      case .mapType?: try {
        guard case .mapType(let v)? = _storage._typeKind else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
      }()
      case .function?: try {
        guard case .function(let v)? = _storage._typeKind else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
      }()
      case .messageType?: try {
        guard case .messageType(let v)? = _storage._typeKind else { preconditionFailure() }
        try visitor.visitSingularStringField(value: v, fieldNumber: 9)
      }()
      case .typeParam?: try {
        guard case .typeParam(let v)? = _storage._typeKind else { preconditionFailure() }
        try visitor.visitSingularStringField(value: v, fieldNumber: 10)
      }()
      case .type?: try {
        guard case .type(let v)? = _storage._typeKind else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 11)
      }()
      case .error?: try {
        guard case .error(let v)? = _storage._typeKind else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 12)
      }()
      case .abstractType?: try {
        guard case .abstractType(let v)? = _storage._typeKind else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 14)
      }()
      case nil: break
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Cel_Expr_Type, rhs: Cel_Expr_Type) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._typeKind != rhs_storage._typeKind {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Cel_Expr_Type.PrimitiveType: SwiftProtobuf._ProtoNameProviding {
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0PRIMITIVE_TYPE_UNSPECIFIED\0\u{1}BOOL\0\u{1}INT64\0\u{1}UINT64\0\u{1}DOUBLE\0\u{1}STRING\0\u{1}BYTES\0")
}

extension Cel_Expr_Type.WellKnownType: SwiftProtobuf._ProtoNameProviding {
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0WELL_KNOWN_TYPE_UNSPECIFIED\0\u{1}ANY\0\u{1}TIMESTAMP\0\u{1}DURATION\0")
}

extension Cel_Expr_Type.ListType: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = Cel_Expr_Type.protoMessageName + ".ListType"
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}elem_type\0")

  fileprivate class _StorageClass {
    var _elemType: Cel_Expr_Type? = nil

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _elemType = source._elemType
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularMessageField(value: &_storage._elemType) }()
        default: break
        }
      }
    }
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      try { if let v = _storage._elemType {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Cel_Expr_Type.ListType, rhs: Cel_Expr_Type.ListType) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._elemType != rhs_storage._elemType {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Cel_Expr_Type.MapType: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = Cel_Expr_Type.protoMessageName + ".MapType"
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}key_type\0\u{3}value_type\0")

  fileprivate class _StorageClass {
    var _keyType: Cel_Expr_Type? = nil
    var _valueType: Cel_Expr_Type? = nil

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _keyType = source._keyType
      _valueType = source._valueType
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularMessageField(value: &_storage._keyType) }()
        case 2: try { try decoder.decodeSingularMessageField(value: &_storage._valueType) }()
        default: break
        }
      }
    }
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      try { if let v = _storage._keyType {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      } }()
      try { if let v = _storage._valueType {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Cel_Expr_Type.MapType, rhs: Cel_Expr_Type.MapType) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._keyType != rhs_storage._keyType {return false}
        if _storage._valueType != rhs_storage._valueType {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Cel_Expr_Type.FunctionType: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = Cel_Expr_Type.protoMessageName + ".FunctionType"
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}result_type\0\u{3}arg_types\0")

  fileprivate class _StorageClass {
    var _resultType: Cel_Expr_Type? = nil
    var _argTypes: [Cel_Expr_Type] = []

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _resultType = source._resultType
      _argTypes = source._argTypes
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularMessageField(value: &_storage._resultType) }()
        case 2: try { try decoder.decodeRepeatedMessageField(value: &_storage._argTypes) }()
        default: break
        }
      }
    }
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      try { if let v = _storage._resultType {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      } }()
      if !_storage._argTypes.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._argTypes, fieldNumber: 2)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Cel_Expr_Type.FunctionType, rhs: Cel_Expr_Type.FunctionType) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._resultType != rhs_storage._resultType {return false}
        if _storage._argTypes != rhs_storage._argTypes {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Cel_Expr_Type.AbstractType: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = Cel_Expr_Type.protoMessageName + ".AbstractType"
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{3}parameter_types\0")

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.parameterTypes) }()
      default: break
      }
    }
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if !self.parameterTypes.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.parameterTypes, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Cel_Expr_Type.AbstractType, rhs: Cel_Expr_Type.AbstractType) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.parameterTypes != rhs.parameterTypes {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Cel_Expr_Decl: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = _protobuf_package + ".Decl"
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}ident\0\u{1}function\0")

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try {
        var v: Cel_Expr_Decl.IdentDecl?
        var hadOneofValue = false
        if let current = self.declKind {
          hadOneofValue = true
          if case .ident(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.declKind = .ident(v)
        }
      }()
      case 3: try {
        var v: Cel_Expr_Decl.FunctionDecl?
        var hadOneofValue = false
        if let current = self.declKind {
          hadOneofValue = true
          if case .function(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.declKind = .function(v)
        }
      }()
      default: break
      }
    }
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    switch self.declKind {
    case .ident?: try {
      guard case .ident(let v)? = self.declKind else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case .function?: try {
      guard case .function(let v)? = self.declKind else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Cel_Expr_Decl, rhs: Cel_Expr_Decl) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.declKind != rhs.declKind {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Cel_Expr_Decl.IdentDecl: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = Cel_Expr_Decl.protoMessageName + ".IdentDecl"
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}type\0\u{1}value\0\u{1}doc\0")

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._type) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._value) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.doc) }()
      default: break
      }
    }
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._type {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._value {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    if !self.doc.isEmpty {
      try visitor.visitSingularStringField(value: self.doc, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Cel_Expr_Decl.IdentDecl, rhs: Cel_Expr_Decl.IdentDecl) -> Bool {
    if lhs._type != rhs._type {return false}
    if lhs._value != rhs._value {return false}
    if lhs.doc != rhs.doc {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Cel_Expr_Decl.FunctionDecl: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = Cel_Expr_Decl.protoMessageName + ".FunctionDecl"
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}overloads\0\u{1}doc\0")

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.overloads) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.doc) }()
      default: break
      }
    }
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.overloads.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.overloads, fieldNumber: 1)
    }
    if !self.doc.isEmpty {
      try visitor.visitSingularStringField(value: self.doc, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Cel_Expr_Decl.FunctionDecl, rhs: Cel_Expr_Decl.FunctionDecl) -> Bool {
    if lhs.overloads != rhs.overloads {return false}
    if lhs.doc != rhs.doc {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Cel_Expr_Decl.FunctionDecl.Overload: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = Cel_Expr_Decl.FunctionDecl.protoMessageName + ".Overload"
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}overload_id\0\u{1}params\0\u{3}type_params\0\u{3}result_type\0\u{3}is_instance_function\0\u{1}doc\0")

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.overloadID) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.params) }()
      case 3: try { try decoder.decodeRepeatedStringField(value: &self.typeParams) }()
      case 4: try { try decoder.decodeSingularMessageField(value: &self._resultType) }()
      case 5: try { try decoder.decodeSingularBoolField(value: &self.isInstanceFunction) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.doc) }()
      default: break
      }
    }
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.overloadID.isEmpty {
      try visitor.visitSingularStringField(value: self.overloadID, fieldNumber: 1)
    }
    if !self.params.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.params, fieldNumber: 2)
    }
    if !self.typeParams.isEmpty {
      try visitor.visitRepeatedStringField(value: self.typeParams, fieldNumber: 3)
    }
    try { if let v = self._resultType {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    } }()
    if self.isInstanceFunction != false {
      try visitor.visitSingularBoolField(value: self.isInstanceFunction, fieldNumber: 5)
    }
    if !self.doc.isEmpty {
      try visitor.visitSingularStringField(value: self.doc, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Cel_Expr_Decl.FunctionDecl.Overload, rhs: Cel_Expr_Decl.FunctionDecl.Overload) -> Bool {
    if lhs.overloadID != rhs.overloadID {return false}
    if lhs.params != rhs.params {return false}
    if lhs.typeParams != rhs.typeParams {return false}
    if lhs._resultType != rhs._resultType {return false}
    if lhs.isInstanceFunction != rhs.isInstanceFunction {return false}
    if lhs.doc != rhs.doc {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Cel_Expr_Reference: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = _protobuf_package + ".Reference"
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{4}\u{2}overload_id\0\u{1}value\0")

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 3: try { try decoder.decodeRepeatedStringField(value: &self.overloadID) }()
      case 4: try { try decoder.decodeSingularMessageField(value: &self._value) }()
      default: break
      }
    }
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if !self.overloadID.isEmpty {
      try visitor.visitRepeatedStringField(value: self.overloadID, fieldNumber: 3)
    }
    try { if let v = self._value {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Cel_Expr_Reference, rhs: Cel_Expr_Reference) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.overloadID != rhs.overloadID {return false}
    if lhs._value != rhs._value {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
