// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by protoc-gen-cel-swift.
// Source: cel/expr/conformance/proto2/test_all_types_extensions.proto

import CEL
import CELProtobuf
import SwiftProtobuf

/// The CEL description of `cel/expr/conformance/proto2/test_all_types_extensions.proto`, for `ProtobufTypes`.
package let Cel_Expr_Conformance_Proto2_TestAllTypesExtensions_CELFile = ProtobufFile(
  path: "cel/expr/conformance/proto2/test_all_types_extensions.proto",
  messageTypes: [
    ProtobufMessageType(Cel_Expr_Conformance_Proto2_Proto2ExtensionScopedMessage.self, fields: _celFields_Cel_Expr_Conformance_Proto2_Proto2ExtensionScopedMessage()),
  ],
  enumTypes: [
  ],
  extensions: [
    ProtobufExtension(ProtobufField<Cel_Expr_Conformance_Proto2_TestAllTypes>.singular("cel.expr.conformance.proto2.int32_ext", number: 1000, \Cel_Expr_Conformance_Proto2_TestAllTypes.Cel_Expr_Conformance_Proto2_int32Ext, .int32, presence: .explicit(\Cel_Expr_Conformance_Proto2_TestAllTypes.hasCel_Expr_Conformance_Proto2_int32Ext))),
    ProtobufExtension(ProtobufField<Cel_Expr_Conformance_Proto2_TestAllTypes>.singular("cel.expr.conformance.proto2.nested_ext", number: 1001, \Cel_Expr_Conformance_Proto2_TestAllTypes.Cel_Expr_Conformance_Proto2_nestedExt, .message, presence: .explicit(\Cel_Expr_Conformance_Proto2_TestAllTypes.hasCel_Expr_Conformance_Proto2_nestedExt))),
    ProtobufExtension(ProtobufField<Cel_Expr_Conformance_Proto2_TestAllTypes>.singular("cel.expr.conformance.proto2.test_all_types_ext", number: 1002, \Cel_Expr_Conformance_Proto2_TestAllTypes.Cel_Expr_Conformance_Proto2_testAllTypesExt, .message, presence: .explicit(\Cel_Expr_Conformance_Proto2_TestAllTypes.hasCel_Expr_Conformance_Proto2_testAllTypesExt))),
    ProtobufExtension(ProtobufField<Cel_Expr_Conformance_Proto2_TestAllTypes>.singular("cel.expr.conformance.proto2.nested_enum_ext", number: 1003, \Cel_Expr_Conformance_Proto2_TestAllTypes.Cel_Expr_Conformance_Proto2_nestedEnumExt, .enumeration("cel.expr.conformance.proto2.TestAllTypes.NestedEnum"), presence: .explicit(\Cel_Expr_Conformance_Proto2_TestAllTypes.hasCel_Expr_Conformance_Proto2_nestedEnumExt))),
    ProtobufExtension(ProtobufField<Cel_Expr_Conformance_Proto2_TestAllTypes>.repeated("cel.expr.conformance.proto2.repeated_test_all_types", number: 1004, \Cel_Expr_Conformance_Proto2_TestAllTypes.Cel_Expr_Conformance_Proto2_repeatedTestAllTypes, .message)),
    ProtobufExtension(ProtobufField<Cel_Expr_Conformance_Proto2_TestAllTypes>.singular("cel.expr.conformance.proto2.Proto2ExtensionScopedMessage.int64_ext", number: 1005, \Cel_Expr_Conformance_Proto2_TestAllTypes.Cel_Expr_Conformance_Proto2_Proto2ExtensionScopedMessage_int64Ext, .int64, presence: .explicit(\Cel_Expr_Conformance_Proto2_TestAllTypes.hasCel_Expr_Conformance_Proto2_Proto2ExtensionScopedMessage_int64Ext))),
    ProtobufExtension(ProtobufField<Cel_Expr_Conformance_Proto2_TestAllTypes>.singular("cel.expr.conformance.proto2.Proto2ExtensionScopedMessage.message_scoped_nested_ext", number: 1006, \Cel_Expr_Conformance_Proto2_TestAllTypes.Cel_Expr_Conformance_Proto2_Proto2ExtensionScopedMessage_messageScopedNestedExt, .message, presence: .explicit(\Cel_Expr_Conformance_Proto2_TestAllTypes.hasCel_Expr_Conformance_Proto2_Proto2ExtensionScopedMessage_messageScopedNestedExt))),
    ProtobufExtension(ProtobufField<Cel_Expr_Conformance_Proto2_TestAllTypes>.singular("cel.expr.conformance.proto2.Proto2ExtensionScopedMessage.nested_enum_ext", number: 1007, \Cel_Expr_Conformance_Proto2_TestAllTypes.Cel_Expr_Conformance_Proto2_Proto2ExtensionScopedMessage_nestedEnumExt, .enumeration("cel.expr.conformance.proto2.TestAllTypes.NestedEnum"), presence: .explicit(\Cel_Expr_Conformance_Proto2_TestAllTypes.hasCel_Expr_Conformance_Proto2_Proto2ExtensionScopedMessage_nestedEnumExt))),
    ProtobufExtension(ProtobufField<Cel_Expr_Conformance_Proto2_TestAllTypes>.repeated("cel.expr.conformance.proto2.Proto2ExtensionScopedMessage.message_scoped_repeated_test_all_types", number: 1008, \Cel_Expr_Conformance_Proto2_TestAllTypes.Cel_Expr_Conformance_Proto2_Proto2ExtensionScopedMessage_messageScopedRepeatedTestAllTypes, .message)),
  ],
  extensionMap: Cel_Expr_Conformance_Proto2_TestAllTypesExtensions_Extensions,
  dependencies: [Cel_Expr_Conformance_Proto2_TestAllTypes_CELFile]
)

fileprivate func _celFields_Cel_Expr_Conformance_Proto2_Proto2ExtensionScopedMessage() -> [ProtobufField<Cel_Expr_Conformance_Proto2_Proto2ExtensionScopedMessage>] {
  []
}
