// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: cel/expr/syntax.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Copyright 2023 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// An expression together with source information as returned by the parser.
package struct Cel_Expr_ParsedExpr: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The parsed expression.
  package var expr: Cel_Expr_Expr {
    get {_expr ?? Cel_Expr_Expr()}
    set {_expr = newValue}
  }
  /// Returns true if `expr` has been explicitly set.
  package var hasExpr: Bool {self._expr != nil}
  /// Clears the value of `expr`. Subsequent reads from it will return its default value.
  package mutating func clearExpr() {self._expr = nil}

  /// The source info derived from input that generated the parsed `expr`.
  package var sourceInfo: Cel_Expr_SourceInfo {
    get {_sourceInfo ?? Cel_Expr_SourceInfo()}
    set {_sourceInfo = newValue}
  }
  /// Returns true if `sourceInfo` has been explicitly set.
  package var hasSourceInfo: Bool {self._sourceInfo != nil}
  /// Clears the value of `sourceInfo`. Subsequent reads from it will return its default value.
  package mutating func clearSourceInfo() {self._sourceInfo = nil}

  package var unknownFields = SwiftProtobuf.UnknownStorage()

  package init() {}

  fileprivate var _expr: Cel_Expr_Expr? = nil
  fileprivate var _sourceInfo: Cel_Expr_SourceInfo? = nil
}

/// An abstract representation of a common expression.
///
/// Expressions are abstractly represented as a collection of identifiers,
/// select statements, function calls, literals, and comprehensions. All
/// operators with the exception of the '.' operator are modelled as function
/// calls. This makes it easy to represent new operators into the existing AST.
///
/// All references within expressions must resolve to a
/// [Decl][cel.expr.Decl] provided at type-check for an expression to be
/// valid. A reference may either be a bare identifier `name` or a qualified
/// identifier `google.api.name`. References may either refer to a value or a
/// function declaration.
///
/// For example, the expression `google.api.name.startsWith('expr')` references
/// the declaration `google.api.name` within a
/// [Expr.Select][cel.expr.Expr.Select] expression, and the function
/// declaration `startsWith`.
package struct Cel_Expr_Expr: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Required. An id assigned to this node by the parser which is unique in a
  /// given expression tree. This is used to associate type information and other
  /// attributes to a node in the parse tree.
  package var id: Int64 {
    get {_storage._id}
    set {_uniqueStorage()._id = newValue}
  }

  /// Required. Variants of expressions.
  package var exprKind: OneOf_ExprKind? {
    get {return _storage._exprKind}
    set {_uniqueStorage()._exprKind = newValue}
  }

  /// A constant expression.
  package var constExpr: Cel_Expr_Constant {
    get {
      if case .constExpr(let v)? = _storage._exprKind {return v}
      return Cel_Expr_Constant()
    }
    set {_uniqueStorage()._exprKind = .constExpr(newValue)}
  }

  /// An identifier expression.
  package var identExpr: Cel_Expr_Expr.Ident {
    get {
      if case .identExpr(let v)? = _storage._exprKind {return v}
      return Cel_Expr_Expr.Ident()
    }
    set {_uniqueStorage()._exprKind = .identExpr(newValue)}
  }

  /// A field selection expression, e.g. `request.auth`.
  package var selectExpr: Cel_Expr_Expr.Select {
    get {
      if case .selectExpr(let v)? = _storage._exprKind {return v}
      return Cel_Expr_Expr.Select()
    }
    set {_uniqueStorage()._exprKind = .selectExpr(newValue)}
  }

  /// A call expression, including calls to predefined functions and operators.
  package var callExpr: Cel_Expr_Expr.Call {
    get {
      if case .callExpr(let v)? = _storage._exprKind {return v}
      return Cel_Expr_Expr.Call()
    }
    set {_uniqueStorage()._exprKind = .callExpr(newValue)}
  }

  /// A list creation expression.
  package var listExpr: Cel_Expr_Expr.CreateList {
    get {
      if case .listExpr(let v)? = _storage._exprKind {return v}
      return Cel_Expr_Expr.CreateList()
    }
    set {_uniqueStorage()._exprKind = .listExpr(newValue)}
  }

  /// A map or message creation expression.
  package var structExpr: Cel_Expr_Expr.CreateStruct {
    get {
      if case .structExpr(let v)? = _storage._exprKind {return v}
      return Cel_Expr_Expr.CreateStruct()
    }
    set {_uniqueStorage()._exprKind = .structExpr(newValue)}
  }

  /// A comprehension expression.
  package var comprehensionExpr: Cel_Expr_Expr.Comprehension {
    get {
      if case .comprehensionExpr(let v)? = _storage._exprKind {return v}
      return Cel_Expr_Expr.Comprehension()
    }
    set {_uniqueStorage()._exprKind = .comprehensionExpr(newValue)}
  }

  package var unknownFields = SwiftProtobuf.UnknownStorage()

  /// Required. Variants of expressions.
  package enum OneOf_ExprKind: Equatable, Sendable {
    /// A constant expression.
    case constExpr(Cel_Expr_Constant)
    /// An identifier expression.
    case identExpr(Cel_Expr_Expr.Ident)
    /// A field selection expression, e.g. `request.auth`.
    case selectExpr(Cel_Expr_Expr.Select)
    /// A call expression, including calls to predefined functions and operators.
    case callExpr(Cel_Expr_Expr.Call)
    /// A list creation expression.
    case listExpr(Cel_Expr_Expr.CreateList)
    /// A map or message creation expression.
    case structExpr(Cel_Expr_Expr.CreateStruct)
    /// A comprehension expression.
    case comprehensionExpr(Cel_Expr_Expr.Comprehension)

  }

  /// An identifier expression. e.g. `request`.
  package struct Ident: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// Required. Holds a single, unqualified identifier, possibly preceded by a
    /// '.'.
    ///
    /// Qualified names are represented by the
    /// [Expr.Select][cel.expr.Expr.Select] expression.
    package var name: String = String()

    package var unknownFields = SwiftProtobuf.UnknownStorage()

    package init() {}
  }

  /// A field selection expression. e.g. `request.auth`.
  package struct Select: @unchecked Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// Required. The target of the selection expression.
    ///
    /// For example, in the select expression `request.auth`, the `request`
    /// portion of the expression is the `operand`.
    package var operand: Cel_Expr_Expr {
      get {_storage._operand ?? Cel_Expr_Expr()}
      set {_uniqueStorage()._operand = newValue}
    }
    /// Returns true if `operand` has been explicitly set.
    package var hasOperand: Bool {_storage._operand != nil}
    /// Clears the value of `operand`. Subsequent reads from it will return its default value.
    package mutating func clearOperand() {_uniqueStorage()._operand = nil}

    /// Required. The name of the field to select.
    ///
    /// For example, in the select expression `request.auth`, the `auth` portion
    /// of the expression would be the `field`.
    package var field: String {
      get {_storage._field}
      set {_uniqueStorage()._field = newValue}
    }

    /// Whether the select is to be interpreted as a field presence test.
    ///
    /// This results from the macro `has(request.auth)`.
    package var testOnly: Bool {
      get {_storage._testOnly}
      set {_uniqueStorage()._testOnly = newValue}
    }

    package var unknownFields = SwiftProtobuf.UnknownStorage()

    package init() {}

    fileprivate var _storage = _StorageClass.defaultInstance
  }

  /// A call expression, including calls to predefined functions and operators.
  ///
  /// For example, `value == 10`, `size(map_value)`.
  package struct Call: @unchecked Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// The target of an method call-style expression. For example, `x` in
    /// `x.f()`.
    package var target: Cel_Expr_Expr {
      get {_storage._target ?? Cel_Expr_Expr()}
      set {_uniqueStorage()._target = newValue}
    }
    /// Returns true if `target` has been explicitly set.
    package var hasTarget: Bool {_storage._target != nil}
    /// Clears the value of `target`. Subsequent reads from it will return its default value.
    package mutating func clearTarget() {_uniqueStorage()._target = nil}

    /// Required. The name of the function or method being called.
    package var function: String {
      get {_storage._function}
      set {_uniqueStorage()._function = newValue}
    }

    /// The arguments.
    package var args: [Cel_Expr_Expr] {
      get {_storage._args}
      set {_uniqueStorage()._args = newValue}
    }

    package var unknownFields = SwiftProtobuf.UnknownStorage()

    package init() {}

    fileprivate var _storage = _StorageClass.defaultInstance
  }

  /// A list creation expression.
  ///
  /// Lists may either be homogenous, e.g. `[1, 2, 3]`, or heterogeneous, e.g.
  /// `dyn([1, 'hello', 2.0])`
  package struct CreateList: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// The elements part of the list.
    package var elements: [Cel_Expr_Expr] = []

    /// The indices within the elements list which are marked as optional
    /// elements.
    ///
    /// When an optional-typed value is present, the value it contains
    /// is included in the list. If the optional-typed value is absent, the list
    /// element is omitted from the CreateList result.
    package var optionalIndices: [Int32] = []

    package var unknownFields = SwiftProtobuf.UnknownStorage()

    package init() {}
  }

  /// A map or message creation expression.
  ///
  /// Maps are constructed as `{'key_name': 'value'}`. Message construction is
  /// similar, but prefixed with a type name and composed of field ids:
  /// `types.MyType{field_id: 'value'}`.
  package struct CreateStruct: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// The type name of the message to be created, empty when creating map
    /// literals.
    package var messageName: String = String()

    /// The entries in the creation expression.
    package var entries: [Cel_Expr_Expr.CreateStruct.Entry] = []

    package var unknownFields = SwiftProtobuf.UnknownStorage()

    /// Represents an entry.
    package struct Entry: Sendable {
      // SwiftProtobuf.Message conformance is added in an extension below. See the
      // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
      // methods supported on all messages.

      /// Required. An id assigned to this node by the parser which is unique
      /// in a given expression tree. This is used to associate type
      /// information and other attributes to the node.
      package var id: Int64 = 0

      /// The `Entry` key kinds.
      package var keyKind: Cel_Expr_Expr.CreateStruct.Entry.OneOf_KeyKind? = nil

      /// The field key for a message creator statement.
      package var fieldKey: String {
        get {
          if case .fieldKey(let v)? = keyKind {return v}
          return String()
        }
        set {keyKind = .fieldKey(newValue)}
      }

      /// The key expression for a map creation statement.
      package var mapKey: Cel_Expr_Expr {
        get {
          if case .mapKey(let v)? = keyKind {return v}
          return Cel_Expr_Expr()
        }
        set {keyKind = .mapKey(newValue)}
      }

      /// Required. The value assigned to the key.
      ///
      /// If the optional_entry field is true, the expression must resolve to an
      /// optional-typed value. If the optional value is present, the key will be
      /// set; however, if the optional value is absent, the key will be unset.
      package var value: Cel_Expr_Expr {
        get {_value ?? Cel_Expr_Expr()}
        set {_value = newValue}
      }
      /// Returns true if `value` has been explicitly set.
      package var hasValue: Bool {self._value != nil}
      /// Clears the value of `value`. Subsequent reads from it will return its default value.
      package mutating func clearValue() {self._value = nil}

      /// Whether the key-value pair is optional.
      package var optionalEntry: Bool = false

      package var unknownFields = SwiftProtobuf.UnknownStorage()

      /// The `Entry` key kinds.
      package enum OneOf_KeyKind: Equatable, Sendable {
        /// The field key for a message creator statement.
        case fieldKey(String)
        /// The key expression for a map creation statement.
        case mapKey(Cel_Expr_Expr)

      }

      package init() {}

      fileprivate var _value: Cel_Expr_Expr? = nil
    }

    package init() {}
  }

  /// A comprehension expression applied to a list or map.
  ///
  /// Comprehensions are not part of the core syntax, but enabled with macros.
  /// A macro matches a specific call signature within a parsed AST and replaces
  /// the call with an alternate AST block. Macro expansion happens at parse
  /// time.
  ///
  /// The following macros are supported within CEL:
  ///
  /// Aggregate type macros may be applied to all elements in a list or all keys
  /// in a map:
  ///
  /// *  `all`, `exists`, `exists_one` -  test a predicate expression against
  ///    the inputs and return `true` if the predicate is satisfied for all,
  ///    any, or only one value `list.all(x, x < 10)`.
  /// *  `filter` - test a predicate expression against the inputs and return
  ///    the subset of elements which satisfy the predicate:
  ///    `payments.filter(p, p > 1000)`.
  /// *  `map` - apply an expression to all elements in the input and return the
  ///    output aggregate type: `[1, 2, 3].map(i, i * i)`.
  ///
  /// The `has(m.x)` macro tests whether the property `x` is present in struct
  /// `m`. The semantics of this macro depend on the type of `m`. For proto2
  /// messages `has(m.x)` is defined as 'defined, but not set`. For proto3, the
  /// macro tests whether the property is set to its default. For map and struct
  /// types, the macro tests whether the property `x` is defined on `m`.
  ///
  /// Comprehensions for the standard environment macros evaluation can be best
  /// visualized as the following pseudocode:
  ///
  /// ```
  /// let `accu_var` = `accu_init`
  /// for (let `iter_var` in `iter_range`) {
  ///   if (!`loop_condition`) {
  ///     break
  ///   }
  ///   `accu_var` = `loop_step`
  /// }
  /// return `result`
  /// ```
  ///
  /// Comprehensions for the optional V2 macros which support map-to-map
  /// translation differ slightly from the standard environment macros in that
  /// they expose both the key or index in addition to the value for each list
  /// or map entry:
  ///
  /// ```
  /// let `accu_var` = `accu_init`
  /// for (let `iter_var`, `iter_var2` in `iter_range`) {
  ///   if (!`loop_condition`) {
  ///     break
  ///   }
  ///   `accu_var` = `loop_step`
  /// }
  /// return `result`
  /// ```
  package struct Comprehension: @unchecked Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// The name of the first iteration variable.
    /// For the single iteration variable macros, when iter_range is a list, this
    /// variable is the list element and when the iter_range is a map, this
    /// variable is the map key.
    package var iterVar: String {
      get {_storage._iterVar}
      set {_uniqueStorage()._iterVar = newValue}
    }

    /// The name of the second iteration variable, empty if not set.
    /// This field is only set for comprehension v2 macros.
    package var iterVar2: String {
      get {_storage._iterVar2}
      set {_uniqueStorage()._iterVar2 = newValue}
    }

    /// The range over which the comprehension iterates.
    package var iterRange: Cel_Expr_Expr {
      get {_storage._iterRange ?? Cel_Expr_Expr()}
      set {_uniqueStorage()._iterRange = newValue}
    }
    /// Returns true if `iterRange` has been explicitly set.
    package var hasIterRange: Bool {_storage._iterRange != nil}
    /// Clears the value of `iterRange`. Subsequent reads from it will return its default value.
    package mutating func clearIterRange() {_uniqueStorage()._iterRange = nil}

    /// The name of the variable used for accumulation of the result.
    package var accuVar: String {
      get {_storage._accuVar}
      set {_uniqueStorage()._accuVar = newValue}
    }

    /// The initial value of the accumulator.
    package var accuInit: Cel_Expr_Expr {
      get {_storage._accuInit ?? Cel_Expr_Expr()}
      set {_uniqueStorage()._accuInit = newValue}
    }
    /// Returns true if `accuInit` has been explicitly set.
    package var hasAccuInit: Bool {_storage._accuInit != nil}
    /// Clears the value of `accuInit`. Subsequent reads from it will return its default value.
    package mutating func clearAccuInit() {_uniqueStorage()._accuInit = nil}

    /// An expression which can contain iter_var, iter_var2, and accu_var.
    ///
    /// Returns false when the result has been computed and may be used as
    /// a hint to short-circuit the remainder of the comprehension.
    package var loopCondition: Cel_Expr_Expr {
      get {_storage._loopCondition ?? Cel_Expr_Expr()}
      set {_uniqueStorage()._loopCondition = newValue}
    }
    /// Returns true if `loopCondition` has been explicitly set.
    package var hasLoopCondition: Bool {_storage._loopCondition != nil}
    /// Clears the value of `loopCondition`. Subsequent reads from it will return its default value.
    package mutating func clearLoopCondition() {_uniqueStorage()._loopCondition = nil}

    /// An expression which can contain iter_var, iter_var2, and accu_var.
    ///
    /// Computes the next value of accu_var.
    package var loopStep: Cel_Expr_Expr {
      get {_storage._loopStep ?? Cel_Expr_Expr()}
      set {_uniqueStorage()._loopStep = newValue}
    }
    /// Returns true if `loopStep` has been explicitly set.
    package var hasLoopStep: Bool {_storage._loopStep != nil}
    /// Clears the value of `loopStep`. Subsequent reads from it will return its default value.
    package mutating func clearLoopStep() {_uniqueStorage()._loopStep = nil}

    /// An expression which can contain accu_var.
    ///
    /// Computes the result.
    package var result: Cel_Expr_Expr {
      get {_storage._result ?? Cel_Expr_Expr()}
      set {_uniqueStorage()._result = newValue}
    }
    /// Returns true if `result` has been explicitly set.
    package var hasResult: Bool {_storage._result != nil}
    /// Clears the value of `result`. Subsequent reads from it will return its default value.
    package mutating func clearResult() {_uniqueStorage()._result = nil}

    package var unknownFields = SwiftProtobuf.UnknownStorage()

    package init() {}

    fileprivate var _storage = _StorageClass.defaultInstance
  }

  package init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

/// Represents a primitive literal.
///
/// Named 'Constant' here for backwards compatibility.
///
/// This is similar as the primitives supported in the well-known type
/// `google.protobuf.Value`, but richer so it can represent CEL's full range of
/// primitives.
///
/// Lists and structs are not included as constants as these aggregate types may
/// contain [Expr][cel.expr.Expr] elements which require evaluation and
/// are thus not constant.
///
/// Examples of constants include: `"hello"`, `b'bytes'`, `1u`, `4.2`, `-2`,
/// `true`, `null`.
package struct Cel_Expr_Constant: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Required. The valid constant kinds.
  package var constantKind: Cel_Expr_Constant.OneOf_ConstantKind? = nil

  /// null value.
  package var nullValue: SwiftProtobuf.Google_Protobuf_NullValue {
    get {
      if case .nullValue(let v)? = constantKind {return v}
      return .nullValue
    }
    set {constantKind = .nullValue(newValue)}
  }

  /// boolean value.
  package var boolValue: Bool {
    get {
      if case .boolValue(let v)? = constantKind {return v}
      return false
    }
    set {constantKind = .boolValue(newValue)}
  }

  /// int64 value.
  package var int64Value: Int64 {
    get {
      if case .int64Value(let v)? = constantKind {return v}
      return 0
    }
    set {constantKind = .int64Value(newValue)}
  }

  /// uint64 value.
  package var uint64Value: UInt64 {
    get {
      if case .uint64Value(let v)? = constantKind {return v}
      return 0
    }
    set {constantKind = .uint64Value(newValue)}
  }

  /// double value.
  package var doubleValue: Double {
    get {
      if case .doubleValue(let v)? = constantKind {return v}
      return 0
    }
    set {constantKind = .doubleValue(newValue)}
  }

  /// string value.
  package var stringValue: String {
    get {
      if case .stringValue(let v)? = constantKind {return v}
      return String()
    }
    set {constantKind = .stringValue(newValue)}
  }

  /// bytes value.
  package var bytesValue: Data {
    get {
      if case .bytesValue(let v)? = constantKind {return v}
      return Data()
    }
    set {constantKind = .bytesValue(newValue)}
  }

  /// protobuf.Duration value.
  ///
  /// Deprecated: duration is no longer considered a builtin cel type.
  ///
  /// NOTE: This field was marked as deprecated in the .proto file.
  package var durationValue: SwiftProtobuf.Google_Protobuf_Duration {
    get {
      if case .durationValue(let v)? = constantKind {return v}
      return SwiftProtobuf.Google_Protobuf_Duration()
    }
    set {constantKind = .durationValue(newValue)}
  }

  /// protobuf.Timestamp value.
  ///
  /// Deprecated: timestamp is no longer considered a builtin cel type.
  ///
  /// NOTE: This field was marked as deprecated in the .proto file.
  package var timestampValue: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {
      if case .timestampValue(let v)? = constantKind {return v}
      return SwiftProtobuf.Google_Protobuf_Timestamp()
    }
    set {constantKind = .timestampValue(newValue)}
  }

  package var unknownFields = SwiftProtobuf.UnknownStorage()

  /// Required. The valid constant kinds.
  package enum OneOf_ConstantKind: Equatable, Sendable {
    /// null value.
    case nullValue(SwiftProtobuf.Google_Protobuf_NullValue)
    /// boolean value.
    case boolValue(Bool)
    /// int64 value.
    case int64Value(Int64)
    /// uint64 value.
    case uint64Value(UInt64)
    /// double value.
    case doubleValue(Double)
    /// string value.
    case stringValue(String)
    /// bytes value.
    case bytesValue(Data)
    /// protobuf.Duration value.
    ///
    /// Deprecated: duration is no longer considered a builtin cel type.
    ///
    /// NOTE: This field was marked as deprecated in the .proto file.
    case durationValue(SwiftProtobuf.Google_Protobuf_Duration)
    /// protobuf.Timestamp value.
    ///
    /// Deprecated: timestamp is no longer considered a builtin cel type.
    ///
    /// NOTE: This field was marked as deprecated in the .proto file.
    case timestampValue(SwiftProtobuf.Google_Protobuf_Timestamp)

  }

  package init() {}
}

/// Source information collected at parse time.
package struct Cel_Expr_SourceInfo: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The syntax version of the source, e.g. `cel1`.
  package var syntaxVersion: String = String()

  /// The location name. All position information attached to an expression is
  /// relative to this location.
  ///
  /// The location could be a file, UI element, or similar. For example,
  /// `acme/app/AnvilPolicy.cel`.
  package var location: String = String()

  /// Monotonically increasing list of code point offsets where newlines
  /// `\n` appear.
  ///
  /// The line number of a given position is the index `i` where for a given
  /// `id` the `line_offsets[i] < id_positions[id] < line_offsets[i+1]`. The
  /// column may be derived from `id_positions[id] - line_offsets[i]`.
  package var lineOffsets: [Int32] = []

  /// A map from the parse node id (e.g. `Expr.id`) to the code point offset
  /// within the source.
  package var positions: Dictionary<Int64,Int32> = [:]

  /// A map from the parse node id where a macro replacement was made to the
  /// call `Expr` that resulted in a macro expansion.
  ///
  /// For example, `has(value.field)` is a function call that is replaced by a
  /// `test_only` field selection in the AST. Likewise, the call
  /// `list.exists(e, e > 10)` translates to a comprehension expression. The key
  /// in the map corresponds to the expression id of the expanded macro, and the
  /// value is the call `Expr` that was replaced.
  package var macroCalls: Dictionary<Int64,Cel_Expr_Expr> = [:]

  /// A list of tags for extensions that were used while parsing or type checking
  /// the source expression. For example, optimizations that require special
  /// runtime support may be specified.
  ///
  /// These are used to check feature support between components in separate
  /// implementations. This can be used to either skip redundant work or
  /// report an error if the extension is unsupported.
  package var extensions: [Cel_Expr_SourceInfo.Extension] = []

  package var unknownFields = SwiftProtobuf.UnknownStorage()

  /// An extension that was requested for the source expression.
  package struct Extension: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// Identifier for the extension. Example: constant_folding
    package var id: String = String()

    /// If set, the listed components must understand the extension for the
    /// expression to evaluate correctly.
    ///
    /// This field has set semantics, repeated values should be deduplicated.
    package var affectedComponents: [Cel_Expr_SourceInfo.Extension.Component] = []

    /// Version info. May be skipped if it isn't meaningful for the extension.
    /// (for example constant_folding might always be v0.0).
    package var version: Cel_Expr_SourceInfo.Extension.Version {
      get {_version ?? Cel_Expr_SourceInfo.Extension.Version()}
      set {_version = newValue}
    }
    /// Returns true if `version` has been explicitly set.
    package var hasVersion: Bool {self._version != nil}
    /// Clears the value of `version`. Subsequent reads from it will return its default value.
    package mutating func clearVersion() {self._version = nil}

    package var unknownFields = SwiftProtobuf.UnknownStorage()

    /// CEL component specifier.
    package enum Component: SwiftProtobuf.Enum, Swift.CaseIterable {
      package typealias RawValue = Int

      /// Unspecified, default.
      case unspecified // = 0

      /// Parser. Converts a CEL string to an AST.
      case parser // = 1

      /// Type checker. Checks that references in an AST are defined and types
      /// agree.
      case typeChecker // = 2

      /// Runtime. Evaluates a parsed and optionally checked CEL AST against a
      /// context.
      case runtime // = 3
      case UNRECOGNIZED(Int)

      package init() {
        self = .unspecified
      }

      package init?(rawValue: Int) {
        switch rawValue {
        case 0: self = .unspecified
        case 1: self = .parser
        case 2: self = .typeChecker
        case 3: self = .runtime
        default: self = .UNRECOGNIZED(rawValue)
        }
      }

      package var rawValue: Int {
        switch self {
        case .unspecified: return 0
        case .parser: return 1
        case .typeChecker: return 2
        case .runtime: return 3
        case .UNRECOGNIZED(let i): return i
        }
      }

      // The compiler won't synthesize support with the UNRECOGNIZED case.
      package static let allCases: [Cel_Expr_SourceInfo.Extension.Component] = [
        .unspecified,
        .parser,
        .typeChecker,
        .runtime,
      ]

    }

    /// Version
    package struct Version: Sendable {
      // SwiftProtobuf.Message conformance is added in an extension below. See the
      // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
      // methods supported on all messages.

      /// Major version changes indicate different required support level from
      /// the required components.
      package var major: Int64 = 0

      /// Minor version changes must not change the observed behavior from
      /// existing implementations, but may be provided informationally.
      package var minor: Int64 = 0

      package var unknownFields = SwiftProtobuf.UnknownStorage()

      package init() {}
    }

    package init() {}

    fileprivate var _version: Cel_Expr_SourceInfo.Extension.Version? = nil
  }

  package init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "cel.expr"

extension Cel_Expr_ParsedExpr: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = _protobuf_package + ".ParsedExpr"
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\u{2}expr\0\u{3}source_info\0")

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 2: try { try decoder.decodeSingularMessageField(value: &self._expr) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._sourceInfo) }()
      default: break
      }
    }
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._expr {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._sourceInfo {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Cel_Expr_ParsedExpr, rhs: Cel_Expr_ParsedExpr) -> Bool {
    if lhs._expr != rhs._expr {return false}
    if lhs._sourceInfo != rhs._sourceInfo {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Cel_Expr_Expr: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = _protobuf_package + ".Expr"
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\u{2}id\0\u{3}const_expr\0\u{3}ident_expr\0\u{3}select_expr\0\u{3}call_expr\0\u{3}list_expr\0\u{3}struct_expr\0\u{3}comprehension_expr\0")

  fileprivate class _StorageClass {
    var _id: Int64 = 0
    var _exprKind: Cel_Expr_Expr.OneOf_ExprKind?

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _id = source._id
      _exprKind = source._exprKind
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 2: try { try decoder.decodeSingularInt64Field(value: &_storage._id) }()
        case 3: try {
          var v: Cel_Expr_Constant?
          var hadOneofValue = false
          if let current = _storage._exprKind {
            hadOneofValue = true
            if case .constExpr(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._exprKind = .constExpr(v)
          }
        }()
        case 4: try {
          var v: Cel_Expr_Expr.Ident?
          var hadOneofValue = false
          if let current = _storage._exprKind {
            hadOneofValue = true
            if case .identExpr(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._exprKind = .identExpr(v)
          }
        }()
        case 5: try {
          var v: Cel_Expr_Expr.Select?
          var hadOneofValue = false
          if let current = _storage._exprKind {
            hadOneofValue = true
            if case .selectExpr(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._exprKind = .selectExpr(v)
          }
        }()
        case 6: try {
          var v: Cel_Expr_Expr.Call?
          var hadOneofValue = false
          if let current = _storage._exprKind {
            hadOneofValue = true
            if case .callExpr(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._exprKind = .callExpr(v)
          }
        }()
        case 7: try {
          var v: Cel_Expr_Expr.CreateList?
          var hadOneofValue = false
          if let current = _storage._exprKind {
            hadOneofValue = true
            if case .listExpr(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._exprKind = .listExpr(v)
          }
        }()
        case 8: try {
          var v: Cel_Expr_Expr.CreateStruct?
          var hadOneofValue = false
          if let current = _storage._exprKind {
            hadOneofValue = true
            if case .structExpr(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._exprKind = .structExpr(v)
          }
        }()
        case 9: try {
          var v: Cel_Expr_Expr.Comprehension?
          var hadOneofValue = false
          if let current = _storage._exprKind {
            hadOneofValue = true
            if case .comprehensionExpr(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._exprKind = .comprehensionExpr(v)
          }
        }()
        default: break
        }
      }
    }
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if _storage._id != 0 {
        try visitor.visitSingularInt64Field(value: _storage._id, fieldNumber: 2)
      }
      switch _storage._exprKind {
      case .constExpr?: try {
        guard case .constExpr(let v)? = _storage._exprKind else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
      }()
      case .identExpr?: try {
        guard case .identExpr(let v)? = _storage._exprKind else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
      }()
      case .selectExpr?: try {
        guard case .selectExpr(let v)? = _storage._exprKind else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
      }()
      case .callExpr?: try {
        guard case .callExpr(let v)? = _storage._exprKind else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
      }()
      case .listExpr?: try {
        guard case .listExpr(let v)? = _storage._exprKind else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
      }()
      case .structExpr?: try {
        guard case .structExpr(let v)? = _storage._exprKind else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
      }()
      case .comprehensionExpr?: try {
        guard case .comprehensionExpr(let v)? = _storage._exprKind else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 9)
      }()
      case nil: break
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Cel_Expr_Expr, rhs: Cel_Expr_Expr) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._id != rhs_storage._id {return false}
        if _storage._exprKind != rhs_storage._exprKind {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Cel_Expr_Expr.Ident: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = Cel_Expr_Expr.protoMessageName + ".Ident"
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0")

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      default: break
      }
    }
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Cel_Expr_Expr.Ident, rhs: Cel_Expr_Expr.Ident) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Cel_Expr_Expr.Select: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = Cel_Expr_Expr.protoMessageName + ".Select"
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}operand\0\u{1}field\0\u{3}test_only\0")

  fileprivate class _StorageClass {
    var _operand: Cel_Expr_Expr? = nil
    var _field: String = String()
    var _testOnly: Bool = false

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _operand = source._operand
      _field = source._field
      _testOnly = source._testOnly
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularMessageField(value: &_storage._operand) }()
        case 2: try { try decoder.decodeSingularStringField(value: &_storage._field) }()
        case 3: try { try decoder.decodeSingularBoolField(value: &_storage._testOnly) }()
        default: break
        }
      }
    }
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      try { if let v = _storage._operand {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      } }()
      if !_storage._field.isEmpty {
        try visitor.visitSingularStringField(value: _storage._field, fieldNumber: 2)
      }
      if _storage._testOnly != false {
        try visitor.visitSingularBoolField(value: _storage._testOnly, fieldNumber: 3)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Cel_Expr_Expr.Select, rhs: Cel_Expr_Expr.Select) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._operand != rhs_storage._operand {return false}
        if _storage._field != rhs_storage._field {return false}
        if _storage._testOnly != rhs_storage._testOnly {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Cel_Expr_Expr.Call: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = Cel_Expr_Expr.protoMessageName + ".Call"
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}target\0\u{1}function\0\u{1}args\0")

  fileprivate class _StorageClass {
    var _target: Cel_Expr_Expr? = nil
    var _function: String = String()
    var _args: [Cel_Expr_Expr] = []

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _target = source._target
      _function = source._function
      _args = source._args
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularMessageField(value: &_storage._target) }()
        case 2: try { try decoder.decodeSingularStringField(value: &_storage._function) }()
        case 3: try { try decoder.decodeRepeatedMessageField(value: &_storage._args) }()
        default: break
        }
      }
    }
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      try { if let v = _storage._target {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      } }()
      if !_storage._function.isEmpty {
        try visitor.visitSingularStringField(value: _storage._function, fieldNumber: 2)
      }
      if !_storage._args.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._args, fieldNumber: 3)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Cel_Expr_Expr.Call, rhs: Cel_Expr_Expr.Call) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._target != rhs_storage._target {return false}
        if _storage._function != rhs_storage._function {return false}
        if _storage._args != rhs_storage._args {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Cel_Expr_Expr.CreateList: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = Cel_Expr_Expr.protoMessageName + ".CreateList"
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}elements\0\u{3}optional_indices\0")

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.elements) }()
      case 2: try { try decoder.decodeRepeatedInt32Field(value: &self.optionalIndices) }()
      default: break
      }
    }
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.elements.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.elements, fieldNumber: 1)
    }
    if !self.optionalIndices.isEmpty {
      try visitor.visitPackedInt32Field(value: self.optionalIndices, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Cel_Expr_Expr.CreateList, rhs: Cel_Expr_Expr.CreateList) -> Bool {
    if lhs.elements != rhs.elements {return false}
    if lhs.optionalIndices != rhs.optionalIndices {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Cel_Expr_Expr.CreateStruct: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = Cel_Expr_Expr.protoMessageName + ".CreateStruct"
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}message_name\0\u{1}entries\0")

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.messageName) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.entries) }()
      default: break
      }
    }
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.messageName.isEmpty {
      try visitor.visitSingularStringField(value: self.messageName, fieldNumber: 1)
    }
    if !self.entries.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.entries, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Cel_Expr_Expr.CreateStruct, rhs: Cel_Expr_Expr.CreateStruct) -> Bool {
    if lhs.messageName != rhs.messageName {return false}
    if lhs.entries != rhs.entries {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Cel_Expr_Expr.CreateStruct.Entry: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = Cel_Expr_Expr.CreateStruct.protoMessageName + ".Entry"
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{3}field_key\0\u{3}map_key\0\u{1}value\0\u{3}optional_entry\0")

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.id) }()
      case 2: try {
        var v: String?
        try decoder.decodeSingularStringField(value: &v)
        if let v = v {
          if self.keyKind != nil {try decoder.handleConflictingOneOf()}
          self.keyKind = .fieldKey(v)
        }
      }()
      case 3: try {
        var v: Cel_Expr_Expr?
        var hadOneofValue = false
        if let current = self.keyKind {
          hadOneofValue = true
          if case .mapKey(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.keyKind = .mapKey(v)
        }
      }()
      case 4: try { try decoder.decodeSingularMessageField(value: &self._value) }()
      case 5: try { try decoder.decodeSingularBoolField(value: &self.optionalEntry) }()
      default: break
      }
    }
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.id != 0 {
      try visitor.visitSingularInt64Field(value: self.id, fieldNumber: 1)
    }
    switch self.keyKind {
    case .fieldKey?: try {
      guard case .fieldKey(let v)? = self.keyKind else { preconditionFailure() }
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    }()
    case .mapKey?: try {
      guard case .mapKey(let v)? = self.keyKind else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }()
    case nil: break
    }
    try { if let v = self._value {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    } }()
    if self.optionalEntry != false {
      try visitor.visitSingularBoolField(value: self.optionalEntry, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Cel_Expr_Expr.CreateStruct.Entry, rhs: Cel_Expr_Expr.CreateStruct.Entry) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.keyKind != rhs.keyKind {return false}
    if lhs._value != rhs._value {return false}
    if lhs.optionalEntry != rhs.optionalEntry {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Cel_Expr_Expr.Comprehension: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = Cel_Expr_Expr.protoMessageName + ".Comprehension"
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}iter_var\0\u{3}iter_range\0\u{3}accu_var\0\u{3}accu_init\0\u{3}loop_condition\0\u{3}loop_step\0\u{1}result\0\u{3}iter_var2\0")

  fileprivate class _StorageClass {
    var _iterVar: String = String()
    var _iterVar2: String = String()
    var _iterRange: Cel_Expr_Expr? = nil
    var _accuVar: String = String()
    var _accuInit: Cel_Expr_Expr? = nil
    var _loopCondition: Cel_Expr_Expr? = nil
    var _loopStep: Cel_Expr_Expr? = nil
    var _result: Cel_Expr_Expr? = nil

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _iterVar = source._iterVar
      _iterVar2 = source._iterVar2
      _iterRange = source._iterRange
      _accuVar = source._accuVar
      _accuInit = source._accuInit
      _loopCondition = source._loopCondition
      _loopStep = source._loopStep
      _result = source._result
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularStringField(value: &_storage._iterVar) }()
        case 2: try { try decoder.decodeSingularMessageField(value: &_storage._iterRange) }()
        case 3: try { try decoder.decodeSingularStringField(value: &_storage._accuVar) }()
        case 4: try { try decoder.decodeSingularMessageField(value: &_storage._accuInit) }()
        case 5: try { try decoder.decodeSingularMessageField(value: &_storage._loopCondition) }()
        case 6: try { try decoder.decodeSingularMessageField(value: &_storage._loopStep) }()
        case 7: try { try decoder.decodeSingularMessageField(value: &_storage._result) }()
        case 8: try { try decoder.decodeSingularStringField(value: &_storage._iterVar2) }()
        default: break
        }
      }
    }
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if !_storage._iterVar.isEmpty {
        try visitor.visitSingularStringField(value: _storage._iterVar, fieldNumber: 1)
      }
      try { if let v = _storage._iterRange {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      } }()
      if !_storage._accuVar.isEmpty {
        try visitor.visitSingularStringField(value: _storage._accuVar, fieldNumber: 3)
      }
      try { if let v = _storage._accuInit {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
      } }()
      try { if let v = _storage._loopCondition {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
      } }()
      try { if let v = _storage._loopStep {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
      } }()
      try { if let v = _storage._result {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
      } }()
      if !_storage._iterVar2.isEmpty {
        try visitor.visitSingularStringField(value: _storage._iterVar2, fieldNumber: 8)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Cel_Expr_Expr.Comprehension, rhs: Cel_Expr_Expr.Comprehension) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._iterVar != rhs_storage._iterVar {return false}
        if _storage._iterVar2 != rhs_storage._iterVar2 {return false}
        if _storage._iterRange != rhs_storage._iterRange {return false}
        if _storage._accuVar != rhs_storage._accuVar {return false}
        if _storage._accuInit != rhs_storage._accuInit {return false}
        if _storage._loopCondition != rhs_storage._loopCondition {return false}
        if _storage._loopStep != rhs_storage._loopStep {return false}
        if _storage._result != rhs_storage._result {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Cel_Expr_Constant: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = _protobuf_package + ".Constant"
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}null_value\0\u{3}bool_value\0\u{3}int64_value\0\u{3}uint64_value\0\u{3}double_value\0\u{3}string_value\0\u{3}bytes_value\0\u{3}duration_value\0\u{3}timestamp_value\0")

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: SwiftProtobuf.Google_Protobuf_NullValue?
        try decoder.decodeSingularEnumField(value: &v)
        if let v = v {
          if self.constantKind != nil {try decoder.handleConflictingOneOf()}
          self.constantKind = .nullValue(v)
        }
      }()
      case 2: try {
        var v: Bool?
        try decoder.decodeSingularBoolField(value: &v)
        if let v = v {
          if self.constantKind != nil {try decoder.handleConflictingOneOf()}
          self.constantKind = .boolValue(v)
        }
      }()
      case 3: try {
        var v: Int64?
        try decoder.decodeSingularInt64Field(value: &v)
        if let v = v {
          if self.constantKind != nil {try decoder.handleConflictingOneOf()}
          self.constantKind = .int64Value(v)
        }
      }()
      case 4: try {
        var v: UInt64?
        try decoder.decodeSingularUInt64Field(value: &v)
        if let v = v {
          if self.constantKind != nil {try decoder.handleConflictingOneOf()}
          self.constantKind = .uint64Value(v)
        }
      }()
      case 5: try {
        var v: Double?
        try decoder.decodeSingularDoubleField(value: &v)
        if let v = v {
          if self.constantKind != nil {try decoder.handleConflictingOneOf()}
          self.constantKind = .doubleValue(v)
        }
      }()
      case 6: try {
        var v: String?
        try decoder.decodeSingularStringField(value: &v)
        if let v = v {
          if self.constantKind != nil {try decoder.handleConflictingOneOf()}
          self.constantKind = .stringValue(v)
        }
      }()
      case 7: try {
        var v: Data?
        try decoder.decodeSingularBytesField(value: &v)
        if let v = v {
          if self.constantKind != nil {try decoder.handleConflictingOneOf()}
          self.constantKind = .bytesValue(v)
        }
      }()
      case 8: try {
        var v: SwiftProtobuf.Google_Protobuf_Duration?
        var hadOneofValue = false
        if let current = self.constantKind {
          hadOneofValue = true
          if case .durationValue(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.constantKind = .durationValue(v)
        }
      }()
      case 9: try {
        var v: SwiftProtobuf.Google_Protobuf_Timestamp?
        var hadOneofValue = false
        if let current = self.constantKind {
          hadOneofValue = true
          if case .timestampValue(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.constantKind = .timestampValue(v)
        }
      }()
      default: break
      }
    }
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.constantKind {
    case .nullValue?: try {
      guard case .nullValue(let v)? = self.constantKind else { preconditionFailure() }
      try visitor.visitSingularEnumField(value: v, fieldNumber: 1)
    }()
    case .boolValue?: try {
      guard case .boolValue(let v)? = self.constantKind else { preconditionFailure() }
      try visitor.visitSingularBoolField(value: v, fieldNumber: 2)
    }()
    case .int64Value?: try {
      guard case .int64Value(let v)? = self.constantKind else { preconditionFailure() }
      try visitor.visitSingularInt64Field(value: v, fieldNumber: 3)
    }()
    case .uint64Value?: try {
      guard case .uint64Value(let v)? = self.constantKind else { preconditionFailure() }
      try visitor.visitSingularUInt64Field(value: v, fieldNumber: 4)
    }()
    case .doubleValue?: try {
      guard case .doubleValue(let v)? = self.constantKind else { preconditionFailure() }
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 5)
    }()
    case .stringValue?: try {
      guard case .stringValue(let v)? = self.constantKind else { preconditionFailure() }
      try visitor.visitSingularStringField(value: v, fieldNumber: 6)
    }()
    case .bytesValue?: try {
      guard case .bytesValue(let v)? = self.constantKind else { preconditionFailure() }
      try visitor.visitSingularBytesField(value: v, fieldNumber: 7)
    }()
    case .durationValue?: try {
      guard case .durationValue(let v)? = self.constantKind else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
    }()
    case .timestampValue?: try {
      guard case .timestampValue(let v)? = self.constantKind else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 9)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Cel_Expr_Constant, rhs: Cel_Expr_Constant) -> Bool {
    if lhs.constantKind != rhs.constantKind {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Cel_Expr_SourceInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = _protobuf_package + ".SourceInfo"
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}syntax_version\0\u{1}location\0\u{3}line_offsets\0\u{1}positions\0\u{3}macro_calls\0\u{1}extensions\0")

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.syntaxVersion) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.location) }()
      case 3: try { try decoder.decodeRepeatedInt32Field(value: &self.lineOffsets) }()
      case 4: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufInt64,SwiftProtobuf.ProtobufInt32>.self, value: &self.positions) }()
      case 5: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufInt64,Cel_Expr_Expr>.self, value: &self.macroCalls) }()
      case 6: try { try decoder.decodeRepeatedMessageField(value: &self.extensions) }()
      default: break
      }
    }
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.syntaxVersion.isEmpty {
      try visitor.visitSingularStringField(value: self.syntaxVersion, fieldNumber: 1)
    }
    if !self.location.isEmpty {
      try visitor.visitSingularStringField(value: self.location, fieldNumber: 2)
    }
    if !self.lineOffsets.isEmpty {
      try visitor.visitPackedInt32Field(value: self.lineOffsets, fieldNumber: 3)
    }
    if !self.positions.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufInt64,SwiftProtobuf.ProtobufInt32>.self, value: self.positions, fieldNumber: 4)
    }
    if !self.macroCalls.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufInt64,Cel_Expr_Expr>.self, value: self.macroCalls, fieldNumber: 5)
    }
    if !self.extensions.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.extensions, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Cel_Expr_SourceInfo, rhs: Cel_Expr_SourceInfo) -> Bool {
    if lhs.syntaxVersion != rhs.syntaxVersion {return false}
    if lhs.location != rhs.location {return false}
    if lhs.lineOffsets != rhs.lineOffsets {return false}
    if lhs.positions != rhs.positions {return false}
    if lhs.macroCalls != rhs.macroCalls {return false}
    if lhs.extensions != rhs.extensions {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Cel_Expr_SourceInfo.Extension: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = Cel_Expr_SourceInfo.protoMessageName + ".Extension"
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{3}affected_components\0\u{1}version\0")

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.id) }()
      case 2: try { try decoder.decodeRepeatedEnumField(value: &self.affectedComponents) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._version) }()
      default: break
      }
    }
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    if !self.affectedComponents.isEmpty {
      try visitor.visitPackedEnumField(value: self.affectedComponents, fieldNumber: 2)
    }
    try { if let v = self._version {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Cel_Expr_SourceInfo.Extension, rhs: Cel_Expr_SourceInfo.Extension) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.affectedComponents != rhs.affectedComponents {return false}
    if lhs._version != rhs._version {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Cel_Expr_SourceInfo.Extension.Component: SwiftProtobuf._ProtoNameProviding {
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0COMPONENT_UNSPECIFIED\0\u{1}COMPONENT_PARSER\0\u{1}COMPONENT_TYPE_CHECKER\0\u{1}COMPONENT_RUNTIME\0")
}

extension Cel_Expr_SourceInfo.Extension.Version: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = Cel_Expr_SourceInfo.Extension.protoMessageName + ".Version"
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}major\0\u{1}minor\0")

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.major) }()
      case 2: try { try decoder.decodeSingularInt64Field(value: &self.minor) }()
      default: break
      }
    }
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.major != 0 {
      try visitor.visitSingularInt64Field(value: self.major, fieldNumber: 1)
    }
    if self.minor != 0 {
      try visitor.visitSingularInt64Field(value: self.minor, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Cel_Expr_SourceInfo.Extension.Version, rhs: Cel_Expr_SourceInfo.Extension.Version) -> Bool {
    if lhs.major != rhs.major {return false}
    if lhs.minor != rhs.minor {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
