// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by protoc-gen-cel-swift.
// Source: test/proto3pb/test_import.proto

import CEL
import CELProtobuf
import SwiftProtobuf

/// The CEL description of `test/proto3pb/test_import.proto`, for `ProtobufTypes`.
package let Google_Expr_Proto3_Test_TestImport_CELFile = ProtobufFile(
  path: "test/proto3pb/test_import.proto",
  messageTypes: [
  ],
  enumTypes: [
    ProtobufEnumType("google.expr.proto3.test.ImportedGlobalEnum", values: [("IMPORT_FOO", 0), ("IMPORT_BAR", 1), ("IMPORT_BAZ", 2)]),
  ],
  extensions: [
  ],
  dependencies: []
)
