// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: test/proto3pb/test_all_types.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// This proto tests that global enums are resolved correctly.
package enum Google_Expr_Proto3_Test_GlobalEnum: SwiftProtobuf.Enum, Swift.CaseIterable {
  package typealias RawValue = Int
  case goo // = 0
  case gar // = 1
  case gaz // = 2
  case UNRECOGNIZED(Int)

  package init() {
    self = .goo
  }

  package init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .goo
    case 1: self = .gar
    case 2: self = .gaz
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  package var rawValue: Int {
    switch self {
    case .goo: return 0
    case .gar: return 1
    case .gaz: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  package static let allCases: [Google_Expr_Proto3_Test_GlobalEnum] = [
    .goo,
    .gar,
    .gaz,
  ]

}

/// This proto includes every type of field in both singular and repeated
/// forms.
package struct Google_Expr_Proto3_Test_TestAllTypes: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Singular
  package var singleInt32: Int32 {
    get {_storage._singleInt32}
    set {_uniqueStorage()._singleInt32 = newValue}
  }

  package var singleInt64: Int64 {
    get {_storage._singleInt64}
    set {_uniqueStorage()._singleInt64 = newValue}
  }

  package var singleUint32: UInt32 {
    get {_storage._singleUint32}
    set {_uniqueStorage()._singleUint32 = newValue}
  }

  package var singleUint64: UInt64 {
    get {_storage._singleUint64}
    set {_uniqueStorage()._singleUint64 = newValue}
  }

  package var singleSint32: Int32 {
    get {_storage._singleSint32}
    set {_uniqueStorage()._singleSint32 = newValue}
  }

  package var singleSint64: Int64 {
    get {_storage._singleSint64}
    set {_uniqueStorage()._singleSint64 = newValue}
  }

  package var singleFixed32: UInt32 {
    get {_storage._singleFixed32}
    set {_uniqueStorage()._singleFixed32 = newValue}
  }

  package var singleFixed64: UInt64 {
    get {_storage._singleFixed64}
    set {_uniqueStorage()._singleFixed64 = newValue}
  }

  package var singleSfixed32: Int32 {
    get {_storage._singleSfixed32}
    set {_uniqueStorage()._singleSfixed32 = newValue}
  }

  package var singleSfixed64: Int64 {
    get {_storage._singleSfixed64}
    set {_uniqueStorage()._singleSfixed64 = newValue}
  }

  package var singleFloat: Float {
    get {_storage._singleFloat}
    set {_uniqueStorage()._singleFloat = newValue}
  }

  package var singleDouble: Double {
    get {_storage._singleDouble}
    set {_uniqueStorage()._singleDouble = newValue}
  }

  package var singleBool: Bool {
    get {_storage._singleBool}
    set {_uniqueStorage()._singleBool = newValue}
  }

  package var singleString: String {
    get {_storage._singleString}
    set {_uniqueStorage()._singleString = newValue}
  }

  package var singleBytes: Data {
    get {_storage._singleBytes}
    set {_uniqueStorage()._singleBytes = newValue}
  }

  package var standaloneEnum: Google_Expr_Proto3_Test_TestAllTypes.NestedEnum {
    get {_storage._standaloneEnum}
    set {_uniqueStorage()._standaloneEnum = newValue}
  }

  /// Wellknown.
  package var singleAny: SwiftProtobuf.Google_Protobuf_Any {
    get {_storage._singleAny ?? SwiftProtobuf.Google_Protobuf_Any()}
    set {_uniqueStorage()._singleAny = newValue}
  }
  /// Returns true if `singleAny` has been explicitly set.
  package var hasSingleAny: Bool {_storage._singleAny != nil}
  /// Clears the value of `singleAny`. Subsequent reads from it will return its default value.
  package mutating func clearSingleAny() {_uniqueStorage()._singleAny = nil}

  package var singleDuration: SwiftProtobuf.Google_Protobuf_Duration {
    get {_storage._singleDuration ?? SwiftProtobuf.Google_Protobuf_Duration()}
    set {_uniqueStorage()._singleDuration = newValue}
  }
  /// Returns true if `singleDuration` has been explicitly set.
  package var hasSingleDuration: Bool {_storage._singleDuration != nil}
  /// Clears the value of `singleDuration`. Subsequent reads from it will return its default value.
  package mutating func clearSingleDuration() {_uniqueStorage()._singleDuration = nil}

  package var singleTimestamp: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {_storage._singleTimestamp ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_uniqueStorage()._singleTimestamp = newValue}
  }
  /// Returns true if `singleTimestamp` has been explicitly set.
  package var hasSingleTimestamp: Bool {_storage._singleTimestamp != nil}
  /// Clears the value of `singleTimestamp`. Subsequent reads from it will return its default value.
  package mutating func clearSingleTimestamp() {_uniqueStorage()._singleTimestamp = nil}

  package var singleStruct: SwiftProtobuf.Google_Protobuf_Struct {
    get {_storage._singleStruct ?? SwiftProtobuf.Google_Protobuf_Struct()}
    set {_uniqueStorage()._singleStruct = newValue}
  }
  /// Returns true if `singleStruct` has been explicitly set.
  package var hasSingleStruct: Bool {_storage._singleStruct != nil}
  /// Clears the value of `singleStruct`. Subsequent reads from it will return its default value.
  package mutating func clearSingleStruct() {_uniqueStorage()._singleStruct = nil}

  package var singleValue: SwiftProtobuf.Google_Protobuf_Value {
    get {_storage._singleValue ?? SwiftProtobuf.Google_Protobuf_Value()}
    set {_uniqueStorage()._singleValue = newValue}
  }
  /// Returns true if `singleValue` has been explicitly set.
  package var hasSingleValue: Bool {_storage._singleValue != nil}
  /// Clears the value of `singleValue`. Subsequent reads from it will return its default value.
  package mutating func clearSingleValue() {_uniqueStorage()._singleValue = nil}

  package var singleInt64Wrapper: SwiftProtobuf.Google_Protobuf_Int64Value {
    get {_storage._singleInt64Wrapper ?? SwiftProtobuf.Google_Protobuf_Int64Value()}
    set {_uniqueStorage()._singleInt64Wrapper = newValue}
  }
  /// Returns true if `singleInt64Wrapper` has been explicitly set.
  package var hasSingleInt64Wrapper: Bool {_storage._singleInt64Wrapper != nil}
  /// Clears the value of `singleInt64Wrapper`. Subsequent reads from it will return its default value.
  package mutating func clearSingleInt64Wrapper() {_uniqueStorage()._singleInt64Wrapper = nil}

  package var singleInt32Wrapper: SwiftProtobuf.Google_Protobuf_Int32Value {
    get {_storage._singleInt32Wrapper ?? SwiftProtobuf.Google_Protobuf_Int32Value()}
    set {_uniqueStorage()._singleInt32Wrapper = newValue}
  }
  /// Returns true if `singleInt32Wrapper` has been explicitly set.
  package var hasSingleInt32Wrapper: Bool {_storage._singleInt32Wrapper != nil}
  /// Clears the value of `singleInt32Wrapper`. Subsequent reads from it will return its default value.
  package mutating func clearSingleInt32Wrapper() {_uniqueStorage()._singleInt32Wrapper = nil}

  package var singleDoubleWrapper: SwiftProtobuf.Google_Protobuf_DoubleValue {
    get {_storage._singleDoubleWrapper ?? SwiftProtobuf.Google_Protobuf_DoubleValue()}
    set {_uniqueStorage()._singleDoubleWrapper = newValue}
  }
  /// Returns true if `singleDoubleWrapper` has been explicitly set.
  package var hasSingleDoubleWrapper: Bool {_storage._singleDoubleWrapper != nil}
  /// Clears the value of `singleDoubleWrapper`. Subsequent reads from it will return its default value.
  package mutating func clearSingleDoubleWrapper() {_uniqueStorage()._singleDoubleWrapper = nil}

  package var singleFloatWrapper: SwiftProtobuf.Google_Protobuf_FloatValue {
    get {_storage._singleFloatWrapper ?? SwiftProtobuf.Google_Protobuf_FloatValue()}
    set {_uniqueStorage()._singleFloatWrapper = newValue}
  }
  /// Returns true if `singleFloatWrapper` has been explicitly set.
  package var hasSingleFloatWrapper: Bool {_storage._singleFloatWrapper != nil}
  /// Clears the value of `singleFloatWrapper`. Subsequent reads from it will return its default value.
  package mutating func clearSingleFloatWrapper() {_uniqueStorage()._singleFloatWrapper = nil}

  package var singleUint64Wrapper: SwiftProtobuf.Google_Protobuf_UInt64Value {
    get {_storage._singleUint64Wrapper ?? SwiftProtobuf.Google_Protobuf_UInt64Value()}
    set {_uniqueStorage()._singleUint64Wrapper = newValue}
  }
  /// Returns true if `singleUint64Wrapper` has been explicitly set.
  package var hasSingleUint64Wrapper: Bool {_storage._singleUint64Wrapper != nil}
  /// Clears the value of `singleUint64Wrapper`. Subsequent reads from it will return its default value.
  package mutating func clearSingleUint64Wrapper() {_uniqueStorage()._singleUint64Wrapper = nil}

  package var singleUint32Wrapper: SwiftProtobuf.Google_Protobuf_UInt32Value {
    get {_storage._singleUint32Wrapper ?? SwiftProtobuf.Google_Protobuf_UInt32Value()}
    set {_uniqueStorage()._singleUint32Wrapper = newValue}
  }
  /// Returns true if `singleUint32Wrapper` has been explicitly set.
  package var hasSingleUint32Wrapper: Bool {_storage._singleUint32Wrapper != nil}
  /// Clears the value of `singleUint32Wrapper`. Subsequent reads from it will return its default value.
  package mutating func clearSingleUint32Wrapper() {_uniqueStorage()._singleUint32Wrapper = nil}

  package var singleStringWrapper: SwiftProtobuf.Google_Protobuf_StringValue {
    get {_storage._singleStringWrapper ?? SwiftProtobuf.Google_Protobuf_StringValue()}
    set {_uniqueStorage()._singleStringWrapper = newValue}
  }
  /// Returns true if `singleStringWrapper` has been explicitly set.
  package var hasSingleStringWrapper: Bool {_storage._singleStringWrapper != nil}
  /// Clears the value of `singleStringWrapper`. Subsequent reads from it will return its default value.
  package mutating func clearSingleStringWrapper() {_uniqueStorage()._singleStringWrapper = nil}

  package var singleBoolWrapper: SwiftProtobuf.Google_Protobuf_BoolValue {
    get {_storage._singleBoolWrapper ?? SwiftProtobuf.Google_Protobuf_BoolValue()}
    set {_uniqueStorage()._singleBoolWrapper = newValue}
  }
  /// Returns true if `singleBoolWrapper` has been explicitly set.
  package var hasSingleBoolWrapper: Bool {_storage._singleBoolWrapper != nil}
  /// Clears the value of `singleBoolWrapper`. Subsequent reads from it will return its default value.
  package mutating func clearSingleBoolWrapper() {_uniqueStorage()._singleBoolWrapper = nil}

  package var singleBytesWrapper: SwiftProtobuf.Google_Protobuf_BytesValue {
    get {_storage._singleBytesWrapper ?? SwiftProtobuf.Google_Protobuf_BytesValue()}
    set {_uniqueStorage()._singleBytesWrapper = newValue}
  }
  /// Returns true if `singleBytesWrapper` has been explicitly set.
  package var hasSingleBytesWrapper: Bool {_storage._singleBytesWrapper != nil}
  /// Clears the value of `singleBytesWrapper`. Subsequent reads from it will return its default value.
  package mutating func clearSingleBytesWrapper() {_uniqueStorage()._singleBytesWrapper = nil}

  /// Nested messages
  package var nestedType: OneOf_NestedType? {
    get {return _storage._nestedType}
    set {_uniqueStorage()._nestedType = newValue}
  }

  package var singleNestedMessage: Google_Expr_Proto3_Test_TestAllTypes.NestedMessage {
    get {
      if case .singleNestedMessage(let v)? = _storage._nestedType {return v}
      return Google_Expr_Proto3_Test_TestAllTypes.NestedMessage()
    }
    set {_uniqueStorage()._nestedType = .singleNestedMessage(newValue)}
  }

  package var singleNestedEnum: Google_Expr_Proto3_Test_TestAllTypes.NestedEnum {
    get {
      if case .singleNestedEnum(let v)? = _storage._nestedType {return v}
      return .foo
    }
    set {_uniqueStorage()._nestedType = .singleNestedEnum(newValue)}
  }

  /// Repeated
  package var repeatedInt32: [Int32] {
    get {_storage._repeatedInt32}
    set {_uniqueStorage()._repeatedInt32 = newValue}
  }

  package var repeatedInt64: [Int64] {
    get {_storage._repeatedInt64}
    set {_uniqueStorage()._repeatedInt64 = newValue}
  }

  package var repeatedUint32: [UInt32] {
    get {_storage._repeatedUint32}
    set {_uniqueStorage()._repeatedUint32 = newValue}
  }

  package var repeatedUint64: [UInt64] {
    get {_storage._repeatedUint64}
    set {_uniqueStorage()._repeatedUint64 = newValue}
  }

  package var repeatedSint32: [Int32] {
    get {_storage._repeatedSint32}
    set {_uniqueStorage()._repeatedSint32 = newValue}
  }

  package var repeatedSint64: [Int64] {
    get {_storage._repeatedSint64}
    set {_uniqueStorage()._repeatedSint64 = newValue}
  }

  package var repeatedFixed32: [UInt32] {
    get {_storage._repeatedFixed32}
    set {_uniqueStorage()._repeatedFixed32 = newValue}
  }

  package var repeatedFixed64: [UInt64] {
    get {_storage._repeatedFixed64}
    set {_uniqueStorage()._repeatedFixed64 = newValue}
  }

  package var repeatedSfixed32: [Int32] {
    get {_storage._repeatedSfixed32}
    set {_uniqueStorage()._repeatedSfixed32 = newValue}
  }

  package var repeatedSfixed64: [Int64] {
    get {_storage._repeatedSfixed64}
    set {_uniqueStorage()._repeatedSfixed64 = newValue}
  }

  package var repeatedFloat: [Float] {
    get {_storage._repeatedFloat}
    set {_uniqueStorage()._repeatedFloat = newValue}
  }

  package var repeatedDouble: [Double] {
    get {_storage._repeatedDouble}
    set {_uniqueStorage()._repeatedDouble = newValue}
  }

  package var repeatedBool: [Bool] {
    get {_storage._repeatedBool}
    set {_uniqueStorage()._repeatedBool = newValue}
  }

  package var repeatedString: [String] {
    get {_storage._repeatedString}
    set {_uniqueStorage()._repeatedString = newValue}
  }

  package var repeatedBytes: [Data] {
    get {_storage._repeatedBytes}
    set {_uniqueStorage()._repeatedBytes = newValue}
  }

  package var repeatedNestedMessage: [Google_Expr_Proto3_Test_TestAllTypes.NestedMessage] {
    get {_storage._repeatedNestedMessage}
    set {_uniqueStorage()._repeatedNestedMessage = newValue}
  }

  package var repeatedNestedEnum: [Google_Expr_Proto3_Test_TestAllTypes.NestedEnum] {
    get {_storage._repeatedNestedEnum}
    set {_uniqueStorage()._repeatedNestedEnum = newValue}
  }

  package var repeatedStringPiece: [String] {
    get {_storage._repeatedStringPiece}
    set {_uniqueStorage()._repeatedStringPiece = newValue}
  }

  package var repeatedCord: [String] {
    get {_storage._repeatedCord}
    set {_uniqueStorage()._repeatedCord = newValue}
  }

  package var repeatedLazyMessage: [Google_Expr_Proto3_Test_TestAllTypes.NestedMessage] {
    get {_storage._repeatedLazyMessage}
    set {_uniqueStorage()._repeatedLazyMessage = newValue}
  }

  /// Map
  package var mapStringString: Dictionary<String,String> {
    get {_storage._mapStringString}
    set {_uniqueStorage()._mapStringString = newValue}
  }

  package var mapInt64NestedType: Dictionary<Int64,Google_Expr_Proto3_Test_NestedTestAllTypes> {
    get {_storage._mapInt64NestedType}
    set {_uniqueStorage()._mapInt64NestedType = newValue}
  }

  /// Imports
  package var importedEnums: [Google_Expr_Proto3_Test_ImportedGlobalEnum] {
    get {_storage._importedEnums}
    set {_uniqueStorage()._importedEnums = newValue}
  }

  package var unknownFields = SwiftProtobuf.UnknownStorage()

  /// Nested messages
  package enum OneOf_NestedType: Equatable, Sendable {
    case singleNestedMessage(Google_Expr_Proto3_Test_TestAllTypes.NestedMessage)
    case singleNestedEnum(Google_Expr_Proto3_Test_TestAllTypes.NestedEnum)

  }

  package enum NestedEnum: SwiftProtobuf.Enum, Swift.CaseIterable {
    package typealias RawValue = Int
    case foo // = 0
    case bar // = 1
    case baz // = 2
    case UNRECOGNIZED(Int)

    package init() {
      self = .foo
    }

    package init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .foo
      case 1: self = .bar
      case 2: self = .baz
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    package var rawValue: Int {
      switch self {
      case .foo: return 0
      case .bar: return 1
      case .baz: return 2
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    package static let allCases: [Google_Expr_Proto3_Test_TestAllTypes.NestedEnum] = [
      .foo,
      .bar,
      .baz,
    ]

  }

  package struct NestedMessage: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// The field name "b" fails to compile in proto1 because it conflicts with
    /// a local variable named "b" in one of the generated methods.
    /// This file needs to compile in proto1 to test backwards-compatibility.
    package var bb: Int32 = 0

    package var unknownFields = SwiftProtobuf.UnknownStorage()

    package init() {}
  }

  package init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

/// This proto includes a recursively nested message.
package struct Google_Expr_Proto3_Test_NestedTestAllTypes: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  package var child: Google_Expr_Proto3_Test_NestedTestAllTypes {
    get {_storage._child ?? Google_Expr_Proto3_Test_NestedTestAllTypes()}
    set {_uniqueStorage()._child = newValue}
  }
  /// Returns true if `child` has been explicitly set.
  package var hasChild: Bool {_storage._child != nil}
  /// Clears the value of `child`. Subsequent reads from it will return its default value.
  package mutating func clearChild() {_uniqueStorage()._child = nil}

  package var payload: Google_Expr_Proto3_Test_TestAllTypes {
    get {_storage._payload ?? Google_Expr_Proto3_Test_TestAllTypes()}
    set {_uniqueStorage()._payload = newValue}
  }
  /// Returns true if `payload` has been explicitly set.
  package var hasPayload: Bool {_storage._payload != nil}
  /// Clears the value of `payload`. Subsequent reads from it will return its default value.
  package mutating func clearPayload() {_uniqueStorage()._payload = nil}

  package var unknownFields = SwiftProtobuf.UnknownStorage()

  package init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

/// This proto tests json_name options
package struct Google_Expr_Proto3_Test_TestJsonNames: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  package var int32SnakeCaseJsonName: Int32 = 0

  package var int64CamelCaseJsonName: Int64 = 0

  package var uint32DefaultJsonName: UInt32 = 0

  package var uint64CustomJsonName: UInt64 = 0

  /// Collides with normal field name.
  package var stringJsonNameShadows: String = String()

  package var singleString: String = String()

  package var unknownFields = SwiftProtobuf.UnknownStorage()

  package init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "google.expr.proto3.test"

extension Google_Expr_Proto3_Test_GlobalEnum: SwiftProtobuf._ProtoNameProviding {
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0GOO\0\u{1}GAR\0\u{1}GAZ\0")
}

extension Google_Expr_Proto3_Test_TestAllTypes: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = _protobuf_package + ".TestAllTypes"
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}single_int32\0\u{3}single_int64\0\u{3}single_uint32\0\u{3}single_uint64\0\u{3}single_sint32\0\u{3}single_sint64\0\u{3}single_fixed32\0\u{3}single_fixed64\0\u{3}single_sfixed32\0\u{3}single_sfixed64\0\u{3}single_float\0\u{3}single_double\0\u{3}single_bool\0\u{3}single_string\0\u{3}single_bytes\0\u{4}\u{3}single_nested_message\0\u{4}\u{3}single_nested_enum\0\u{3}standalone_enum\0\u{4}\u{9}repeated_int32\0\u{3}repeated_int64\0\u{3}repeated_uint32\0\u{3}repeated_uint64\0\u{3}repeated_sint32\0\u{3}repeated_sint64\0\u{3}repeated_fixed32\0\u{3}repeated_fixed64\0\u{3}repeated_sfixed32\0\u{3}repeated_sfixed64\0\u{3}repeated_float\0\u{3}repeated_double\0\u{3}repeated_bool\0\u{3}repeated_string\0\u{3}repeated_bytes\0\u{4}\u{3}repeated_nested_message\0\u{4}\u{3}repeated_nested_enum\0\u{4}\u{3}repeated_string_piece\0\u{3}repeated_cord\0\u{4}\u{2}repeated_lazy_message\0\u{3}map_string_string\0\u{3}map_int64_nested_type\0\u{3}imported_enums\0\u{4}(single_any\0\u{3}single_duration\0\u{3}single_timestamp\0\u{3}single_struct\0\u{3}single_value\0\u{3}single_int64_wrapper\0\u{3}single_int32_wrapper\0\u{3}single_double_wrapper\0\u{3}single_float_wrapper\0\u{3}single_uint64_wrapper\0\u{3}single_uint32_wrapper\0\u{3}single_string_wrapper\0\u{3}single_bool_wrapper\0\u{3}single_bytes_wrapper\0")

  fileprivate class _StorageClass {
    var _singleInt32: Int32 = 0
    var _singleInt64: Int64 = 0
    var _singleUint32: UInt32 = 0
    var _singleUint64: UInt64 = 0
    var _singleSint32: Int32 = 0
    var _singleSint64: Int64 = 0
    var _singleFixed32: UInt32 = 0
    var _singleFixed64: UInt64 = 0
    var _singleSfixed32: Int32 = 0
    var _singleSfixed64: Int64 = 0
    var _singleFloat: Float = 0
    var _singleDouble: Double = 0
    var _singleBool: Bool = false
    var _singleString: String = String()
    var _singleBytes: Data = Data()
    var _standaloneEnum: Google_Expr_Proto3_Test_TestAllTypes.NestedEnum = .foo
    var _singleAny: SwiftProtobuf.Google_Protobuf_Any? = nil
    var _singleDuration: SwiftProtobuf.Google_Protobuf_Duration? = nil
    var _singleTimestamp: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
    var _singleStruct: SwiftProtobuf.Google_Protobuf_Struct? = nil
    var _singleValue: SwiftProtobuf.Google_Protobuf_Value? = nil
    var _singleInt64Wrapper: SwiftProtobuf.Google_Protobuf_Int64Value? = nil
    var _singleInt32Wrapper: SwiftProtobuf.Google_Protobuf_Int32Value? = nil
    var _singleDoubleWrapper: SwiftProtobuf.Google_Protobuf_DoubleValue? = nil
    var _singleFloatWrapper: SwiftProtobuf.Google_Protobuf_FloatValue? = nil
    var _singleUint64Wrapper: SwiftProtobuf.Google_Protobuf_UInt64Value? = nil
    var _singleUint32Wrapper: SwiftProtobuf.Google_Protobuf_UInt32Value? = nil
    var _singleStringWrapper: SwiftProtobuf.Google_Protobuf_StringValue? = nil
    var _singleBoolWrapper: SwiftProtobuf.Google_Protobuf_BoolValue? = nil
    var _singleBytesWrapper: SwiftProtobuf.Google_Protobuf_BytesValue? = nil
    var _nestedType: Google_Expr_Proto3_Test_TestAllTypes.OneOf_NestedType?
    var _repeatedInt32: [Int32] = []
    var _repeatedInt64: [Int64] = []
    var _repeatedUint32: [UInt32] = []
    var _repeatedUint64: [UInt64] = []
    var _repeatedSint32: [Int32] = []
    var _repeatedSint64: [Int64] = []
    var _repeatedFixed32: [UInt32] = []
    var _repeatedFixed64: [UInt64] = []
    var _repeatedSfixed32: [Int32] = []
    var _repeatedSfixed64: [Int64] = []
    var _repeatedFloat: [Float] = []
    var _repeatedDouble: [Double] = []
    var _repeatedBool: [Bool] = []
    var _repeatedString: [String] = []
    var _repeatedBytes: [Data] = []
    var _repeatedNestedMessage: [Google_Expr_Proto3_Test_TestAllTypes.NestedMessage] = []
    var _repeatedNestedEnum: [Google_Expr_Proto3_Test_TestAllTypes.NestedEnum] = []
    var _repeatedStringPiece: [String] = []
    var _repeatedCord: [String] = []
    var _repeatedLazyMessage: [Google_Expr_Proto3_Test_TestAllTypes.NestedMessage] = []
    var _mapStringString: Dictionary<String,String> = [:]
    var _mapInt64NestedType: Dictionary<Int64,Google_Expr_Proto3_Test_NestedTestAllTypes> = [:]
    var _importedEnums: [Google_Expr_Proto3_Test_ImportedGlobalEnum] = []

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _singleInt32 = source._singleInt32
      _singleInt64 = source._singleInt64
      _singleUint32 = source._singleUint32
      _singleUint64 = source._singleUint64
      _singleSint32 = source._singleSint32
      _singleSint64 = source._singleSint64
      _singleFixed32 = source._singleFixed32
      _singleFixed64 = source._singleFixed64
      _singleSfixed32 = source._singleSfixed32
      _singleSfixed64 = source._singleSfixed64
      _singleFloat = source._singleFloat
      _singleDouble = source._singleDouble
      _singleBool = source._singleBool
      _singleString = source._singleString
      _singleBytes = source._singleBytes
      _standaloneEnum = source._standaloneEnum
      _singleAny = source._singleAny
      _singleDuration = source._singleDuration
      _singleTimestamp = source._singleTimestamp
      _singleStruct = source._singleStruct
      _singleValue = source._singleValue
      _singleInt64Wrapper = source._singleInt64Wrapper
      _singleInt32Wrapper = source._singleInt32Wrapper
      _singleDoubleWrapper = source._singleDoubleWrapper
      _singleFloatWrapper = source._singleFloatWrapper
      _singleUint64Wrapper = source._singleUint64Wrapper
      _singleUint32Wrapper = source._singleUint32Wrapper
      _singleStringWrapper = source._singleStringWrapper
      _singleBoolWrapper = source._singleBoolWrapper
      _singleBytesWrapper = source._singleBytesWrapper
      _nestedType = source._nestedType
      _repeatedInt32 = source._repeatedInt32
      _repeatedInt64 = source._repeatedInt64
      _repeatedUint32 = source._repeatedUint32
      _repeatedUint64 = source._repeatedUint64
      _repeatedSint32 = source._repeatedSint32
      _repeatedSint64 = source._repeatedSint64
      _repeatedFixed32 = source._repeatedFixed32
      _repeatedFixed64 = source._repeatedFixed64
      _repeatedSfixed32 = source._repeatedSfixed32
      _repeatedSfixed64 = source._repeatedSfixed64
      _repeatedFloat = source._repeatedFloat
      _repeatedDouble = source._repeatedDouble
      _repeatedBool = source._repeatedBool
      _repeatedString = source._repeatedString
      _repeatedBytes = source._repeatedBytes
      _repeatedNestedMessage = source._repeatedNestedMessage
      _repeatedNestedEnum = source._repeatedNestedEnum
      _repeatedStringPiece = source._repeatedStringPiece
      _repeatedCord = source._repeatedCord
      _repeatedLazyMessage = source._repeatedLazyMessage
      _mapStringString = source._mapStringString
      _mapInt64NestedType = source._mapInt64NestedType
      _importedEnums = source._importedEnums
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularInt32Field(value: &_storage._singleInt32) }()
        case 2: try { try decoder.decodeSingularInt64Field(value: &_storage._singleInt64) }()
        case 3: try { try decoder.decodeSingularUInt32Field(value: &_storage._singleUint32) }()
        case 4: try { try decoder.decodeSingularUInt64Field(value: &_storage._singleUint64) }()
        case 5: try { try decoder.decodeSingularSInt32Field(value: &_storage._singleSint32) }()
        case 6: try { try decoder.decodeSingularSInt64Field(value: &_storage._singleSint64) }()
        case 7: try { try decoder.decodeSingularFixed32Field(value: &_storage._singleFixed32) }()
        case 8: try { try decoder.decodeSingularFixed64Field(value: &_storage._singleFixed64) }()
        case 9: try { try decoder.decodeSingularSFixed32Field(value: &_storage._singleSfixed32) }()
        case 10: try { try decoder.decodeSingularSFixed64Field(value: &_storage._singleSfixed64) }()
        case 11: try { try decoder.decodeSingularFloatField(value: &_storage._singleFloat) }()
        case 12: try { try decoder.decodeSingularDoubleField(value: &_storage._singleDouble) }()
        case 13: try { try decoder.decodeSingularBoolField(value: &_storage._singleBool) }()
        case 14: try { try decoder.decodeSingularStringField(value: &_storage._singleString) }()
        case 15: try { try decoder.decodeSingularBytesField(value: &_storage._singleBytes) }()
        case 18: try {
          var v: Google_Expr_Proto3_Test_TestAllTypes.NestedMessage?
          var hadOneofValue = false
          if let current = _storage._nestedType {
            hadOneofValue = true
            if case .singleNestedMessage(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._nestedType = .singleNestedMessage(v)
          }
        }()
        case 21: try {
          var v: Google_Expr_Proto3_Test_TestAllTypes.NestedEnum?
          try decoder.decodeSingularEnumField(value: &v)
          if let v = v {
            if _storage._nestedType != nil {try decoder.handleConflictingOneOf()}
            _storage._nestedType = .singleNestedEnum(v)
          }
        }()
        case 22: try { try decoder.decodeSingularEnumField(value: &_storage._standaloneEnum) }()
        case 31: try { try decoder.decodeRepeatedInt32Field(value: &_storage._repeatedInt32) }()
        case 32: try { try decoder.decodeRepeatedInt64Field(value: &_storage._repeatedInt64) }()
        case 33: try { try decoder.decodeRepeatedUInt32Field(value: &_storage._repeatedUint32) }()
        case 34: try { try decoder.decodeRepeatedUInt64Field(value: &_storage._repeatedUint64) }()
        case 35: try { try decoder.decodeRepeatedSInt32Field(value: &_storage._repeatedSint32) }()
        case 36: try { try decoder.decodeRepeatedSInt64Field(value: &_storage._repeatedSint64) }()
        case 37: try { try decoder.decodeRepeatedFixed32Field(value: &_storage._repeatedFixed32) }()
        case 38: try { try decoder.decodeRepeatedFixed64Field(value: &_storage._repeatedFixed64) }()
        case 39: try { try decoder.decodeRepeatedSFixed32Field(value: &_storage._repeatedSfixed32) }()
        case 40: try { try decoder.decodeRepeatedSFixed64Field(value: &_storage._repeatedSfixed64) }()
        case 41: try { try decoder.decodeRepeatedFloatField(value: &_storage._repeatedFloat) }()
        case 42: try { try decoder.decodeRepeatedDoubleField(value: &_storage._repeatedDouble) }()
        case 43: try { try decoder.decodeRepeatedBoolField(value: &_storage._repeatedBool) }()
        case 44: try { try decoder.decodeRepeatedStringField(value: &_storage._repeatedString) }()
        case 45: try { try decoder.decodeRepeatedBytesField(value: &_storage._repeatedBytes) }()
        case 48: try { try decoder.decodeRepeatedMessageField(value: &_storage._repeatedNestedMessage) }()
        case 51: try { try decoder.decodeRepeatedEnumField(value: &_storage._repeatedNestedEnum) }()
        case 54: try { try decoder.decodeRepeatedStringField(value: &_storage._repeatedStringPiece) }()
        case 55: try { try decoder.decodeRepeatedStringField(value: &_storage._repeatedCord) }()
        case 57: try { try decoder.decodeRepeatedMessageField(value: &_storage._repeatedLazyMessage) }()
        case 58: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &_storage._mapStringString) }()
        case 59: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufInt64,Google_Expr_Proto3_Test_NestedTestAllTypes>.self, value: &_storage._mapInt64NestedType) }()
        case 60: try { try decoder.decodeRepeatedEnumField(value: &_storage._importedEnums) }()
        case 100: try { try decoder.decodeSingularMessageField(value: &_storage._singleAny) }()
        case 101: try { try decoder.decodeSingularMessageField(value: &_storage._singleDuration) }()
        case 102: try { try decoder.decodeSingularMessageField(value: &_storage._singleTimestamp) }()
        case 103: try { try decoder.decodeSingularMessageField(value: &_storage._singleStruct) }()
        case 104: try { try decoder.decodeSingularMessageField(value: &_storage._singleValue) }()
        case 105: try { try decoder.decodeSingularMessageField(value: &_storage._singleInt64Wrapper) }()
        case 106: try { try decoder.decodeSingularMessageField(value: &_storage._singleInt32Wrapper) }()
        case 107: try { try decoder.decodeSingularMessageField(value: &_storage._singleDoubleWrapper) }()
        case 108: try { try decoder.decodeSingularMessageField(value: &_storage._singleFloatWrapper) }()
        case 109: try { try decoder.decodeSingularMessageField(value: &_storage._singleUint64Wrapper) }()
        case 110: try { try decoder.decodeSingularMessageField(value: &_storage._singleUint32Wrapper) }()
        case 111: try { try decoder.decodeSingularMessageField(value: &_storage._singleStringWrapper) }()
        case 112: try { try decoder.decodeSingularMessageField(value: &_storage._singleBoolWrapper) }()
        case 113: try { try decoder.decodeSingularMessageField(value: &_storage._singleBytesWrapper) }()
        default: break
        }
      }
    }
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if _storage._singleInt32 != 0 {
        try visitor.visitSingularInt32Field(value: _storage._singleInt32, fieldNumber: 1)
      }
      if _storage._singleInt64 != 0 {
        try visitor.visitSingularInt64Field(value: _storage._singleInt64, fieldNumber: 2)
      }
      if _storage._singleUint32 != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._singleUint32, fieldNumber: 3)
      }
      if _storage._singleUint64 != 0 {
        try visitor.visitSingularUInt64Field(value: _storage._singleUint64, fieldNumber: 4)
      }
      if _storage._singleSint32 != 0 {
        try visitor.visitSingularSInt32Field(value: _storage._singleSint32, fieldNumber: 5)
      }
      if _storage._singleSint64 != 0 {
        try visitor.visitSingularSInt64Field(value: _storage._singleSint64, fieldNumber: 6)
      }
      if _storage._singleFixed32 != 0 {
        try visitor.visitSingularFixed32Field(value: _storage._singleFixed32, fieldNumber: 7)
      }
      if _storage._singleFixed64 != 0 {
        try visitor.visitSingularFixed64Field(value: _storage._singleFixed64, fieldNumber: 8)
      }
      if _storage._singleSfixed32 != 0 {
        try visitor.visitSingularSFixed32Field(value: _storage._singleSfixed32, fieldNumber: 9)
      }
      if _storage._singleSfixed64 != 0 {
        try visitor.visitSingularSFixed64Field(value: _storage._singleSfixed64, fieldNumber: 10)
      }
      if _storage._singleFloat.bitPattern != 0 {
        try visitor.visitSingularFloatField(value: _storage._singleFloat, fieldNumber: 11)
      }
      if _storage._singleDouble.bitPattern != 0 {
        try visitor.visitSingularDoubleField(value: _storage._singleDouble, fieldNumber: 12)
      }
      if _storage._singleBool != false {
        try visitor.visitSingularBoolField(value: _storage._singleBool, fieldNumber: 13)
      }
      if !_storage._singleString.isEmpty {
        try visitor.visitSingularStringField(value: _storage._singleString, fieldNumber: 14)
      }
      if !_storage._singleBytes.isEmpty {
        try visitor.visitSingularBytesField(value: _storage._singleBytes, fieldNumber: 15)
      }
      switch _storage._nestedType {
      case .singleNestedMessage?: try {
        guard case .singleNestedMessage(let v)? = _storage._nestedType else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 18)
      }()
      case .singleNestedEnum?: try {
        guard case .singleNestedEnum(let v)? = _storage._nestedType else { preconditionFailure() }
        try visitor.visitSingularEnumField(value: v, fieldNumber: 21)
      }()
      case nil: break
      }
      if _storage._standaloneEnum != .foo {
        try visitor.visitSingularEnumField(value: _storage._standaloneEnum, fieldNumber: 22)
      }
      if !_storage._repeatedInt32.isEmpty {
        try visitor.visitPackedInt32Field(value: _storage._repeatedInt32, fieldNumber: 31)
      }
      if !_storage._repeatedInt64.isEmpty {
        try visitor.visitPackedInt64Field(value: _storage._repeatedInt64, fieldNumber: 32)
      }
      if !_storage._repeatedUint32.isEmpty {
        try visitor.visitPackedUInt32Field(value: _storage._repeatedUint32, fieldNumber: 33)
      }
      if !_storage._repeatedUint64.isEmpty {
        try visitor.visitPackedUInt64Field(value: _storage._repeatedUint64, fieldNumber: 34)
      }
      if !_storage._repeatedSint32.isEmpty {
        try visitor.visitPackedSInt32Field(value: _storage._repeatedSint32, fieldNumber: 35)
      }
      if !_storage._repeatedSint64.isEmpty {
        try visitor.visitPackedSInt64Field(value: _storage._repeatedSint64, fieldNumber: 36)
      }
      if !_storage._repeatedFixed32.isEmpty {
        try visitor.visitPackedFixed32Field(value: _storage._repeatedFixed32, fieldNumber: 37)
      }
      if !_storage._repeatedFixed64.isEmpty {
        try visitor.visitPackedFixed64Field(value: _storage._repeatedFixed64, fieldNumber: 38)
      }
      if !_storage._repeatedSfixed32.isEmpty {
        try visitor.visitPackedSFixed32Field(value: _storage._repeatedSfixed32, fieldNumber: 39)
      }
      if !_storage._repeatedSfixed64.isEmpty {
        try visitor.visitPackedSFixed64Field(value: _storage._repeatedSfixed64, fieldNumber: 40)
      }
      if !_storage._repeatedFloat.isEmpty {
        try visitor.visitPackedFloatField(value: _storage._repeatedFloat, fieldNumber: 41)
      }
      if !_storage._repeatedDouble.isEmpty {
        try visitor.visitPackedDoubleField(value: _storage._repeatedDouble, fieldNumber: 42)
      }
      if !_storage._repeatedBool.isEmpty {
        try visitor.visitPackedBoolField(value: _storage._repeatedBool, fieldNumber: 43)
      }
      if !_storage._repeatedString.isEmpty {
        try visitor.visitRepeatedStringField(value: _storage._repeatedString, fieldNumber: 44)
      }
      if !_storage._repeatedBytes.isEmpty {
        try visitor.visitRepeatedBytesField(value: _storage._repeatedBytes, fieldNumber: 45)
      }
      if !_storage._repeatedNestedMessage.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._repeatedNestedMessage, fieldNumber: 48)
      }
      if !_storage._repeatedNestedEnum.isEmpty {
        try visitor.visitPackedEnumField(value: _storage._repeatedNestedEnum, fieldNumber: 51)
      }
      if !_storage._repeatedStringPiece.isEmpty {
        try visitor.visitRepeatedStringField(value: _storage._repeatedStringPiece, fieldNumber: 54)
      }
      if !_storage._repeatedCord.isEmpty {
        try visitor.visitRepeatedStringField(value: _storage._repeatedCord, fieldNumber: 55)
      }
      if !_storage._repeatedLazyMessage.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._repeatedLazyMessage, fieldNumber: 57)
      }
      if !_storage._mapStringString.isEmpty {
        try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: _storage._mapStringString, fieldNumber: 58)
      }
      if !_storage._mapInt64NestedType.isEmpty {
        try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufInt64,Google_Expr_Proto3_Test_NestedTestAllTypes>.self, value: _storage._mapInt64NestedType, fieldNumber: 59)
      }
      if !_storage._importedEnums.isEmpty {
        try visitor.visitPackedEnumField(value: _storage._importedEnums, fieldNumber: 60)
      }
      try { if let v = _storage._singleAny {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 100)
      } }()
      try { if let v = _storage._singleDuration {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 101)
      } }()
      try { if let v = _storage._singleTimestamp {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 102)
      } }()
      try { if let v = _storage._singleStruct {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 103)
      } }()
      try { if let v = _storage._singleValue {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 104)
      } }()
      try { if let v = _storage._singleInt64Wrapper {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 105)
      } }()
      try { if let v = _storage._singleInt32Wrapper {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 106)
      } }()
      try { if let v = _storage._singleDoubleWrapper {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 107)
      } }()
      try { if let v = _storage._singleFloatWrapper {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 108)
      } }()
      try { if let v = _storage._singleUint64Wrapper {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 109)
      } }()
      try { if let v = _storage._singleUint32Wrapper {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 110)
      } }()
      try { if let v = _storage._singleStringWrapper {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 111)
      } }()
      try { if let v = _storage._singleBoolWrapper {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 112)
      } }()
      try { if let v = _storage._singleBytesWrapper {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 113)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Google_Expr_Proto3_Test_TestAllTypes, rhs: Google_Expr_Proto3_Test_TestAllTypes) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._singleInt32 != rhs_storage._singleInt32 {return false}
        if _storage._singleInt64 != rhs_storage._singleInt64 {return false}
        if _storage._singleUint32 != rhs_storage._singleUint32 {return false}
        if _storage._singleUint64 != rhs_storage._singleUint64 {return false}
        if _storage._singleSint32 != rhs_storage._singleSint32 {return false}
        if _storage._singleSint64 != rhs_storage._singleSint64 {return false}
        if _storage._singleFixed32 != rhs_storage._singleFixed32 {return false}
        if _storage._singleFixed64 != rhs_storage._singleFixed64 {return false}
        if _storage._singleSfixed32 != rhs_storage._singleSfixed32 {return false}
        if _storage._singleSfixed64 != rhs_storage._singleSfixed64 {return false}
        if _storage._singleFloat != rhs_storage._singleFloat {return false}
        if _storage._singleDouble != rhs_storage._singleDouble {return false}
        if _storage._singleBool != rhs_storage._singleBool {return false}
        if _storage._singleString != rhs_storage._singleString {return false}
        if _storage._singleBytes != rhs_storage._singleBytes {return false}
        if _storage._standaloneEnum != rhs_storage._standaloneEnum {return false}
        if _storage._singleAny != rhs_storage._singleAny {return false}
        if _storage._singleDuration != rhs_storage._singleDuration {return false}
        if _storage._singleTimestamp != rhs_storage._singleTimestamp {return false}
        if _storage._singleStruct != rhs_storage._singleStruct {return false}
        if _storage._singleValue != rhs_storage._singleValue {return false}
        if _storage._singleInt64Wrapper != rhs_storage._singleInt64Wrapper {return false}
        if _storage._singleInt32Wrapper != rhs_storage._singleInt32Wrapper {return false}
        if _storage._singleDoubleWrapper != rhs_storage._singleDoubleWrapper {return false}
        if _storage._singleFloatWrapper != rhs_storage._singleFloatWrapper {return false}
        if _storage._singleUint64Wrapper != rhs_storage._singleUint64Wrapper {return false}
        if _storage._singleUint32Wrapper != rhs_storage._singleUint32Wrapper {return false}
        if _storage._singleStringWrapper != rhs_storage._singleStringWrapper {return false}
        if _storage._singleBoolWrapper != rhs_storage._singleBoolWrapper {return false}
        if _storage._singleBytesWrapper != rhs_storage._singleBytesWrapper {return false}
        if _storage._nestedType != rhs_storage._nestedType {return false}
        if _storage._repeatedInt32 != rhs_storage._repeatedInt32 {return false}
        if _storage._repeatedInt64 != rhs_storage._repeatedInt64 {return false}
        if _storage._repeatedUint32 != rhs_storage._repeatedUint32 {return false}
        if _storage._repeatedUint64 != rhs_storage._repeatedUint64 {return false}
        if _storage._repeatedSint32 != rhs_storage._repeatedSint32 {return false}
        if _storage._repeatedSint64 != rhs_storage._repeatedSint64 {return false}
        if _storage._repeatedFixed32 != rhs_storage._repeatedFixed32 {return false}
        if _storage._repeatedFixed64 != rhs_storage._repeatedFixed64 {return false}
        if _storage._repeatedSfixed32 != rhs_storage._repeatedSfixed32 {return false}
        if _storage._repeatedSfixed64 != rhs_storage._repeatedSfixed64 {return false}
        if _storage._repeatedFloat != rhs_storage._repeatedFloat {return false}
        if _storage._repeatedDouble != rhs_storage._repeatedDouble {return false}
        if _storage._repeatedBool != rhs_storage._repeatedBool {return false}
        if _storage._repeatedString != rhs_storage._repeatedString {return false}
        if _storage._repeatedBytes != rhs_storage._repeatedBytes {return false}
        if _storage._repeatedNestedMessage != rhs_storage._repeatedNestedMessage {return false}
        if _storage._repeatedNestedEnum != rhs_storage._repeatedNestedEnum {return false}
        if _storage._repeatedStringPiece != rhs_storage._repeatedStringPiece {return false}
        if _storage._repeatedCord != rhs_storage._repeatedCord {return false}
        if _storage._repeatedLazyMessage != rhs_storage._repeatedLazyMessage {return false}
        if _storage._mapStringString != rhs_storage._mapStringString {return false}
        if _storage._mapInt64NestedType != rhs_storage._mapInt64NestedType {return false}
        if _storage._importedEnums != rhs_storage._importedEnums {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Google_Expr_Proto3_Test_TestAllTypes.NestedEnum: SwiftProtobuf._ProtoNameProviding {
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0FOO\0\u{1}BAR\0\u{1}BAZ\0")
}

extension Google_Expr_Proto3_Test_TestAllTypes.NestedMessage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = Google_Expr_Proto3_Test_TestAllTypes.protoMessageName + ".NestedMessage"
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}bb\0")

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.bb) }()
      default: break
      }
    }
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.bb != 0 {
      try visitor.visitSingularInt32Field(value: self.bb, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Google_Expr_Proto3_Test_TestAllTypes.NestedMessage, rhs: Google_Expr_Proto3_Test_TestAllTypes.NestedMessage) -> Bool {
    if lhs.bb != rhs.bb {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Google_Expr_Proto3_Test_NestedTestAllTypes: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = _protobuf_package + ".NestedTestAllTypes"
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}child\0\u{1}payload\0")

  fileprivate class _StorageClass {
    var _child: Google_Expr_Proto3_Test_NestedTestAllTypes? = nil
    var _payload: Google_Expr_Proto3_Test_TestAllTypes? = nil

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _child = source._child
      _payload = source._payload
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularMessageField(value: &_storage._child) }()
        case 2: try { try decoder.decodeSingularMessageField(value: &_storage._payload) }()
        default: break
        }
      }
    }
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      try { if let v = _storage._child {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      } }()
      try { if let v = _storage._payload {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Google_Expr_Proto3_Test_NestedTestAllTypes, rhs: Google_Expr_Proto3_Test_NestedTestAllTypes) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._child != rhs_storage._child {return false}
        if _storage._payload != rhs_storage._payload {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Google_Expr_Proto3_Test_TestJsonNames: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = _protobuf_package + ".TestJsonNames"
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}int32_snake_case_json_name\0\u{3}int64_camel_case_json_name\0\u{3}uint32_default_json_name\0\u{5}uint64_custom_json_name\0uint64-custom-json-name\0\u{5}string_json_name_shadows\0single_string\0\u{3}single_string\0")

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.int32SnakeCaseJsonName) }()
      case 2: try { try decoder.decodeSingularInt64Field(value: &self.int64CamelCaseJsonName) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.uint32DefaultJsonName) }()
      case 4: try { try decoder.decodeSingularUInt64Field(value: &self.uint64CustomJsonName) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.stringJsonNameShadows) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.singleString) }()
      default: break
      }
    }
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.int32SnakeCaseJsonName != 0 {
      try visitor.visitSingularInt32Field(value: self.int32SnakeCaseJsonName, fieldNumber: 1)
    }
    if self.int64CamelCaseJsonName != 0 {
      try visitor.visitSingularInt64Field(value: self.int64CamelCaseJsonName, fieldNumber: 2)
    }
    if self.uint32DefaultJsonName != 0 {
      try visitor.visitSingularUInt32Field(value: self.uint32DefaultJsonName, fieldNumber: 3)
    }
    if self.uint64CustomJsonName != 0 {
      try visitor.visitSingularUInt64Field(value: self.uint64CustomJsonName, fieldNumber: 4)
    }
    if !self.stringJsonNameShadows.isEmpty {
      try visitor.visitSingularStringField(value: self.stringJsonNameShadows, fieldNumber: 5)
    }
    if !self.singleString.isEmpty {
      try visitor.visitSingularStringField(value: self.singleString, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Google_Expr_Proto3_Test_TestJsonNames, rhs: Google_Expr_Proto3_Test_TestJsonNames) -> Bool {
    if lhs.int32SnakeCaseJsonName != rhs.int32SnakeCaseJsonName {return false}
    if lhs.int64CamelCaseJsonName != rhs.int64CamelCaseJsonName {return false}
    if lhs.uint32DefaultJsonName != rhs.uint32DefaultJsonName {return false}
    if lhs.uint64CustomJsonName != rhs.uint64CustomJsonName {return false}
    if lhs.stringJsonNameShadows != rhs.stringJsonNameShadows {return false}
    if lhs.singleString != rhs.singleString {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
