// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: test/proto2pb/test_extensions.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Message scoped extensions.
package struct Google_Expr_Proto2_Test_ExternalMessageType: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  package var unknownFields = SwiftProtobuf.UnknownStorage()

  package init() {}
}

// MARK: - Extension support defined in test_extensions.proto.

// MARK: - Extension Properties

// Swift Extensions on the extended Messages to add easy access to the declared
// extension fields. The names are based on the extension field name from the proto
// declaration. To avoid naming collisions, the names are prefixed with the name of
// the scope where the extend directive occurs.

extension Google_Expr_Proto2_Test_ExampleType {

  package var Google_Expr_Proto2_Test_nestedExample: Google_Expr_Proto2_Test_ExampleType {
    get {return getExtensionValue(ext: Google_Expr_Proto2_Test_Extensions_nested_example) ?? Google_Expr_Proto2_Test_ExampleType()}
    set {setExtensionValue(ext: Google_Expr_Proto2_Test_Extensions_nested_example, value: newValue)}
  }
  /// Returns true if extension `Google_Expr_Proto2_Test_Extensions_nested_example`
  /// has been explicitly set.
  package var hasGoogle_Expr_Proto2_Test_nestedExample: Bool {
    return hasExtensionValue(ext: Google_Expr_Proto2_Test_Extensions_nested_example)
  }
  /// Clears the value of extension `Google_Expr_Proto2_Test_Extensions_nested_example`.
  /// Subsequent reads from it will return its default value.
  package mutating func clearGoogle_Expr_Proto2_Test_nestedExample() {
    clearExtensionValue(ext: Google_Expr_Proto2_Test_Extensions_nested_example)
  }

  package var Google_Expr_Proto2_Test_int32Ext: Int32 {
    get {return getExtensionValue(ext: Google_Expr_Proto2_Test_Extensions_int32_ext) ?? 0}
    set {setExtensionValue(ext: Google_Expr_Proto2_Test_Extensions_int32_ext, value: newValue)}
  }
  /// Returns true if extension `Google_Expr_Proto2_Test_Extensions_int32_ext`
  /// has been explicitly set.
  package var hasGoogle_Expr_Proto2_Test_int32Ext: Bool {
    return hasExtensionValue(ext: Google_Expr_Proto2_Test_Extensions_int32_ext)
  }
  /// Clears the value of extension `Google_Expr_Proto2_Test_Extensions_int32_ext`.
  /// Subsequent reads from it will return its default value.
  package mutating func clearGoogle_Expr_Proto2_Test_int32Ext() {
    clearExtensionValue(ext: Google_Expr_Proto2_Test_Extensions_int32_ext)
  }

  package var Google_Expr_Proto2_Test_int32WrapperExt: SwiftProtobuf.Google_Protobuf_Int32Value {
    get {return getExtensionValue(ext: Google_Expr_Proto2_Test_Extensions_int32_wrapper_ext) ?? SwiftProtobuf.Google_Protobuf_Int32Value()}
    set {setExtensionValue(ext: Google_Expr_Proto2_Test_Extensions_int32_wrapper_ext, value: newValue)}
  }
  /// Returns true if extension `Google_Expr_Proto2_Test_Extensions_int32_wrapper_ext`
  /// has been explicitly set.
  package var hasGoogle_Expr_Proto2_Test_int32WrapperExt: Bool {
    return hasExtensionValue(ext: Google_Expr_Proto2_Test_Extensions_int32_wrapper_ext)
  }
  /// Clears the value of extension `Google_Expr_Proto2_Test_Extensions_int32_wrapper_ext`.
  /// Subsequent reads from it will return its default value.
  package mutating func clearGoogle_Expr_Proto2_Test_int32WrapperExt() {
    clearExtensionValue(ext: Google_Expr_Proto2_Test_Extensions_int32_wrapper_ext)
  }

  package var Google_Expr_Proto2_Test_ExternalMessageType_int64Ext: Int64 {
    get {return getExtensionValue(ext: Google_Expr_Proto2_Test_ExternalMessageType.Extensions.int64_ext) ?? 0}
    set {setExtensionValue(ext: Google_Expr_Proto2_Test_ExternalMessageType.Extensions.int64_ext, value: newValue)}
  }
  /// Returns true if extension `Google_Expr_Proto2_Test_ExternalMessageType.Extensions.int64_ext`
  /// has been explicitly set.
  package var hasGoogle_Expr_Proto2_Test_ExternalMessageType_int64Ext: Bool {
    return hasExtensionValue(ext: Google_Expr_Proto2_Test_ExternalMessageType.Extensions.int64_ext)
  }
  /// Clears the value of extension `Google_Expr_Proto2_Test_ExternalMessageType.Extensions.int64_ext`.
  /// Subsequent reads from it will return its default value.
  package mutating func clearGoogle_Expr_Proto2_Test_ExternalMessageType_int64Ext() {
    clearExtensionValue(ext: Google_Expr_Proto2_Test_ExternalMessageType.Extensions.int64_ext)
  }

}

// MARK: - File's ExtensionMap: Google_Expr_Proto2_Test_TestExtensions_Extensions

/// A `SwiftProtobuf.SimpleExtensionMap` that includes all of the extensions defined by
/// this .proto file. It can be used any place an `SwiftProtobuf.ExtensionMap` is needed
/// in parsing, or it can be combined with other `SwiftProtobuf.SimpleExtensionMap`s to create
/// a larger `SwiftProtobuf.SimpleExtensionMap`.
package let Google_Expr_Proto2_Test_TestExtensions_Extensions: SwiftProtobuf.SimpleExtensionMap = [
  Google_Expr_Proto2_Test_Extensions_nested_example,
  Google_Expr_Proto2_Test_Extensions_int32_ext,
  Google_Expr_Proto2_Test_Extensions_int32_wrapper_ext,
  Google_Expr_Proto2_Test_ExternalMessageType.Extensions.int64_ext
]

// Extension Objects - The only reason these might be needed is when manually
// constructing a `SimpleExtensionMap`, otherwise, use the above _Extension Properties_
// accessors for the extension fields on the messages directly.

package let Google_Expr_Proto2_Test_Extensions_nested_example = SwiftProtobuf.MessageExtension<SwiftProtobuf.OptionalMessageExtensionField<Google_Expr_Proto2_Test_ExampleType>, Google_Expr_Proto2_Test_ExampleType>(
  _protobuf_fieldNumber: 100,
  fieldName: "google.expr.proto2.test.nested_example"
)

package let Google_Expr_Proto2_Test_Extensions_int32_ext = SwiftProtobuf.MessageExtension<SwiftProtobuf.OptionalExtensionField<SwiftProtobuf.ProtobufInt32>, Google_Expr_Proto2_Test_ExampleType>(
  _protobuf_fieldNumber: 101,
  fieldName: "google.expr.proto2.test.int32_ext"
)

package let Google_Expr_Proto2_Test_Extensions_int32_wrapper_ext = SwiftProtobuf.MessageExtension<SwiftProtobuf.OptionalMessageExtensionField<SwiftProtobuf.Google_Protobuf_Int32Value>, Google_Expr_Proto2_Test_ExampleType>(
  _protobuf_fieldNumber: 102,
  fieldName: "google.expr.proto2.test.int32_wrapper_ext"
)

extension Google_Expr_Proto2_Test_ExternalMessageType {
  package enum Extensions {
    package static let int64_ext = SwiftProtobuf.MessageExtension<SwiftProtobuf.OptionalExtensionField<SwiftProtobuf.ProtobufInt64>, Google_Expr_Proto2_Test_ExampleType>(
      _protobuf_fieldNumber: 201,
      fieldName: "google.expr.proto2.test.ExternalMessageType.int64_ext"
    )
  }
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "google.expr.proto2.test"

extension Google_Expr_Proto2_Test_ExternalMessageType: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = _protobuf_package + ".ExternalMessageType"
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Google_Expr_Proto2_Test_ExternalMessageType, rhs: Google_Expr_Proto2_Test_ExternalMessageType) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
