// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by protoc-gen-cel-swift.
// Source: test/proto2pb/test_extensions.proto

import CEL
import CELProtobuf
import SwiftProtobuf

/// The CEL description of `test/proto2pb/test_extensions.proto`, for `ProtobufTypes`.
package let Google_Expr_Proto2_Test_TestExtensions_CELFile = ProtobufFile(
  path: "test/proto2pb/test_extensions.proto",
  messageTypes: [
    ProtobufMessageType(Google_Expr_Proto2_Test_ExternalMessageType.self, fields: _celFields_Google_Expr_Proto2_Test_ExternalMessageType()),
  ],
  enumTypes: [
  ],
  extensions: [
    ProtobufExtension(ProtobufField<Google_Expr_Proto2_Test_ExampleType>.singular("google.expr.proto2.test.nested_example", number: 100, \Google_Expr_Proto2_Test_ExampleType.Google_Expr_Proto2_Test_nestedExample, .message, presence: .explicit(\Google_Expr_Proto2_Test_ExampleType.hasGoogle_Expr_Proto2_Test_nestedExample))),
    ProtobufExtension(ProtobufField<Google_Expr_Proto2_Test_ExampleType>.singular("google.expr.proto2.test.int32_ext", number: 101, \Google_Expr_Proto2_Test_ExampleType.Google_Expr_Proto2_Test_int32Ext, .int32, presence: .explicit(\Google_Expr_Proto2_Test_ExampleType.hasGoogle_Expr_Proto2_Test_int32Ext))),
    ProtobufExtension(ProtobufField<Google_Expr_Proto2_Test_ExampleType>.singular("google.expr.proto2.test.int32_wrapper_ext", number: 102, \Google_Expr_Proto2_Test_ExampleType.Google_Expr_Proto2_Test_int32WrapperExt, .message, presence: .explicit(\Google_Expr_Proto2_Test_ExampleType.hasGoogle_Expr_Proto2_Test_int32WrapperExt))),
    ProtobufExtension(ProtobufField<Google_Expr_Proto2_Test_ExampleType>.singular("google.expr.proto2.test.ExternalMessageType.int64_ext", number: 201, \Google_Expr_Proto2_Test_ExampleType.Google_Expr_Proto2_Test_ExternalMessageType_int64Ext, .int64, presence: .explicit(\Google_Expr_Proto2_Test_ExampleType.hasGoogle_Expr_Proto2_Test_ExternalMessageType_int64Ext))),
  ],
  extensionMap: Google_Expr_Proto2_Test_TestExtensions_Extensions,
  dependencies: [Google_Expr_Proto2_Test_TestAllTypes_CELFile]
)

fileprivate func _celFields_Google_Expr_Proto2_Test_ExternalMessageType() -> [ProtobufField<Google_Expr_Proto2_Test_ExternalMessageType>] {
  []
}
