// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by protoc-gen-cel-swift.
// Source: test/proto2pb/test_all_types.proto

import CEL
import CELProtobuf
import SwiftProtobuf

/// The CEL description of `test/proto2pb/test_all_types.proto`, for `ProtobufTypes`.
package let Google_Expr_Proto2_Test_TestAllTypes_CELFile = ProtobufFile(
  path: "test/proto2pb/test_all_types.proto",
  messageTypes: [
    ProtobufMessageType(Google_Expr_Proto2_Test_TestAllTypes.self, fields: _celFields_Google_Expr_Proto2_Test_TestAllTypes()),
    ProtobufMessageType(Google_Expr_Proto2_Test_TestAllTypes.NestedMessage.self, fields: _celFields_Google_Expr_Proto2_Test_TestAllTypes_NestedMessage()),
    ProtobufMessageType(Google_Expr_Proto2_Test_TestAllTypes.NestedGroup.self, fields: _celFields_Google_Expr_Proto2_Test_TestAllTypes_NestedGroup()),
    ProtobufMessageType(Google_Expr_Proto2_Test_NestedTestAllTypes.self, fields: _celFields_Google_Expr_Proto2_Test_NestedTestAllTypes()),
    ProtobufMessageType(Google_Expr_Proto2_Test_ExampleType.self, fields: _celFields_Google_Expr_Proto2_Test_ExampleType()),
    ProtobufMessageType(Google_Expr_Proto2_Test_ExtendedExampleType.self, fields: _celFields_Google_Expr_Proto2_Test_ExtendedExampleType()),
  ],
  enumTypes: [
    ProtobufEnumType("google.expr.proto2.test.GlobalEnum", values: [("GOO", 0), ("GAR", 1), ("GAZ", 2)]),
    ProtobufEnumType("google.expr.proto2.test.TestAllTypes.NestedEnum", values: [("FOO", 0), ("BAR", 1), ("BAZ", 2)]),
  ],
  extensions: [
    ProtobufExtension(ProtobufField<Google_Expr_Proto2_Test_ExampleType>.repeated("google.expr.proto2.test.ExtendedExampleType.extended_examples", number: 103, \Google_Expr_Proto2_Test_ExampleType.Google_Expr_Proto2_Test_ExtendedExampleType_extendedExamples, .string)),
    ProtobufExtension(ProtobufField<Google_Expr_Proto2_Test_ExampleType>.singular("google.expr.proto2.test.ExtendedExampleType.enum_ext", number: 104, \Google_Expr_Proto2_Test_ExampleType.Google_Expr_Proto2_Test_ExtendedExampleType_enumExt, .enumeration, presence: .explicit(\Google_Expr_Proto2_Test_ExampleType.hasGoogle_Expr_Proto2_Test_ExtendedExampleType_enumExt))),
  ],
  extensionMap: Google_Expr_Proto2_Test_TestAllTypes_Extensions,
  dependencies: []
)

fileprivate func _celFields_Google_Expr_Proto2_Test_TestAllTypes() -> [ProtobufField<Google_Expr_Proto2_Test_TestAllTypes>] {
  var fields: [ProtobufField<Google_Expr_Proto2_Test_TestAllTypes>] = []
  fields.reserveCapacity(55)
  fields.append(.singular("single_int32", number: 1, \Google_Expr_Proto2_Test_TestAllTypes.singleInt32, .int32, presence: .explicit(\Google_Expr_Proto2_Test_TestAllTypes.hasSingleInt32)))
  fields.append(.singular("single_int64", number: 2, \Google_Expr_Proto2_Test_TestAllTypes.singleInt64, .int64, presence: .explicit(\Google_Expr_Proto2_Test_TestAllTypes.hasSingleInt64)))
  fields.append(.singular("single_uint32", number: 3, \Google_Expr_Proto2_Test_TestAllTypes.singleUint32, .uint32, presence: .explicit(\Google_Expr_Proto2_Test_TestAllTypes.hasSingleUint32)))
  fields.append(.singular("single_uint64", number: 4, \Google_Expr_Proto2_Test_TestAllTypes.singleUint64, .uint64, presence: .explicit(\Google_Expr_Proto2_Test_TestAllTypes.hasSingleUint64)))
  fields.append(.singular("single_sint32", number: 5, \Google_Expr_Proto2_Test_TestAllTypes.singleSint32, .int32, presence: .explicit(\Google_Expr_Proto2_Test_TestAllTypes.hasSingleSint32)))
  fields.append(.singular("single_sint64", number: 6, \Google_Expr_Proto2_Test_TestAllTypes.singleSint64, .int64, presence: .explicit(\Google_Expr_Proto2_Test_TestAllTypes.hasSingleSint64)))
  fields.append(.singular("single_fixed32", number: 7, \Google_Expr_Proto2_Test_TestAllTypes.singleFixed32, .uint32, presence: .explicit(\Google_Expr_Proto2_Test_TestAllTypes.hasSingleFixed32)))
  fields.append(.singular("single_fixed64", number: 8, \Google_Expr_Proto2_Test_TestAllTypes.singleFixed64, .uint64, presence: .explicit(\Google_Expr_Proto2_Test_TestAllTypes.hasSingleFixed64)))
  fields.append(.singular("single_sfixed32", number: 9, \Google_Expr_Proto2_Test_TestAllTypes.singleSfixed32, .int32, presence: .explicit(\Google_Expr_Proto2_Test_TestAllTypes.hasSingleSfixed32)))
  fields.append(.singular("single_sfixed64", number: 10, \Google_Expr_Proto2_Test_TestAllTypes.singleSfixed64, .int64, presence: .explicit(\Google_Expr_Proto2_Test_TestAllTypes.hasSingleSfixed64)))
  fields.append(.singular("single_float", number: 11, \Google_Expr_Proto2_Test_TestAllTypes.singleFloat, .float, presence: .explicit(\Google_Expr_Proto2_Test_TestAllTypes.hasSingleFloat)))
  fields.append(.singular("single_double", number: 12, \Google_Expr_Proto2_Test_TestAllTypes.singleDouble, .double, presence: .explicit(\Google_Expr_Proto2_Test_TestAllTypes.hasSingleDouble)))
  fields.append(.singular("single_bool", number: 13, \Google_Expr_Proto2_Test_TestAllTypes.singleBool, .bool, presence: .explicit(\Google_Expr_Proto2_Test_TestAllTypes.hasSingleBool)))
  fields.append(.singular("single_string", number: 14, \Google_Expr_Proto2_Test_TestAllTypes.singleString, .string, presence: .explicit(\Google_Expr_Proto2_Test_TestAllTypes.hasSingleString)))
  fields.append(.singular("single_bytes", number: 15, \Google_Expr_Proto2_Test_TestAllTypes.singleBytes, .bytes, presence: .explicit(\Google_Expr_Proto2_Test_TestAllTypes.hasSingleBytes)))
  fields.append(.singular("standalone_enum", number: 22, \Google_Expr_Proto2_Test_TestAllTypes.standaloneEnum, .enumeration, presence: .explicit(\Google_Expr_Proto2_Test_TestAllTypes.hasStandaloneEnum)))
  fields.append(.singular("nestedgroup", number: 23, \Google_Expr_Proto2_Test_TestAllTypes.nestedGroup, .message, presence: .explicit(\Google_Expr_Proto2_Test_TestAllTypes.hasNestedGroup)))
  fields.append(.singular("single_any", number: 100, \Google_Expr_Proto2_Test_TestAllTypes.singleAny, .message, presence: .explicit(\Google_Expr_Proto2_Test_TestAllTypes.hasSingleAny)))
  fields.append(.singular("single_duration", number: 101, \Google_Expr_Proto2_Test_TestAllTypes.singleDuration, .message, presence: .explicit(\Google_Expr_Proto2_Test_TestAllTypes.hasSingleDuration)))
  fields.append(.singular("single_timestamp", number: 102, \Google_Expr_Proto2_Test_TestAllTypes.singleTimestamp, .message, presence: .explicit(\Google_Expr_Proto2_Test_TestAllTypes.hasSingleTimestamp)))
  fields.append(.singular("single_struct", number: 103, \Google_Expr_Proto2_Test_TestAllTypes.singleStruct, .message, presence: .explicit(\Google_Expr_Proto2_Test_TestAllTypes.hasSingleStruct)))
  fields.append(.singular("single_value", number: 104, \Google_Expr_Proto2_Test_TestAllTypes.singleValue, .message, presence: .explicit(\Google_Expr_Proto2_Test_TestAllTypes.hasSingleValue)))
  fields.append(.singular("single_int64_wrapper", number: 105, \Google_Expr_Proto2_Test_TestAllTypes.singleInt64Wrapper, .message, presence: .explicit(\Google_Expr_Proto2_Test_TestAllTypes.hasSingleInt64Wrapper)))
  fields.append(.singular("single_int32_wrapper", number: 106, \Google_Expr_Proto2_Test_TestAllTypes.singleInt32Wrapper, .message, presence: .explicit(\Google_Expr_Proto2_Test_TestAllTypes.hasSingleInt32Wrapper)))
  fields.append(.singular("single_double_wrapper", number: 107, \Google_Expr_Proto2_Test_TestAllTypes.singleDoubleWrapper, .message, presence: .explicit(\Google_Expr_Proto2_Test_TestAllTypes.hasSingleDoubleWrapper)))
  fields.append(.singular("single_float_wrapper", number: 108, \Google_Expr_Proto2_Test_TestAllTypes.singleFloatWrapper, .message, presence: .explicit(\Google_Expr_Proto2_Test_TestAllTypes.hasSingleFloatWrapper)))
  fields.append(.singular("single_uint64_wrapper", number: 109, \Google_Expr_Proto2_Test_TestAllTypes.singleUint64Wrapper, .message, presence: .explicit(\Google_Expr_Proto2_Test_TestAllTypes.hasSingleUint64Wrapper)))
  fields.append(.singular("single_uint32_wrapper", number: 110, \Google_Expr_Proto2_Test_TestAllTypes.singleUint32Wrapper, .message, presence: .explicit(\Google_Expr_Proto2_Test_TestAllTypes.hasSingleUint32Wrapper)))
  fields.append(.singular("single_string_wrapper", number: 111, \Google_Expr_Proto2_Test_TestAllTypes.singleStringWrapper, .message, presence: .explicit(\Google_Expr_Proto2_Test_TestAllTypes.hasSingleStringWrapper)))
  fields.append(.singular("single_bool_wrapper", number: 112, \Google_Expr_Proto2_Test_TestAllTypes.singleBoolWrapper, .message, presence: .explicit(\Google_Expr_Proto2_Test_TestAllTypes.hasSingleBoolWrapper)))
  fields.append(.singular("single_bytes_wrapper", number: 113, \Google_Expr_Proto2_Test_TestAllTypes.singleBytesWrapper, .message, presence: .explicit(\Google_Expr_Proto2_Test_TestAllTypes.hasSingleBytesWrapper)))
  fields.append(.singular("single_nested_message", number: 18, \Google_Expr_Proto2_Test_TestAllTypes.singleNestedMessage, .message, presence: .oneof({ if case .singleNestedMessage? = $0.nestedType { return true }; return false })))
  fields.append(.singular("single_nested_enum", number: 21, \Google_Expr_Proto2_Test_TestAllTypes.singleNestedEnum, .enumeration, presence: .oneof({ if case .singleNestedEnum? = $0.nestedType { return true }; return false })))
  fields.append(.repeated("repeated_int32", number: 31, \Google_Expr_Proto2_Test_TestAllTypes.repeatedInt32, .int32))
  fields.append(.repeated("repeated_int64", number: 32, \Google_Expr_Proto2_Test_TestAllTypes.repeatedInt64, .int64))
  fields.append(.repeated("repeated_uint32", number: 33, \Google_Expr_Proto2_Test_TestAllTypes.repeatedUint32, .uint32))
  fields.append(.repeated("repeated_uint64", number: 34, \Google_Expr_Proto2_Test_TestAllTypes.repeatedUint64, .uint64))
  fields.append(.repeated("repeated_sint32", number: 35, \Google_Expr_Proto2_Test_TestAllTypes.repeatedSint32, .int32))
  fields.append(.repeated("repeated_sint64", number: 36, \Google_Expr_Proto2_Test_TestAllTypes.repeatedSint64, .int64))
  fields.append(.repeated("repeated_fixed32", number: 37, \Google_Expr_Proto2_Test_TestAllTypes.repeatedFixed32, .uint32))
  fields.append(.repeated("repeated_fixed64", number: 38, \Google_Expr_Proto2_Test_TestAllTypes.repeatedFixed64, .uint64))
  fields.append(.repeated("repeated_sfixed32", number: 39, \Google_Expr_Proto2_Test_TestAllTypes.repeatedSfixed32, .int32))
  fields.append(.repeated("repeated_sfixed64", number: 40, \Google_Expr_Proto2_Test_TestAllTypes.repeatedSfixed64, .int64))
  fields.append(.repeated("repeated_float", number: 41, \Google_Expr_Proto2_Test_TestAllTypes.repeatedFloat, .float))
  fields.append(.repeated("repeated_double", number: 42, \Google_Expr_Proto2_Test_TestAllTypes.repeatedDouble, .double))
  fields.append(.repeated("repeated_bool", number: 43, \Google_Expr_Proto2_Test_TestAllTypes.repeatedBool, .bool))
  fields.append(.repeated("repeated_string", number: 44, \Google_Expr_Proto2_Test_TestAllTypes.repeatedString, .string))
  fields.append(.repeated("repeated_bytes", number: 45, \Google_Expr_Proto2_Test_TestAllTypes.repeatedBytes, .bytes))
  fields.append(.repeated("repeated_nested_message", number: 48, \Google_Expr_Proto2_Test_TestAllTypes.repeatedNestedMessage, .message))
  fields.append(.repeated("repeated_nested_enum", number: 51, \Google_Expr_Proto2_Test_TestAllTypes.repeatedNestedEnum, .enumeration))
  fields.append(.repeated("repeated_string_piece", number: 54, \Google_Expr_Proto2_Test_TestAllTypes.repeatedStringPiece, .string))
  fields.append(.repeated("repeated_cord", number: 55, \Google_Expr_Proto2_Test_TestAllTypes.repeatedCord, .string))
  fields.append(.repeated("repeated_lazy_message", number: 57, \Google_Expr_Proto2_Test_TestAllTypes.repeatedLazyMessage, .message))
  fields.append(.map("map_string_string", number: 58, \Google_Expr_Proto2_Test_TestAllTypes.mapStringString, key: .string, value: .string))
  fields.append(.map("map_int64_nested_type", number: 59, \Google_Expr_Proto2_Test_TestAllTypes.mapInt64NestedType, key: .int64, value: .message))
  return fields
}

fileprivate func _celFields_Google_Expr_Proto2_Test_TestAllTypes_NestedMessage() -> [ProtobufField<Google_Expr_Proto2_Test_TestAllTypes.NestedMessage>] {
  var fields: [ProtobufField<Google_Expr_Proto2_Test_TestAllTypes.NestedMessage>] = []
  fields.reserveCapacity(1)
  fields.append(.singular("bb", number: 1, \Google_Expr_Proto2_Test_TestAllTypes.NestedMessage.bb, .int32, presence: .explicit(\Google_Expr_Proto2_Test_TestAllTypes.NestedMessage.hasBb)))
  return fields
}

fileprivate func _celFields_Google_Expr_Proto2_Test_TestAllTypes_NestedGroup() -> [ProtobufField<Google_Expr_Proto2_Test_TestAllTypes.NestedGroup>] {
  var fields: [ProtobufField<Google_Expr_Proto2_Test_TestAllTypes.NestedGroup>] = []
  fields.reserveCapacity(2)
  fields.append(.singular("nested_id", number: 24, \Google_Expr_Proto2_Test_TestAllTypes.NestedGroup.nestedID, .int32, presence: .explicit(\Google_Expr_Proto2_Test_TestAllTypes.NestedGroup.hasNestedID)))
  fields.append(.singular("nested_name", number: 25, \Google_Expr_Proto2_Test_TestAllTypes.NestedGroup.nestedName, .string, presence: .explicit(\Google_Expr_Proto2_Test_TestAllTypes.NestedGroup.hasNestedName)))
  return fields
}

fileprivate func _celFields_Google_Expr_Proto2_Test_NestedTestAllTypes() -> [ProtobufField<Google_Expr_Proto2_Test_NestedTestAllTypes>] {
  var fields: [ProtobufField<Google_Expr_Proto2_Test_NestedTestAllTypes>] = []
  fields.reserveCapacity(2)
  fields.append(.singular("child", number: 1, \Google_Expr_Proto2_Test_NestedTestAllTypes.child, .message, presence: .explicit(\Google_Expr_Proto2_Test_NestedTestAllTypes.hasChild)))
  fields.append(.singular("payload", number: 2, \Google_Expr_Proto2_Test_NestedTestAllTypes.payload, .message, presence: .explicit(\Google_Expr_Proto2_Test_NestedTestAllTypes.hasPayload)))
  return fields
}

fileprivate func _celFields_Google_Expr_Proto2_Test_ExampleType() -> [ProtobufField<Google_Expr_Proto2_Test_ExampleType>] {
  var fields: [ProtobufField<Google_Expr_Proto2_Test_ExampleType>] = []
  fields.reserveCapacity(3)
  fields.append(.singular("name", number: 1, \Google_Expr_Proto2_Test_ExampleType.name, .string, presence: .explicit(\Google_Expr_Proto2_Test_ExampleType.hasName)))
  fields.append(.singular("foo_bar", number: 2, \Google_Expr_Proto2_Test_ExampleType.fooBar, .string, presence: .explicit(\Google_Expr_Proto2_Test_ExampleType.hasFooBar)))
  fields.append(.singular("in", number: 3, \Google_Expr_Proto2_Test_ExampleType.`in`, .int64, presence: .explicit(\Google_Expr_Proto2_Test_ExampleType.hasIn)))
  return fields
}

fileprivate func _celFields_Google_Expr_Proto2_Test_ExtendedExampleType() -> [ProtobufField<Google_Expr_Proto2_Test_ExtendedExampleType>] {
  []
}
