// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: test/proto3pb/test_import.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

package enum Google_Expr_Proto3_Test_ImportedGlobalEnum: SwiftProtobuf.Enum, Swift.CaseIterable {
  package typealias RawValue = Int
  case importFoo // = 0
  case importBar // = 1
  case importBaz // = 2
  case UNRECOGNIZED(Int)

  package init() {
    self = .importFoo
  }

  package init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .importFoo
    case 1: self = .importBar
    case 2: self = .importBaz
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  package var rawValue: Int {
    switch self {
    case .importFoo: return 0
    case .importBar: return 1
    case .importBaz: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  package static let allCases: [Google_Expr_Proto3_Test_ImportedGlobalEnum] = [
    .importFoo,
    .importBar,
    .importBaz,
  ]

}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension Google_Expr_Proto3_Test_ImportedGlobalEnum: SwiftProtobuf._ProtoNameProviding {
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0IMPORT_FOO\0\u{1}IMPORT_BAR\0\u{1}IMPORT_BAZ\0")
}
