// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: test/proto2pb/test_all_types.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

/// LINT: ALLOW_GROUPS

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// This proto tests that global enums are resolved correctly.
package enum Google_Expr_Proto2_Test_GlobalEnum: Int, SwiftProtobuf.Enum, Swift.CaseIterable {
  case goo = 0
  case gar = 1
  case gaz = 2

  package init() {
    self = .goo
  }

}

/// This proto includes every type of field in both singular and repeated
/// forms.
package struct Google_Expr_Proto2_Test_TestAllTypes: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Singular
  package var singleInt32: Int32 {
    get {_storage._singleInt32 ?? -32}
    set {_uniqueStorage()._singleInt32 = newValue}
  }
  /// Returns true if `singleInt32` has been explicitly set.
  package var hasSingleInt32: Bool {_storage._singleInt32 != nil}
  /// Clears the value of `singleInt32`. Subsequent reads from it will return its default value.
  package mutating func clearSingleInt32() {_uniqueStorage()._singleInt32 = nil}

  package var singleInt64: Int64 {
    get {_storage._singleInt64 ?? -64}
    set {_uniqueStorage()._singleInt64 = newValue}
  }
  /// Returns true if `singleInt64` has been explicitly set.
  package var hasSingleInt64: Bool {_storage._singleInt64 != nil}
  /// Clears the value of `singleInt64`. Subsequent reads from it will return its default value.
  package mutating func clearSingleInt64() {_uniqueStorage()._singleInt64 = nil}

  package var singleUint32: UInt32 {
    get {_storage._singleUint32 ?? 32}
    set {_uniqueStorage()._singleUint32 = newValue}
  }
  /// Returns true if `singleUint32` has been explicitly set.
  package var hasSingleUint32: Bool {_storage._singleUint32 != nil}
  /// Clears the value of `singleUint32`. Subsequent reads from it will return its default value.
  package mutating func clearSingleUint32() {_uniqueStorage()._singleUint32 = nil}

  package var singleUint64: UInt64 {
    get {_storage._singleUint64 ?? 64}
    set {_uniqueStorage()._singleUint64 = newValue}
  }
  /// Returns true if `singleUint64` has been explicitly set.
  package var hasSingleUint64: Bool {_storage._singleUint64 != nil}
  /// Clears the value of `singleUint64`. Subsequent reads from it will return its default value.
  package mutating func clearSingleUint64() {_uniqueStorage()._singleUint64 = nil}

  package var singleSint32: Int32 {
    get {_storage._singleSint32 ?? 0}
    set {_uniqueStorage()._singleSint32 = newValue}
  }
  /// Returns true if `singleSint32` has been explicitly set.
  package var hasSingleSint32: Bool {_storage._singleSint32 != nil}
  /// Clears the value of `singleSint32`. Subsequent reads from it will return its default value.
  package mutating func clearSingleSint32() {_uniqueStorage()._singleSint32 = nil}

  package var singleSint64: Int64 {
    get {_storage._singleSint64 ?? 0}
    set {_uniqueStorage()._singleSint64 = newValue}
  }
  /// Returns true if `singleSint64` has been explicitly set.
  package var hasSingleSint64: Bool {_storage._singleSint64 != nil}
  /// Clears the value of `singleSint64`. Subsequent reads from it will return its default value.
  package mutating func clearSingleSint64() {_uniqueStorage()._singleSint64 = nil}

  package var singleFixed32: UInt32 {
    get {_storage._singleFixed32 ?? 0}
    set {_uniqueStorage()._singleFixed32 = newValue}
  }
  /// Returns true if `singleFixed32` has been explicitly set.
  package var hasSingleFixed32: Bool {_storage._singleFixed32 != nil}
  /// Clears the value of `singleFixed32`. Subsequent reads from it will return its default value.
  package mutating func clearSingleFixed32() {_uniqueStorage()._singleFixed32 = nil}

  package var singleFixed64: UInt64 {
    get {_storage._singleFixed64 ?? 0}
    set {_uniqueStorage()._singleFixed64 = newValue}
  }
  /// Returns true if `singleFixed64` has been explicitly set.
  package var hasSingleFixed64: Bool {_storage._singleFixed64 != nil}
  /// Clears the value of `singleFixed64`. Subsequent reads from it will return its default value.
  package mutating func clearSingleFixed64() {_uniqueStorage()._singleFixed64 = nil}

  package var singleSfixed32: Int32 {
    get {_storage._singleSfixed32 ?? 0}
    set {_uniqueStorage()._singleSfixed32 = newValue}
  }
  /// Returns true if `singleSfixed32` has been explicitly set.
  package var hasSingleSfixed32: Bool {_storage._singleSfixed32 != nil}
  /// Clears the value of `singleSfixed32`. Subsequent reads from it will return its default value.
  package mutating func clearSingleSfixed32() {_uniqueStorage()._singleSfixed32 = nil}

  package var singleSfixed64: Int64 {
    get {_storage._singleSfixed64 ?? 0}
    set {_uniqueStorage()._singleSfixed64 = newValue}
  }
  /// Returns true if `singleSfixed64` has been explicitly set.
  package var hasSingleSfixed64: Bool {_storage._singleSfixed64 != nil}
  /// Clears the value of `singleSfixed64`. Subsequent reads from it will return its default value.
  package mutating func clearSingleSfixed64() {_uniqueStorage()._singleSfixed64 = nil}

  package var singleFloat: Float {
    get {_storage._singleFloat ?? 3}
    set {_uniqueStorage()._singleFloat = newValue}
  }
  /// Returns true if `singleFloat` has been explicitly set.
  package var hasSingleFloat: Bool {_storage._singleFloat != nil}
  /// Clears the value of `singleFloat`. Subsequent reads from it will return its default value.
  package mutating func clearSingleFloat() {_uniqueStorage()._singleFloat = nil}

  package var singleDouble: Double {
    get {_storage._singleDouble ?? 6.4}
    set {_uniqueStorage()._singleDouble = newValue}
  }
  /// Returns true if `singleDouble` has been explicitly set.
  package var hasSingleDouble: Bool {_storage._singleDouble != nil}
  /// Clears the value of `singleDouble`. Subsequent reads from it will return its default value.
  package mutating func clearSingleDouble() {_uniqueStorage()._singleDouble = nil}

  package var singleBool: Bool {
    get {_storage._singleBool ?? true}
    set {_uniqueStorage()._singleBool = newValue}
  }
  /// Returns true if `singleBool` has been explicitly set.
  package var hasSingleBool: Bool {_storage._singleBool != nil}
  /// Clears the value of `singleBool`. Subsequent reads from it will return its default value.
  package mutating func clearSingleBool() {_uniqueStorage()._singleBool = nil}

  package var singleString: String {
    get {_storage._singleString ?? "empty"}
    set {_uniqueStorage()._singleString = newValue}
  }
  /// Returns true if `singleString` has been explicitly set.
  package var hasSingleString: Bool {_storage._singleString != nil}
  /// Clears the value of `singleString`. Subsequent reads from it will return its default value.
  package mutating func clearSingleString() {_uniqueStorage()._singleString = nil}

  package var singleBytes: Data {
    get {_storage._singleBytes ?? Data([110, 111, 110, 101])}
    set {_uniqueStorage()._singleBytes = newValue}
  }
  /// Returns true if `singleBytes` has been explicitly set.
  package var hasSingleBytes: Bool {_storage._singleBytes != nil}
  /// Clears the value of `singleBytes`. Subsequent reads from it will return its default value.
  package mutating func clearSingleBytes() {_uniqueStorage()._singleBytes = nil}

  package var standaloneEnum: Google_Expr_Proto2_Test_TestAllTypes.NestedEnum {
    get {_storage._standaloneEnum ?? .foo}
    set {_uniqueStorage()._standaloneEnum = newValue}
  }
  /// Returns true if `standaloneEnum` has been explicitly set.
  package var hasStandaloneEnum: Bool {_storage._standaloneEnum != nil}
  /// Clears the value of `standaloneEnum`. Subsequent reads from it will return its default value.
  package mutating func clearStandaloneEnum() {_uniqueStorage()._standaloneEnum = nil}

  package var nestedGroup: Google_Expr_Proto2_Test_TestAllTypes.NestedGroup {
    get {_storage._nestedGroup ?? Google_Expr_Proto2_Test_TestAllTypes.NestedGroup()}
    set {_uniqueStorage()._nestedGroup = newValue}
  }
  /// Returns true if `nestedGroup` has been explicitly set.
  package var hasNestedGroup: Bool {_storage._nestedGroup != nil}
  /// Clears the value of `nestedGroup`. Subsequent reads from it will return its default value.
  package mutating func clearNestedGroup() {_uniqueStorage()._nestedGroup = nil}

  /// Wellknown.
  package var singleAny: SwiftProtobuf.Google_Protobuf_Any {
    get {_storage._singleAny ?? SwiftProtobuf.Google_Protobuf_Any()}
    set {_uniqueStorage()._singleAny = newValue}
  }
  /// Returns true if `singleAny` has been explicitly set.
  package var hasSingleAny: Bool {_storage._singleAny != nil}
  /// Clears the value of `singleAny`. Subsequent reads from it will return its default value.
  package mutating func clearSingleAny() {_uniqueStorage()._singleAny = nil}

  package var singleDuration: SwiftProtobuf.Google_Protobuf_Duration {
    get {_storage._singleDuration ?? SwiftProtobuf.Google_Protobuf_Duration()}
    set {_uniqueStorage()._singleDuration = newValue}
  }
  /// Returns true if `singleDuration` has been explicitly set.
  package var hasSingleDuration: Bool {_storage._singleDuration != nil}
  /// Clears the value of `singleDuration`. Subsequent reads from it will return its default value.
  package mutating func clearSingleDuration() {_uniqueStorage()._singleDuration = nil}

  package var singleTimestamp: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {_storage._singleTimestamp ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_uniqueStorage()._singleTimestamp = newValue}
  }
  /// Returns true if `singleTimestamp` has been explicitly set.
  package var hasSingleTimestamp: Bool {_storage._singleTimestamp != nil}
  /// Clears the value of `singleTimestamp`. Subsequent reads from it will return its default value.
  package mutating func clearSingleTimestamp() {_uniqueStorage()._singleTimestamp = nil}

  package var singleStruct: SwiftProtobuf.Google_Protobuf_Struct {
    get {_storage._singleStruct ?? SwiftProtobuf.Google_Protobuf_Struct()}
    set {_uniqueStorage()._singleStruct = newValue}
  }
  /// Returns true if `singleStruct` has been explicitly set.
  package var hasSingleStruct: Bool {_storage._singleStruct != nil}
  /// Clears the value of `singleStruct`. Subsequent reads from it will return its default value.
  package mutating func clearSingleStruct() {_uniqueStorage()._singleStruct = nil}

  package var singleValue: SwiftProtobuf.Google_Protobuf_Value {
    get {_storage._singleValue ?? SwiftProtobuf.Google_Protobuf_Value()}
    set {_uniqueStorage()._singleValue = newValue}
  }
  /// Returns true if `singleValue` has been explicitly set.
  package var hasSingleValue: Bool {_storage._singleValue != nil}
  /// Clears the value of `singleValue`. Subsequent reads from it will return its default value.
  package mutating func clearSingleValue() {_uniqueStorage()._singleValue = nil}

  package var singleInt64Wrapper: SwiftProtobuf.Google_Protobuf_Int64Value {
    get {_storage._singleInt64Wrapper ?? SwiftProtobuf.Google_Protobuf_Int64Value()}
    set {_uniqueStorage()._singleInt64Wrapper = newValue}
  }
  /// Returns true if `singleInt64Wrapper` has been explicitly set.
  package var hasSingleInt64Wrapper: Bool {_storage._singleInt64Wrapper != nil}
  /// Clears the value of `singleInt64Wrapper`. Subsequent reads from it will return its default value.
  package mutating func clearSingleInt64Wrapper() {_uniqueStorage()._singleInt64Wrapper = nil}

  package var singleInt32Wrapper: SwiftProtobuf.Google_Protobuf_Int32Value {
    get {_storage._singleInt32Wrapper ?? SwiftProtobuf.Google_Protobuf_Int32Value()}
    set {_uniqueStorage()._singleInt32Wrapper = newValue}
  }
  /// Returns true if `singleInt32Wrapper` has been explicitly set.
  package var hasSingleInt32Wrapper: Bool {_storage._singleInt32Wrapper != nil}
  /// Clears the value of `singleInt32Wrapper`. Subsequent reads from it will return its default value.
  package mutating func clearSingleInt32Wrapper() {_uniqueStorage()._singleInt32Wrapper = nil}

  package var singleDoubleWrapper: SwiftProtobuf.Google_Protobuf_DoubleValue {
    get {_storage._singleDoubleWrapper ?? SwiftProtobuf.Google_Protobuf_DoubleValue()}
    set {_uniqueStorage()._singleDoubleWrapper = newValue}
  }
  /// Returns true if `singleDoubleWrapper` has been explicitly set.
  package var hasSingleDoubleWrapper: Bool {_storage._singleDoubleWrapper != nil}
  /// Clears the value of `singleDoubleWrapper`. Subsequent reads from it will return its default value.
  package mutating func clearSingleDoubleWrapper() {_uniqueStorage()._singleDoubleWrapper = nil}

  package var singleFloatWrapper: SwiftProtobuf.Google_Protobuf_FloatValue {
    get {_storage._singleFloatWrapper ?? SwiftProtobuf.Google_Protobuf_FloatValue()}
    set {_uniqueStorage()._singleFloatWrapper = newValue}
  }
  /// Returns true if `singleFloatWrapper` has been explicitly set.
  package var hasSingleFloatWrapper: Bool {_storage._singleFloatWrapper != nil}
  /// Clears the value of `singleFloatWrapper`. Subsequent reads from it will return its default value.
  package mutating func clearSingleFloatWrapper() {_uniqueStorage()._singleFloatWrapper = nil}

  package var singleUint64Wrapper: SwiftProtobuf.Google_Protobuf_UInt64Value {
    get {_storage._singleUint64Wrapper ?? SwiftProtobuf.Google_Protobuf_UInt64Value()}
    set {_uniqueStorage()._singleUint64Wrapper = newValue}
  }
  /// Returns true if `singleUint64Wrapper` has been explicitly set.
  package var hasSingleUint64Wrapper: Bool {_storage._singleUint64Wrapper != nil}
  /// Clears the value of `singleUint64Wrapper`. Subsequent reads from it will return its default value.
  package mutating func clearSingleUint64Wrapper() {_uniqueStorage()._singleUint64Wrapper = nil}

  package var singleUint32Wrapper: SwiftProtobuf.Google_Protobuf_UInt32Value {
    get {_storage._singleUint32Wrapper ?? SwiftProtobuf.Google_Protobuf_UInt32Value()}
    set {_uniqueStorage()._singleUint32Wrapper = newValue}
  }
  /// Returns true if `singleUint32Wrapper` has been explicitly set.
  package var hasSingleUint32Wrapper: Bool {_storage._singleUint32Wrapper != nil}
  /// Clears the value of `singleUint32Wrapper`. Subsequent reads from it will return its default value.
  package mutating func clearSingleUint32Wrapper() {_uniqueStorage()._singleUint32Wrapper = nil}

  package var singleStringWrapper: SwiftProtobuf.Google_Protobuf_StringValue {
    get {_storage._singleStringWrapper ?? SwiftProtobuf.Google_Protobuf_StringValue()}
    set {_uniqueStorage()._singleStringWrapper = newValue}
  }
  /// Returns true if `singleStringWrapper` has been explicitly set.
  package var hasSingleStringWrapper: Bool {_storage._singleStringWrapper != nil}
  /// Clears the value of `singleStringWrapper`. Subsequent reads from it will return its default value.
  package mutating func clearSingleStringWrapper() {_uniqueStorage()._singleStringWrapper = nil}

  package var singleBoolWrapper: SwiftProtobuf.Google_Protobuf_BoolValue {
    get {_storage._singleBoolWrapper ?? SwiftProtobuf.Google_Protobuf_BoolValue()}
    set {_uniqueStorage()._singleBoolWrapper = newValue}
  }
  /// Returns true if `singleBoolWrapper` has been explicitly set.
  package var hasSingleBoolWrapper: Bool {_storage._singleBoolWrapper != nil}
  /// Clears the value of `singleBoolWrapper`. Subsequent reads from it will return its default value.
  package mutating func clearSingleBoolWrapper() {_uniqueStorage()._singleBoolWrapper = nil}

  package var singleBytesWrapper: SwiftProtobuf.Google_Protobuf_BytesValue {
    get {_storage._singleBytesWrapper ?? SwiftProtobuf.Google_Protobuf_BytesValue()}
    set {_uniqueStorage()._singleBytesWrapper = newValue}
  }
  /// Returns true if `singleBytesWrapper` has been explicitly set.
  package var hasSingleBytesWrapper: Bool {_storage._singleBytesWrapper != nil}
  /// Clears the value of `singleBytesWrapper`. Subsequent reads from it will return its default value.
  package mutating func clearSingleBytesWrapper() {_uniqueStorage()._singleBytesWrapper = nil}

  /// Nested messages
  package var nestedType: OneOf_NestedType? {
    get {return _storage._nestedType}
    set {_uniqueStorage()._nestedType = newValue}
  }

  package var singleNestedMessage: Google_Expr_Proto2_Test_TestAllTypes.NestedMessage {
    get {
      if case .singleNestedMessage(let v)? = _storage._nestedType {return v}
      return Google_Expr_Proto2_Test_TestAllTypes.NestedMessage()
    }
    set {_uniqueStorage()._nestedType = .singleNestedMessage(newValue)}
  }

  package var singleNestedEnum: Google_Expr_Proto2_Test_TestAllTypes.NestedEnum {
    get {
      if case .singleNestedEnum(let v)? = _storage._nestedType {return v}
      return .bar
    }
    set {_uniqueStorage()._nestedType = .singleNestedEnum(newValue)}
  }

  /// Repeated
  package var repeatedInt32: [Int32] {
    get {_storage._repeatedInt32}
    set {_uniqueStorage()._repeatedInt32 = newValue}
  }

  package var repeatedInt64: [Int64] {
    get {_storage._repeatedInt64}
    set {_uniqueStorage()._repeatedInt64 = newValue}
  }

  package var repeatedUint32: [UInt32] {
    get {_storage._repeatedUint32}
    set {_uniqueStorage()._repeatedUint32 = newValue}
  }

  package var repeatedUint64: [UInt64] {
    get {_storage._repeatedUint64}
    set {_uniqueStorage()._repeatedUint64 = newValue}
  }

  package var repeatedSint32: [Int32] {
    get {_storage._repeatedSint32}
    set {_uniqueStorage()._repeatedSint32 = newValue}
  }

  package var repeatedSint64: [Int64] {
    get {_storage._repeatedSint64}
    set {_uniqueStorage()._repeatedSint64 = newValue}
  }

  package var repeatedFixed32: [UInt32] {
    get {_storage._repeatedFixed32}
    set {_uniqueStorage()._repeatedFixed32 = newValue}
  }

  package var repeatedFixed64: [UInt64] {
    get {_storage._repeatedFixed64}
    set {_uniqueStorage()._repeatedFixed64 = newValue}
  }

  package var repeatedSfixed32: [Int32] {
    get {_storage._repeatedSfixed32}
    set {_uniqueStorage()._repeatedSfixed32 = newValue}
  }

  package var repeatedSfixed64: [Int64] {
    get {_storage._repeatedSfixed64}
    set {_uniqueStorage()._repeatedSfixed64 = newValue}
  }

  package var repeatedFloat: [Float] {
    get {_storage._repeatedFloat}
    set {_uniqueStorage()._repeatedFloat = newValue}
  }

  package var repeatedDouble: [Double] {
    get {_storage._repeatedDouble}
    set {_uniqueStorage()._repeatedDouble = newValue}
  }

  package var repeatedBool: [Bool] {
    get {_storage._repeatedBool}
    set {_uniqueStorage()._repeatedBool = newValue}
  }

  package var repeatedString: [String] {
    get {_storage._repeatedString}
    set {_uniqueStorage()._repeatedString = newValue}
  }

  package var repeatedBytes: [Data] {
    get {_storage._repeatedBytes}
    set {_uniqueStorage()._repeatedBytes = newValue}
  }

  package var repeatedNestedMessage: [Google_Expr_Proto2_Test_TestAllTypes.NestedMessage] {
    get {_storage._repeatedNestedMessage}
    set {_uniqueStorage()._repeatedNestedMessage = newValue}
  }

  package var repeatedNestedEnum: [Google_Expr_Proto2_Test_TestAllTypes.NestedEnum] {
    get {_storage._repeatedNestedEnum}
    set {_uniqueStorage()._repeatedNestedEnum = newValue}
  }

  package var repeatedStringPiece: [String] {
    get {_storage._repeatedStringPiece}
    set {_uniqueStorage()._repeatedStringPiece = newValue}
  }

  package var repeatedCord: [String] {
    get {_storage._repeatedCord}
    set {_uniqueStorage()._repeatedCord = newValue}
  }

  package var repeatedLazyMessage: [Google_Expr_Proto2_Test_TestAllTypes.NestedMessage] {
    get {_storage._repeatedLazyMessage}
    set {_uniqueStorage()._repeatedLazyMessage = newValue}
  }

  /// Map
  package var mapStringString: Dictionary<String,String> {
    get {_storage._mapStringString}
    set {_uniqueStorage()._mapStringString = newValue}
  }

  package var mapInt64NestedType: Dictionary<Int64,Google_Expr_Proto2_Test_NestedTestAllTypes> {
    get {_storage._mapInt64NestedType}
    set {_uniqueStorage()._mapInt64NestedType = newValue}
  }

  package var unknownFields = SwiftProtobuf.UnknownStorage()

  /// Nested messages
  package enum OneOf_NestedType: Equatable, Sendable {
    case singleNestedMessage(Google_Expr_Proto2_Test_TestAllTypes.NestedMessage)
    case singleNestedEnum(Google_Expr_Proto2_Test_TestAllTypes.NestedEnum)

  }

  package enum NestedEnum: Int, SwiftProtobuf.Enum, Swift.CaseIterable {
    case foo = 0
    case bar = 1
    case baz = 2

    package init() {
      self = .foo
    }

  }

  package struct NestedMessage: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// The field name "b" fails to compile in proto1 because it conflicts with
    /// a local variable named "b" in one of the generated methods.
    /// This file needs to compile in proto1 to test backwards-compatibility.
    package var bb: Int32 {
      get {_bb ?? 0}
      set {_bb = newValue}
    }
    /// Returns true if `bb` has been explicitly set.
    package var hasBb: Bool {self._bb != nil}
    /// Clears the value of `bb`. Subsequent reads from it will return its default value.
    package mutating func clearBb() {self._bb = nil}

    package var unknownFields = SwiftProtobuf.UnknownStorage()

    package init() {}

    fileprivate var _bb: Int32? = nil
  }

  package struct NestedGroup: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    package var nestedID: Int32 {
      get {_nestedID ?? 0}
      set {_nestedID = newValue}
    }
    /// Returns true if `nestedID` has been explicitly set.
    package var hasNestedID: Bool {self._nestedID != nil}
    /// Clears the value of `nestedID`. Subsequent reads from it will return its default value.
    package mutating func clearNestedID() {self._nestedID = nil}

    package var nestedName: String {
      get {_nestedName ?? String()}
      set {_nestedName = newValue}
    }
    /// Returns true if `nestedName` has been explicitly set.
    package var hasNestedName: Bool {self._nestedName != nil}
    /// Clears the value of `nestedName`. Subsequent reads from it will return its default value.
    package mutating func clearNestedName() {self._nestedName = nil}

    package var unknownFields = SwiftProtobuf.UnknownStorage()

    package init() {}

    fileprivate var _nestedID: Int32? = nil
    fileprivate var _nestedName: String? = nil
  }

  package init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

/// This proto includes a recursively nested message.
package struct Google_Expr_Proto2_Test_NestedTestAllTypes: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  package var child: Google_Expr_Proto2_Test_NestedTestAllTypes {
    get {_storage._child ?? Google_Expr_Proto2_Test_NestedTestAllTypes()}
    set {_uniqueStorage()._child = newValue}
  }
  /// Returns true if `child` has been explicitly set.
  package var hasChild: Bool {_storage._child != nil}
  /// Clears the value of `child`. Subsequent reads from it will return its default value.
  package mutating func clearChild() {_uniqueStorage()._child = nil}

  package var payload: Google_Expr_Proto2_Test_TestAllTypes {
    get {_storage._payload ?? Google_Expr_Proto2_Test_TestAllTypes()}
    set {_uniqueStorage()._payload = newValue}
  }
  /// Returns true if `payload` has been explicitly set.
  package var hasPayload: Bool {_storage._payload != nil}
  /// Clears the value of `payload`. Subsequent reads from it will return its default value.
  package mutating func clearPayload() {_uniqueStorage()._payload = nil}

  package var unknownFields = SwiftProtobuf.UnknownStorage()

  package init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

/// This proto is used to show how extensions are tracked as fields
/// with fully qualified names.
package struct Google_Expr_Proto2_Test_ExampleType: SwiftProtobuf.ExtensibleMessage, Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  package var name: String {
    get {_name ?? String()}
    set {_name = newValue}
  }
  /// Returns true if `name` has been explicitly set.
  package var hasName: Bool {self._name != nil}
  /// Clears the value of `name`. Subsequent reads from it will return its default value.
  package mutating func clearName() {self._name = nil}

  package var fooBar: String {
    get {_fooBar ?? String()}
    set {_fooBar = newValue}
  }
  /// Returns true if `fooBar` has been explicitly set.
  package var hasFooBar: Bool {self._fooBar != nil}
  /// Clears the value of `fooBar`. Subsequent reads from it will return its default value.
  package mutating func clearFooBar() {self._fooBar = nil}

  package var `in`: Int64 {
    get {_in ?? 0}
    set {_in = newValue}
  }
  /// Returns true if ``in`` has been explicitly set.
  package var hasIn: Bool {self._in != nil}
  /// Clears the value of ``in``. Subsequent reads from it will return its default value.
  package mutating func clearIn() {self._in = nil}

  package var unknownFields = SwiftProtobuf.UnknownStorage()

  package init() {}

  package var _protobuf_extensionFieldValues = SwiftProtobuf.ExtensionFieldValueSet()
  fileprivate var _name: String? = nil
  fileprivate var _fooBar: String? = nil
  fileprivate var _in: Int64? = nil
}

/// Message scoped extensions.
package struct Google_Expr_Proto2_Test_ExtendedExampleType: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  package var unknownFields = SwiftProtobuf.UnknownStorage()

  package init() {}
}

// MARK: - Extension support defined in test_all_types.proto.

// MARK: - Extension Properties

// Swift Extensions on the extended Messages to add easy access to the declared
// extension fields. The names are based on the extension field name from the proto
// declaration. To avoid naming collisions, the names are prefixed with the name of
// the scope where the extend directive occurs.

extension Google_Expr_Proto2_Test_ExampleType {

  package var Google_Expr_Proto2_Test_ExtendedExampleType_extendedExamples: [String] {
    get {return getExtensionValue(ext: Google_Expr_Proto2_Test_ExtendedExampleType.Extensions.extended_examples) ?? []}
    set {setExtensionValue(ext: Google_Expr_Proto2_Test_ExtendedExampleType.Extensions.extended_examples, value: newValue)}
  }

  package var Google_Expr_Proto2_Test_ExtendedExampleType_enumExt: Google_Expr_Proto2_Test_GlobalEnum {
    get {return getExtensionValue(ext: Google_Expr_Proto2_Test_ExtendedExampleType.Extensions.enum_ext) ?? .goo}
    set {setExtensionValue(ext: Google_Expr_Proto2_Test_ExtendedExampleType.Extensions.enum_ext, value: newValue)}
  }
  /// Returns true if extension `Google_Expr_Proto2_Test_ExtendedExampleType.Extensions.enum_ext`
  /// has been explicitly set.
  package var hasGoogle_Expr_Proto2_Test_ExtendedExampleType_enumExt: Bool {
    return hasExtensionValue(ext: Google_Expr_Proto2_Test_ExtendedExampleType.Extensions.enum_ext)
  }
  /// Clears the value of extension `Google_Expr_Proto2_Test_ExtendedExampleType.Extensions.enum_ext`.
  /// Subsequent reads from it will return its default value.
  package mutating func clearGoogle_Expr_Proto2_Test_ExtendedExampleType_enumExt() {
    clearExtensionValue(ext: Google_Expr_Proto2_Test_ExtendedExampleType.Extensions.enum_ext)
  }

}

// MARK: - File's ExtensionMap: Google_Expr_Proto2_Test_TestAllTypes_Extensions

/// A `SwiftProtobuf.SimpleExtensionMap` that includes all of the extensions defined by
/// this .proto file. It can be used any place an `SwiftProtobuf.ExtensionMap` is needed
/// in parsing, or it can be combined with other `SwiftProtobuf.SimpleExtensionMap`s to create
/// a larger `SwiftProtobuf.SimpleExtensionMap`.
package let Google_Expr_Proto2_Test_TestAllTypes_Extensions: SwiftProtobuf.SimpleExtensionMap = [
  Google_Expr_Proto2_Test_ExtendedExampleType.Extensions.extended_examples,
  Google_Expr_Proto2_Test_ExtendedExampleType.Extensions.enum_ext
]

// Extension Objects - The only reason these might be needed is when manually
// constructing a `SimpleExtensionMap`, otherwise, use the above _Extension Properties_
// accessors for the extension fields on the messages directly.

extension Google_Expr_Proto2_Test_ExtendedExampleType {
  package enum Extensions {
    package static let extended_examples = SwiftProtobuf.MessageExtension<SwiftProtobuf.RepeatedExtensionField<SwiftProtobuf.ProtobufString>, Google_Expr_Proto2_Test_ExampleType>(
      _protobuf_fieldNumber: 103,
      fieldName: "google.expr.proto2.test.ExtendedExampleType.extended_examples"
    )

    package static let enum_ext = SwiftProtobuf.MessageExtension<SwiftProtobuf.OptionalEnumExtensionField<Google_Expr_Proto2_Test_GlobalEnum>, Google_Expr_Proto2_Test_ExampleType>(
      _protobuf_fieldNumber: 104,
      fieldName: "google.expr.proto2.test.ExtendedExampleType.enum_ext"
    )
  }
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "google.expr.proto2.test"

extension Google_Expr_Proto2_Test_GlobalEnum: SwiftProtobuf._ProtoNameProviding {
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0GOO\0\u{1}GAR\0\u{1}GAZ\0")
}

extension Google_Expr_Proto2_Test_TestAllTypes: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = _protobuf_package + ".TestAllTypes"
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}single_int32\0\u{3}single_int64\0\u{3}single_uint32\0\u{3}single_uint64\0\u{3}single_sint32\0\u{3}single_sint64\0\u{3}single_fixed32\0\u{3}single_fixed64\0\u{3}single_sfixed32\0\u{3}single_sfixed64\0\u{3}single_float\0\u{3}single_double\0\u{3}single_bool\0\u{3}single_string\0\u{3}single_bytes\0\u{4}\u{3}single_nested_message\0\u{4}\u{3}single_nested_enum\0\u{3}standalone_enum\0\u{7}NestedGroup\0\u{4}\u{8}repeated_int32\0\u{3}repeated_int64\0\u{3}repeated_uint32\0\u{3}repeated_uint64\0\u{3}repeated_sint32\0\u{3}repeated_sint64\0\u{3}repeated_fixed32\0\u{3}repeated_fixed64\0\u{3}repeated_sfixed32\0\u{3}repeated_sfixed64\0\u{3}repeated_float\0\u{3}repeated_double\0\u{3}repeated_bool\0\u{3}repeated_string\0\u{3}repeated_bytes\0\u{4}\u{3}repeated_nested_message\0\u{4}\u{3}repeated_nested_enum\0\u{4}\u{3}repeated_string_piece\0\u{3}repeated_cord\0\u{4}\u{2}repeated_lazy_message\0\u{3}map_string_string\0\u{3}map_int64_nested_type\0\u{4})single_any\0\u{3}single_duration\0\u{3}single_timestamp\0\u{3}single_struct\0\u{3}single_value\0\u{3}single_int64_wrapper\0\u{3}single_int32_wrapper\0\u{3}single_double_wrapper\0\u{3}single_float_wrapper\0\u{3}single_uint64_wrapper\0\u{3}single_uint32_wrapper\0\u{3}single_string_wrapper\0\u{3}single_bool_wrapper\0\u{3}single_bytes_wrapper\0")

  fileprivate class _StorageClass {
    var _singleInt32: Int32? = nil
    var _singleInt64: Int64? = nil
    var _singleUint32: UInt32? = nil
    var _singleUint64: UInt64? = nil
    var _singleSint32: Int32? = nil
    var _singleSint64: Int64? = nil
    var _singleFixed32: UInt32? = nil
    var _singleFixed64: UInt64? = nil
    var _singleSfixed32: Int32? = nil
    var _singleSfixed64: Int64? = nil
    var _singleFloat: Float? = nil
    var _singleDouble: Double? = nil
    var _singleBool: Bool? = nil
    var _singleString: String? = nil
    var _singleBytes: Data? = nil
    var _standaloneEnum: Google_Expr_Proto2_Test_TestAllTypes.NestedEnum? = nil
    var _nestedGroup: Google_Expr_Proto2_Test_TestAllTypes.NestedGroup? = nil
    var _singleAny: SwiftProtobuf.Google_Protobuf_Any? = nil
    var _singleDuration: SwiftProtobuf.Google_Protobuf_Duration? = nil
    var _singleTimestamp: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
    var _singleStruct: SwiftProtobuf.Google_Protobuf_Struct? = nil
    var _singleValue: SwiftProtobuf.Google_Protobuf_Value? = nil
    var _singleInt64Wrapper: SwiftProtobuf.Google_Protobuf_Int64Value? = nil
    var _singleInt32Wrapper: SwiftProtobuf.Google_Protobuf_Int32Value? = nil
    var _singleDoubleWrapper: SwiftProtobuf.Google_Protobuf_DoubleValue? = nil
    var _singleFloatWrapper: SwiftProtobuf.Google_Protobuf_FloatValue? = nil
    var _singleUint64Wrapper: SwiftProtobuf.Google_Protobuf_UInt64Value? = nil
    var _singleUint32Wrapper: SwiftProtobuf.Google_Protobuf_UInt32Value? = nil
    var _singleStringWrapper: SwiftProtobuf.Google_Protobuf_StringValue? = nil
    var _singleBoolWrapper: SwiftProtobuf.Google_Protobuf_BoolValue? = nil
    var _singleBytesWrapper: SwiftProtobuf.Google_Protobuf_BytesValue? = nil
    var _nestedType: Google_Expr_Proto2_Test_TestAllTypes.OneOf_NestedType?
    var _repeatedInt32: [Int32] = []
    var _repeatedInt64: [Int64] = []
    var _repeatedUint32: [UInt32] = []
    var _repeatedUint64: [UInt64] = []
    var _repeatedSint32: [Int32] = []
    var _repeatedSint64: [Int64] = []
    var _repeatedFixed32: [UInt32] = []
    var _repeatedFixed64: [UInt64] = []
    var _repeatedSfixed32: [Int32] = []
    var _repeatedSfixed64: [Int64] = []
    var _repeatedFloat: [Float] = []
    var _repeatedDouble: [Double] = []
    var _repeatedBool: [Bool] = []
    var _repeatedString: [String] = []
    var _repeatedBytes: [Data] = []
    var _repeatedNestedMessage: [Google_Expr_Proto2_Test_TestAllTypes.NestedMessage] = []
    var _repeatedNestedEnum: [Google_Expr_Proto2_Test_TestAllTypes.NestedEnum] = []
    var _repeatedStringPiece: [String] = []
    var _repeatedCord: [String] = []
    var _repeatedLazyMessage: [Google_Expr_Proto2_Test_TestAllTypes.NestedMessage] = []
    var _mapStringString: Dictionary<String,String> = [:]
    var _mapInt64NestedType: Dictionary<Int64,Google_Expr_Proto2_Test_NestedTestAllTypes> = [:]

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _singleInt32 = source._singleInt32
      _singleInt64 = source._singleInt64
      _singleUint32 = source._singleUint32
      _singleUint64 = source._singleUint64
      _singleSint32 = source._singleSint32
      _singleSint64 = source._singleSint64
      _singleFixed32 = source._singleFixed32
      _singleFixed64 = source._singleFixed64
      _singleSfixed32 = source._singleSfixed32
      _singleSfixed64 = source._singleSfixed64
      _singleFloat = source._singleFloat
      _singleDouble = source._singleDouble
      _singleBool = source._singleBool
      _singleString = source._singleString
      _singleBytes = source._singleBytes
      _standaloneEnum = source._standaloneEnum
      _nestedGroup = source._nestedGroup
      _singleAny = source._singleAny
      _singleDuration = source._singleDuration
      _singleTimestamp = source._singleTimestamp
      _singleStruct = source._singleStruct
      _singleValue = source._singleValue
      _singleInt64Wrapper = source._singleInt64Wrapper
      _singleInt32Wrapper = source._singleInt32Wrapper
      _singleDoubleWrapper = source._singleDoubleWrapper
      _singleFloatWrapper = source._singleFloatWrapper
      _singleUint64Wrapper = source._singleUint64Wrapper
      _singleUint32Wrapper = source._singleUint32Wrapper
      _singleStringWrapper = source._singleStringWrapper
      _singleBoolWrapper = source._singleBoolWrapper
      _singleBytesWrapper = source._singleBytesWrapper
      _nestedType = source._nestedType
      _repeatedInt32 = source._repeatedInt32
      _repeatedInt64 = source._repeatedInt64
      _repeatedUint32 = source._repeatedUint32
      _repeatedUint64 = source._repeatedUint64
      _repeatedSint32 = source._repeatedSint32
      _repeatedSint64 = source._repeatedSint64
      _repeatedFixed32 = source._repeatedFixed32
      _repeatedFixed64 = source._repeatedFixed64
      _repeatedSfixed32 = source._repeatedSfixed32
      _repeatedSfixed64 = source._repeatedSfixed64
      _repeatedFloat = source._repeatedFloat
      _repeatedDouble = source._repeatedDouble
      _repeatedBool = source._repeatedBool
      _repeatedString = source._repeatedString
      _repeatedBytes = source._repeatedBytes
      _repeatedNestedMessage = source._repeatedNestedMessage
      _repeatedNestedEnum = source._repeatedNestedEnum
      _repeatedStringPiece = source._repeatedStringPiece
      _repeatedCord = source._repeatedCord
      _repeatedLazyMessage = source._repeatedLazyMessage
      _mapStringString = source._mapStringString
      _mapInt64NestedType = source._mapInt64NestedType
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularInt32Field(value: &_storage._singleInt32) }()
        case 2: try { try decoder.decodeSingularInt64Field(value: &_storage._singleInt64) }()
        case 3: try { try decoder.decodeSingularUInt32Field(value: &_storage._singleUint32) }()
        case 4: try { try decoder.decodeSingularUInt64Field(value: &_storage._singleUint64) }()
        case 5: try { try decoder.decodeSingularSInt32Field(value: &_storage._singleSint32) }()
        case 6: try { try decoder.decodeSingularSInt64Field(value: &_storage._singleSint64) }()
        case 7: try { try decoder.decodeSingularFixed32Field(value: &_storage._singleFixed32) }()
        case 8: try { try decoder.decodeSingularFixed64Field(value: &_storage._singleFixed64) }()
        case 9: try { try decoder.decodeSingularSFixed32Field(value: &_storage._singleSfixed32) }()
        case 10: try { try decoder.decodeSingularSFixed64Field(value: &_storage._singleSfixed64) }()
        case 11: try { try decoder.decodeSingularFloatField(value: &_storage._singleFloat) }()
        case 12: try { try decoder.decodeSingularDoubleField(value: &_storage._singleDouble) }()
        case 13: try { try decoder.decodeSingularBoolField(value: &_storage._singleBool) }()
        case 14: try { try decoder.decodeSingularStringField(value: &_storage._singleString) }()
        case 15: try { try decoder.decodeSingularBytesField(value: &_storage._singleBytes) }()
        case 18: try {
          var v: Google_Expr_Proto2_Test_TestAllTypes.NestedMessage?
          var hadOneofValue = false
          if let current = _storage._nestedType {
            hadOneofValue = true
            if case .singleNestedMessage(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._nestedType = .singleNestedMessage(v)
          }
        }()
        case 21: try {
          var v: Google_Expr_Proto2_Test_TestAllTypes.NestedEnum?
          try decoder.decodeSingularEnumField(value: &v)
          if let v = v {
            if _storage._nestedType != nil {try decoder.handleConflictingOneOf()}
            _storage._nestedType = .singleNestedEnum(v)
          }
        }()
        case 22: try { try decoder.decodeSingularEnumField(value: &_storage._standaloneEnum) }()
        case 23: try { try decoder.decodeSingularGroupField(value: &_storage._nestedGroup) }()
        case 31: try { try decoder.decodeRepeatedInt32Field(value: &_storage._repeatedInt32) }()
        case 32: try { try decoder.decodeRepeatedInt64Field(value: &_storage._repeatedInt64) }()
        case 33: try { try decoder.decodeRepeatedUInt32Field(value: &_storage._repeatedUint32) }()
        case 34: try { try decoder.decodeRepeatedUInt64Field(value: &_storage._repeatedUint64) }()
        case 35: try { try decoder.decodeRepeatedSInt32Field(value: &_storage._repeatedSint32) }()
        case 36: try { try decoder.decodeRepeatedSInt64Field(value: &_storage._repeatedSint64) }()
        case 37: try { try decoder.decodeRepeatedFixed32Field(value: &_storage._repeatedFixed32) }()
        case 38: try { try decoder.decodeRepeatedFixed64Field(value: &_storage._repeatedFixed64) }()
        case 39: try { try decoder.decodeRepeatedSFixed32Field(value: &_storage._repeatedSfixed32) }()
        case 40: try { try decoder.decodeRepeatedSFixed64Field(value: &_storage._repeatedSfixed64) }()
        case 41: try { try decoder.decodeRepeatedFloatField(value: &_storage._repeatedFloat) }()
        case 42: try { try decoder.decodeRepeatedDoubleField(value: &_storage._repeatedDouble) }()
        case 43: try { try decoder.decodeRepeatedBoolField(value: &_storage._repeatedBool) }()
        case 44: try { try decoder.decodeRepeatedStringField(value: &_storage._repeatedString) }()
        case 45: try { try decoder.decodeRepeatedBytesField(value: &_storage._repeatedBytes) }()
        case 48: try { try decoder.decodeRepeatedMessageField(value: &_storage._repeatedNestedMessage) }()
        case 51: try { try decoder.decodeRepeatedEnumField(value: &_storage._repeatedNestedEnum) }()
        case 54: try { try decoder.decodeRepeatedStringField(value: &_storage._repeatedStringPiece) }()
        case 55: try { try decoder.decodeRepeatedStringField(value: &_storage._repeatedCord) }()
        case 57: try { try decoder.decodeRepeatedMessageField(value: &_storage._repeatedLazyMessage) }()
        case 58: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &_storage._mapStringString) }()
        case 59: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufInt64,Google_Expr_Proto2_Test_NestedTestAllTypes>.self, value: &_storage._mapInt64NestedType) }()
        case 100: try { try decoder.decodeSingularMessageField(value: &_storage._singleAny) }()
        case 101: try { try decoder.decodeSingularMessageField(value: &_storage._singleDuration) }()
        case 102: try { try decoder.decodeSingularMessageField(value: &_storage._singleTimestamp) }()
        case 103: try { try decoder.decodeSingularMessageField(value: &_storage._singleStruct) }()
        case 104: try { try decoder.decodeSingularMessageField(value: &_storage._singleValue) }()
        case 105: try { try decoder.decodeSingularMessageField(value: &_storage._singleInt64Wrapper) }()
        case 106: try { try decoder.decodeSingularMessageField(value: &_storage._singleInt32Wrapper) }()
        case 107: try { try decoder.decodeSingularMessageField(value: &_storage._singleDoubleWrapper) }()
        case 108: try { try decoder.decodeSingularMessageField(value: &_storage._singleFloatWrapper) }()
        case 109: try { try decoder.decodeSingularMessageField(value: &_storage._singleUint64Wrapper) }()
        case 110: try { try decoder.decodeSingularMessageField(value: &_storage._singleUint32Wrapper) }()
        case 111: try { try decoder.decodeSingularMessageField(value: &_storage._singleStringWrapper) }()
        case 112: try { try decoder.decodeSingularMessageField(value: &_storage._singleBoolWrapper) }()
        case 113: try { try decoder.decodeSingularMessageField(value: &_storage._singleBytesWrapper) }()
        default: break
        }
      }
    }
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      try { if let v = _storage._singleInt32 {
        try visitor.visitSingularInt32Field(value: v, fieldNumber: 1)
      } }()
      try { if let v = _storage._singleInt64 {
        try visitor.visitSingularInt64Field(value: v, fieldNumber: 2)
      } }()
      try { if let v = _storage._singleUint32 {
        try visitor.visitSingularUInt32Field(value: v, fieldNumber: 3)
      } }()
      try { if let v = _storage._singleUint64 {
        try visitor.visitSingularUInt64Field(value: v, fieldNumber: 4)
      } }()
      try { if let v = _storage._singleSint32 {
        try visitor.visitSingularSInt32Field(value: v, fieldNumber: 5)
      } }()
      try { if let v = _storage._singleSint64 {
        try visitor.visitSingularSInt64Field(value: v, fieldNumber: 6)
      } }()
      try { if let v = _storage._singleFixed32 {
        try visitor.visitSingularFixed32Field(value: v, fieldNumber: 7)
      } }()
      try { if let v = _storage._singleFixed64 {
        try visitor.visitSingularFixed64Field(value: v, fieldNumber: 8)
      } }()
      try { if let v = _storage._singleSfixed32 {
        try visitor.visitSingularSFixed32Field(value: v, fieldNumber: 9)
      } }()
      try { if let v = _storage._singleSfixed64 {
        try visitor.visitSingularSFixed64Field(value: v, fieldNumber: 10)
      } }()
      try { if let v = _storage._singleFloat {
        try visitor.visitSingularFloatField(value: v, fieldNumber: 11)
      } }()
      try { if let v = _storage._singleDouble {
        try visitor.visitSingularDoubleField(value: v, fieldNumber: 12)
      } }()
      try { if let v = _storage._singleBool {
        try visitor.visitSingularBoolField(value: v, fieldNumber: 13)
      } }()
      try { if let v = _storage._singleString {
        try visitor.visitSingularStringField(value: v, fieldNumber: 14)
      } }()
      try { if let v = _storage._singleBytes {
        try visitor.visitSingularBytesField(value: v, fieldNumber: 15)
      } }()
      switch _storage._nestedType {
      case .singleNestedMessage?: try {
        guard case .singleNestedMessage(let v)? = _storage._nestedType else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 18)
      }()
      case .singleNestedEnum?: try {
        guard case .singleNestedEnum(let v)? = _storage._nestedType else { preconditionFailure() }
        try visitor.visitSingularEnumField(value: v, fieldNumber: 21)
      }()
      case nil: break
      }
      try { if let v = _storage._standaloneEnum {
        try visitor.visitSingularEnumField(value: v, fieldNumber: 22)
      } }()
      try { if let v = _storage._nestedGroup {
        try visitor.visitSingularGroupField(value: v, fieldNumber: 23)
      } }()
      if !_storage._repeatedInt32.isEmpty {
        try visitor.visitRepeatedInt32Field(value: _storage._repeatedInt32, fieldNumber: 31)
      }
      if !_storage._repeatedInt64.isEmpty {
        try visitor.visitRepeatedInt64Field(value: _storage._repeatedInt64, fieldNumber: 32)
      }
      if !_storage._repeatedUint32.isEmpty {
        try visitor.visitRepeatedUInt32Field(value: _storage._repeatedUint32, fieldNumber: 33)
      }
      if !_storage._repeatedUint64.isEmpty {
        try visitor.visitRepeatedUInt64Field(value: _storage._repeatedUint64, fieldNumber: 34)
      }
      if !_storage._repeatedSint32.isEmpty {
        try visitor.visitRepeatedSInt32Field(value: _storage._repeatedSint32, fieldNumber: 35)
      }
      if !_storage._repeatedSint64.isEmpty {
        try visitor.visitRepeatedSInt64Field(value: _storage._repeatedSint64, fieldNumber: 36)
      }
      if !_storage._repeatedFixed32.isEmpty {
        try visitor.visitRepeatedFixed32Field(value: _storage._repeatedFixed32, fieldNumber: 37)
      }
      if !_storage._repeatedFixed64.isEmpty {
        try visitor.visitRepeatedFixed64Field(value: _storage._repeatedFixed64, fieldNumber: 38)
      }
      if !_storage._repeatedSfixed32.isEmpty {
        try visitor.visitRepeatedSFixed32Field(value: _storage._repeatedSfixed32, fieldNumber: 39)
      }
      if !_storage._repeatedSfixed64.isEmpty {
        try visitor.visitRepeatedSFixed64Field(value: _storage._repeatedSfixed64, fieldNumber: 40)
      }
      if !_storage._repeatedFloat.isEmpty {
        try visitor.visitRepeatedFloatField(value: _storage._repeatedFloat, fieldNumber: 41)
      }
      if !_storage._repeatedDouble.isEmpty {
        try visitor.visitRepeatedDoubleField(value: _storage._repeatedDouble, fieldNumber: 42)
      }
      if !_storage._repeatedBool.isEmpty {
        try visitor.visitRepeatedBoolField(value: _storage._repeatedBool, fieldNumber: 43)
      }
      if !_storage._repeatedString.isEmpty {
        try visitor.visitRepeatedStringField(value: _storage._repeatedString, fieldNumber: 44)
      }
      if !_storage._repeatedBytes.isEmpty {
        try visitor.visitRepeatedBytesField(value: _storage._repeatedBytes, fieldNumber: 45)
      }
      if !_storage._repeatedNestedMessage.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._repeatedNestedMessage, fieldNumber: 48)
      }
      if !_storage._repeatedNestedEnum.isEmpty {
        try visitor.visitRepeatedEnumField(value: _storage._repeatedNestedEnum, fieldNumber: 51)
      }
      if !_storage._repeatedStringPiece.isEmpty {
        try visitor.visitRepeatedStringField(value: _storage._repeatedStringPiece, fieldNumber: 54)
      }
      if !_storage._repeatedCord.isEmpty {
        try visitor.visitRepeatedStringField(value: _storage._repeatedCord, fieldNumber: 55)
      }
      if !_storage._repeatedLazyMessage.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._repeatedLazyMessage, fieldNumber: 57)
      }
      if !_storage._mapStringString.isEmpty {
        try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: _storage._mapStringString, fieldNumber: 58)
      }
      if !_storage._mapInt64NestedType.isEmpty {
        try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufInt64,Google_Expr_Proto2_Test_NestedTestAllTypes>.self, value: _storage._mapInt64NestedType, fieldNumber: 59)
      }
      try { if let v = _storage._singleAny {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 100)
      } }()
      try { if let v = _storage._singleDuration {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 101)
      } }()
      try { if let v = _storage._singleTimestamp {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 102)
      } }()
      try { if let v = _storage._singleStruct {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 103)
      } }()
      try { if let v = _storage._singleValue {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 104)
      } }()
      try { if let v = _storage._singleInt64Wrapper {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 105)
      } }()
      try { if let v = _storage._singleInt32Wrapper {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 106)
      } }()
      try { if let v = _storage._singleDoubleWrapper {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 107)
      } }()
      try { if let v = _storage._singleFloatWrapper {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 108)
      } }()
      try { if let v = _storage._singleUint64Wrapper {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 109)
      } }()
      try { if let v = _storage._singleUint32Wrapper {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 110)
      } }()
      try { if let v = _storage._singleStringWrapper {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 111)
      } }()
      try { if let v = _storage._singleBoolWrapper {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 112)
      } }()
      try { if let v = _storage._singleBytesWrapper {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 113)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Google_Expr_Proto2_Test_TestAllTypes, rhs: Google_Expr_Proto2_Test_TestAllTypes) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._singleInt32 != rhs_storage._singleInt32 {return false}
        if _storage._singleInt64 != rhs_storage._singleInt64 {return false}
        if _storage._singleUint32 != rhs_storage._singleUint32 {return false}
        if _storage._singleUint64 != rhs_storage._singleUint64 {return false}
        if _storage._singleSint32 != rhs_storage._singleSint32 {return false}
        if _storage._singleSint64 != rhs_storage._singleSint64 {return false}
        if _storage._singleFixed32 != rhs_storage._singleFixed32 {return false}
        if _storage._singleFixed64 != rhs_storage._singleFixed64 {return false}
        if _storage._singleSfixed32 != rhs_storage._singleSfixed32 {return false}
        if _storage._singleSfixed64 != rhs_storage._singleSfixed64 {return false}
        if _storage._singleFloat != rhs_storage._singleFloat {return false}
        if _storage._singleDouble != rhs_storage._singleDouble {return false}
        if _storage._singleBool != rhs_storage._singleBool {return false}
        if _storage._singleString != rhs_storage._singleString {return false}
        if _storage._singleBytes != rhs_storage._singleBytes {return false}
        if _storage._standaloneEnum != rhs_storage._standaloneEnum {return false}
        if _storage._nestedGroup != rhs_storage._nestedGroup {return false}
        if _storage._singleAny != rhs_storage._singleAny {return false}
        if _storage._singleDuration != rhs_storage._singleDuration {return false}
        if _storage._singleTimestamp != rhs_storage._singleTimestamp {return false}
        if _storage._singleStruct != rhs_storage._singleStruct {return false}
        if _storage._singleValue != rhs_storage._singleValue {return false}
        if _storage._singleInt64Wrapper != rhs_storage._singleInt64Wrapper {return false}
        if _storage._singleInt32Wrapper != rhs_storage._singleInt32Wrapper {return false}
        if _storage._singleDoubleWrapper != rhs_storage._singleDoubleWrapper {return false}
        if _storage._singleFloatWrapper != rhs_storage._singleFloatWrapper {return false}
        if _storage._singleUint64Wrapper != rhs_storage._singleUint64Wrapper {return false}
        if _storage._singleUint32Wrapper != rhs_storage._singleUint32Wrapper {return false}
        if _storage._singleStringWrapper != rhs_storage._singleStringWrapper {return false}
        if _storage._singleBoolWrapper != rhs_storage._singleBoolWrapper {return false}
        if _storage._singleBytesWrapper != rhs_storage._singleBytesWrapper {return false}
        if _storage._nestedType != rhs_storage._nestedType {return false}
        if _storage._repeatedInt32 != rhs_storage._repeatedInt32 {return false}
        if _storage._repeatedInt64 != rhs_storage._repeatedInt64 {return false}
        if _storage._repeatedUint32 != rhs_storage._repeatedUint32 {return false}
        if _storage._repeatedUint64 != rhs_storage._repeatedUint64 {return false}
        if _storage._repeatedSint32 != rhs_storage._repeatedSint32 {return false}
        if _storage._repeatedSint64 != rhs_storage._repeatedSint64 {return false}
        if _storage._repeatedFixed32 != rhs_storage._repeatedFixed32 {return false}
        if _storage._repeatedFixed64 != rhs_storage._repeatedFixed64 {return false}
        if _storage._repeatedSfixed32 != rhs_storage._repeatedSfixed32 {return false}
        if _storage._repeatedSfixed64 != rhs_storage._repeatedSfixed64 {return false}
        if _storage._repeatedFloat != rhs_storage._repeatedFloat {return false}
        if _storage._repeatedDouble != rhs_storage._repeatedDouble {return false}
        if _storage._repeatedBool != rhs_storage._repeatedBool {return false}
        if _storage._repeatedString != rhs_storage._repeatedString {return false}
        if _storage._repeatedBytes != rhs_storage._repeatedBytes {return false}
        if _storage._repeatedNestedMessage != rhs_storage._repeatedNestedMessage {return false}
        if _storage._repeatedNestedEnum != rhs_storage._repeatedNestedEnum {return false}
        if _storage._repeatedStringPiece != rhs_storage._repeatedStringPiece {return false}
        if _storage._repeatedCord != rhs_storage._repeatedCord {return false}
        if _storage._repeatedLazyMessage != rhs_storage._repeatedLazyMessage {return false}
        if _storage._mapStringString != rhs_storage._mapStringString {return false}
        if _storage._mapInt64NestedType != rhs_storage._mapInt64NestedType {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Google_Expr_Proto2_Test_TestAllTypes.NestedEnum: SwiftProtobuf._ProtoNameProviding {
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0FOO\0\u{1}BAR\0\u{1}BAZ\0")
}

extension Google_Expr_Proto2_Test_TestAllTypes.NestedMessage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = Google_Expr_Proto2_Test_TestAllTypes.protoMessageName + ".NestedMessage"
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}bb\0")

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self._bb) }()
      default: break
      }
    }
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._bb {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Google_Expr_Proto2_Test_TestAllTypes.NestedMessage, rhs: Google_Expr_Proto2_Test_TestAllTypes.NestedMessage) -> Bool {
    if lhs._bb != rhs._bb {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Google_Expr_Proto2_Test_TestAllTypes.NestedGroup: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = Google_Expr_Proto2_Test_TestAllTypes.protoMessageName + ".NestedGroup"
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{4}\u{18}nested_id\0\u{3}nested_name\0")

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 24: try { try decoder.decodeSingularInt32Field(value: &self._nestedID) }()
      case 25: try { try decoder.decodeSingularStringField(value: &self._nestedName) }()
      default: break
      }
    }
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._nestedID {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 24)
    } }()
    try { if let v = self._nestedName {
      try visitor.visitSingularStringField(value: v, fieldNumber: 25)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Google_Expr_Proto2_Test_TestAllTypes.NestedGroup, rhs: Google_Expr_Proto2_Test_TestAllTypes.NestedGroup) -> Bool {
    if lhs._nestedID != rhs._nestedID {return false}
    if lhs._nestedName != rhs._nestedName {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Google_Expr_Proto2_Test_NestedTestAllTypes: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = _protobuf_package + ".NestedTestAllTypes"
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}child\0\u{1}payload\0")

  fileprivate class _StorageClass {
    var _child: Google_Expr_Proto2_Test_NestedTestAllTypes? = nil
    var _payload: Google_Expr_Proto2_Test_TestAllTypes? = nil

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _child = source._child
      _payload = source._payload
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularMessageField(value: &_storage._child) }()
        case 2: try { try decoder.decodeSingularMessageField(value: &_storage._payload) }()
        default: break
        }
      }
    }
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      try { if let v = _storage._child {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      } }()
      try { if let v = _storage._payload {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Google_Expr_Proto2_Test_NestedTestAllTypes, rhs: Google_Expr_Proto2_Test_NestedTestAllTypes) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._child != rhs_storage._child {return false}
        if _storage._payload != rhs_storage._payload {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Google_Expr_Proto2_Test_ExampleType: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = _protobuf_package + ".ExampleType"
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{3}foo_bar\0\u{1}in\0")

  public var isInitialized: Bool {
    if !_protobuf_extensionFieldValues.isInitialized {return false}
    return true
  }

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._name) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._fooBar) }()
      case 3: try { try decoder.decodeSingularInt64Field(value: &self._in) }()
      case 100..<536870912:
        try { try decoder.decodeExtensionField(values: &_protobuf_extensionFieldValues, messageType: Google_Expr_Proto2_Test_ExampleType.self, fieldNumber: fieldNumber) }()
      default: break
      }
    }
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._name {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._fooBar {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._in {
      try visitor.visitSingularInt64Field(value: v, fieldNumber: 3)
    } }()
    try visitor.visitExtensionFields(fields: _protobuf_extensionFieldValues, start: 100, end: 536870912)
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Google_Expr_Proto2_Test_ExampleType, rhs: Google_Expr_Proto2_Test_ExampleType) -> Bool {
    if lhs._name != rhs._name {return false}
    if lhs._fooBar != rhs._fooBar {return false}
    if lhs._in != rhs._in {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    if lhs._protobuf_extensionFieldValues != rhs._protobuf_extensionFieldValues {return false}
    return true
  }
}

extension Google_Expr_Proto2_Test_ExtendedExampleType: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = _protobuf_package + ".ExtendedExampleType"
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Google_Expr_Proto2_Test_ExtendedExampleType, rhs: Google_Expr_Proto2_Test_ExtendedExampleType) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
