// Command gen-unicode-tables dumps the tables of Go's unicode package that
// regexp/syntax uses into Sources/CELRegex/UnicodeTables.swift, so that the
// Swift port of regexp matches Go exactly.
//
// Usage (from the repository root):
//
//	go run ./tools/gen-unicode-tables > Sources/CELRegex/UnicodeTables.swift
//
// Every table is a list of closed rune ranges, packed into one UInt32 each:
// lo<<11 | (hi-lo), with ranges longer than 2048 runes split into chunks.
// Strided ranges of the Go tables are expanded and abutting ranges merged,
// which is the canonical form regexp/syntax's appendTable produces anyway.
//
// Simple case folding (unicode.SimpleFold) is dumped as sorted (r, SimpleFold(r))
// pairs for every rune that does not fold to itself.
package main

import (
	"bufio"
	"fmt"
	"os"
	"runtime"
	"slices"
	"strings"
	"unicode"
)

type rng struct{ lo, hi rune }

// ranges returns the canonical sorted, merged range list of the set of runes for which in reports true.
func ranges(in func(rune) bool) []rng {
	var out []rng
	for r := rune(0); r <= unicode.MaxRune; r++ {
		if !in(r) {
			continue
		}
		if n := len(out); n > 0 && out[n-1].hi == r-1 {
			out[n-1].hi = r
		} else {
			out = append(out, rng{r, r})
		}
	}
	return out
}

func tableRanges(t *unicode.RangeTable) []rng {
	var out []rng
	add := func(lo, hi rune) {
		if n := len(out); n > 0 && out[n-1].hi+1 >= lo {
			if hi > out[n-1].hi {
				out[n-1].hi = hi
			}
			return
		}
		out = append(out, rng{lo, hi})
	}
	for _, r := range t.R16 {
		for c := rune(r.Lo); c <= rune(r.Hi); c += rune(r.Stride) {
			add(c, c)
		}
	}
	for _, r := range t.R32 {
		for c := rune(r.Lo); c <= rune(r.Hi); c += rune(r.Stride) {
			add(c, c)
		}
	}
	// Sanity check against the reference membership test.
	want := ranges(func(r rune) bool { return unicode.Is(t, r) })
	if !slices.Equal(out, want) {
		panic("table ranges disagree with unicode.Is")
	}
	return out
}

func pack(rs []rng) []uint32 {
	var out []uint32
	for _, r := range rs {
		for lo := r.lo; lo <= r.hi; lo += 2048 {
			hi := min(lo+2047, r.hi)
			out = append(out, uint32(lo)<<11|uint32(hi-lo))
		}
	}
	return out
}

type entry struct {
	name  string
	start int
	count int
}

func main() {
	var data []uint32
	emit := func(t []rng) entry {
		p := pack(t)
		e := entry{start: len(data), count: len(p)}
		data = append(data, p...)
		return e
	}
	group := func(m map[string]*unicode.RangeTable) []entry {
		var names []string
		for k := range m {
			names = append(names, k)
		}
		slices.Sort(names)
		var es []entry
		for _, n := range names {
			e := emit(tableRanges(m[n]))
			e.name = n
			es = append(es, e)
		}
		return es
	}

	categories := group(unicode.Categories)
	scripts := group(unicode.Scripts)
	foldCategory := group(unicode.FoldCategory)
	foldScript := group(unicode.FoldScript)
	if unicode.Categories["Cn"] != unicode.Cn {
		panic("unicode.Cn is not Categories[\"Cn\"]")
	}
	print := emit(ranges(unicode.IsPrint))
	letter := emit(ranges(unicode.IsLetter))
	digit := emit(ranges(unicode.IsDigit))

	var aliasNames []string
	for k := range unicode.CategoryAliases {
		aliasNames = append(aliasNames, k)
	}
	slices.Sort(aliasNames)

	// Simple folding orbits: every rune with SimpleFold(r) != r, in increasing order.
	var folds []uint32
	for r := rune(0); r <= unicode.MaxRune; r++ {
		if f := unicode.SimpleFold(r); f != r {
			folds = append(folds, uint32(r), uint32(f))
		}
	}

	w := bufio.NewWriter(os.Stdout)
	defer w.Flush()
	p := func(format string, args ...any) { fmt.Fprintf(w, format, args...) }

	p("// Code generated by tools/gen-unicode-tables from Go %s package unicode (Unicode %s); DO NOT EDIT.\n\n",
		runtime.Version(), unicode.Version)
	p("// Copyright 2009 The Go Authors. All rights reserved.\n")
	p("// Use of this source code is governed by a BSD-style\n")
	p("// license that can be found in the LICENSE file.\n\n")
	p("extension UnicodeTables {\n")
	p("  /// Unicode version of the tables.\n")
	p("  static let version = %q\n\n", unicode.Version)

	writeEntries := func(name string, es []entry) {
		p("  static let %s: [String: TableRef] = [\n", name)
		for _, e := range es {
			p("    %q: TableRef(start: %d, count: %d),\n", e.name, e.start, e.count)
		}
		p("  ]\n\n")
	}
	writeEntries("categories", categories)
	writeEntries("scripts", scripts)
	writeEntries("foldCategory", foldCategory)
	writeEntries("foldScript", foldScript)
	for _, e := range []struct {
		name string
		e    entry
	}{{"print", print}, {"letter", letter}, {"digit", digit}} {
		p("  static let %s = TableRef(start: %d, count: %d)\n", e.name, e.e.start, e.e.count)
	}
	p("\n  static let categoryAliases: [String: String] = [\n")
	for _, k := range aliasNames {
		p("    %q: %q,\n", k, unicode.CategoryAliases[k])
	}
	p("  ]\n\n")

	p("  /// Simple case folding: pairs (r, unicode.SimpleFold(r)) for every r that does not fold to itself,\n")
	p("  /// sorted by r.\n")
	p("  static let foldPairs: [UInt32] = [\n")
	for i := 0; i < len(folds); i += 8 {
		p("   ")
		for _, v := range folds[i:min(i+8, len(folds))] {
			p(" 0x%05x,", v)
		}
		p("\n")
	}
	p("  ]\n\n")

	p("  /// Packed ranges, lo<<11 | (hi-lo).\n")
	p("  static let ranges: [UInt32] = [\n")
	var line strings.Builder
	for i, v := range data {
		if i%8 == 0 {
			line.WriteString("   ")
		}
		fmt.Fprintf(&line, " 0x%08x,", v)
		if i%8 == 7 || i == len(data)-1 {
			p("%s\n", line.String())
			line.Reset()
		}
	}
	p("  ]\n")
	p("}\n")
	fmt.Fprintf(os.Stderr, "ranges: %d, fold pairs: %d\n", len(data), len(folds)/2)
}
