#!/usr/bin/env python3
"""Generates Tests/CELExtensionsTests/Fixtures/FormatFixtures.swift from cel-go via tools/oracle.

The fixtures pin the number formatting of `string.format` (strings extension), which ports Go's
fmt / strconv and, before version 4, golang.org/x/text/message:
  - %s, %d, %f, %.Nf, %e, %.Ne on doubles (edge cases and random bit patterns), versions 3 and latest
  - %f, %e, %x, %o, %b on ints and uints

Usage (from the repository root):
  (cd tools/oracle && go build -o /tmp/cel-oracle .)
  python3 tools/ext-fixtures/gen_format_fixtures.py /tmp/cel-oracle > Tests/CELExtensionsTests/Fixtures/FormatFixtures.swift
"""
import json
import random
import struct
import subprocess
import sys

random.seed(20261001)


def run(oracle, version, exprs):
    ext = {"name": "strings"}
    ext["version"] = "latest" if version == "latest" else version
    inp = "".join(
        json.dumps({"id": str(i), "kind": "eval", "check": False, "expr": e,
                    "config": {"extensions": [ext]}}) + "\n"
        for i, e in enumerate(exprs)
    )
    out = subprocess.run([oracle], input=inp, capture_output=True, text=True, check=True).stdout
    results = {}
    for line in out.splitlines():
        r = json.loads(line)
        results[int(r["id"])] = r
    return [results[i] for i in range(len(exprs))]


def swift_string(s):
    out = '"'
    for ch in s:
        if ch == "\\":
            out += "\\\\"
        elif ch == '"':
            out += '\\"'
        elif ord(ch) < 0x20 or ord(ch) > 0x7E:
            out += "\\u{%x}" % ord(ch)
        else:
            out += ch
    return out + '"'


def bits_of(d):
    return struct.unpack("<Q", struct.pack("<d", d))[0]


def double_of(bits):
    return struct.unpack("<d", struct.pack("<Q", bits))[0]


def cel_double(bits):
    # double() of a hex-free literal would round-trip through Go's parser; using the bit pattern
    # through a string keeps every value exact.
    d = double_of(bits)
    if d != d:
        return 'double("NaN")'
    if d in (float("inf"), float("-inf")):
        return 'double("%s")' % ("Infinity" if d > 0 else "-Infinity")
    return 'double("%s")' % repr(d)


def doubles():
    vals = [
        0.0, -0.0, 1.0, -1.0, 0.1, 0.5, 1.5, 2.5, -2.5, 0.125, 0.0625, 100.0, 1e5, 1e6, 123456.0,
        1234567.891, 1e15, 1e16, 1e20, 1e21, 1e22, 1e100, 1e300, 1.7976931348623157e308, 1e-4,
        1e-5, 0.0001234, 5e-324, 2.2250738585072014e-308, 999999.5, 0.0000005, 0.0000015,
        9.9999995, 3.14159265358979, 2.71828, 1052.032911275, -0.0004, 0.045, 1.005, 2.675,
        float("nan"), float("inf"), float("-inf"),
    ]
    bits = [bits_of(v) for v in vals]
    for _ in range(150):
        b = random.getrandbits(64)
        if (b >> 52) & 0x7FF == 0x7FF:
            continue
        bits.append(b)
    for _ in range(100):
        # Moderate magnitudes, where the fraction digits matter.
        bits.append(bits_of(random.uniform(-1e7, 1e7)))
    return bits


CLAUSES = ["%s", "%d", "%f", "%.0f", "%.1f", "%.3f", "%.17f", "%.30f", "%e", "%.0e", "%.3e", "%.15e"]


def main():
    oracle = sys.argv[1]
    dbits = doubles()
    cases = []
    for version in ["latest", 3]:
        exprs = []
        keys = []
        for b in dbits:
            for clause in CLAUSES:
                if version == 3 and clause in ("%d",):
                    continue
                exprs.append('"%s".format([%s])' % (clause, cel_double(b)))
                keys.append((clause, b))
        for (clause, b), r in zip(keys, run(oracle, version, exprs)):
            res = r["result"]
            if "value" in res:
                cases.append((version, clause, b, res["value"]["string"], None))
            else:
                cases.append((version, clause, b, None, res["error"]))

    ints = [0, 1, -1, 7, -255, 255, 4096, 2**53, -(2**53) - 1, 2**63 - 1, -(2**63)]
    uints = [0, 1, 255, 2**53 + 1, 2**64 - 1]
    int_clauses = ["%s", "%d", "%f", "%.2f", "%e", "%x", "%X", "%o", "%b"]
    int_cases = []
    for version in ["latest", 3]:
        exprs = []
        keys = []
        for i in ints:
            for clause in int_clauses:
                lit = str(i) if i != -(2**63) else "-9223372036854775808"
                exprs.append('"%s".format([%s])' % (clause, lit))
                keys.append((clause, "int", i))
        for u in uints:
            for clause in int_clauses:
                exprs.append('"%s".format([%du])' % (clause, u))
                keys.append((clause, "uint", u))
        for (clause, kind, v), r in zip(keys, run(oracle, version, exprs)):
            res = r["result"]
            out = res["value"]["string"] if "value" in res else None
            err = res.get("error")
            int_cases.append((version, clause, kind, v, out, err))

    print("// Generated by tools/ext-fixtures/gen_format_fixtures.py from cel-go v0.32.0 via tools/oracle.")
    print("// Do not edit by hand; regenerate instead.")
    print()
    print("enum FormatFixtures {")
    print("  /// (strings version, nil = latest; clause; IEEE 754 bits; result; error).")
    print("  static let doubles: [(UInt32?, String, UInt64, String?, String?)] = [")
    for version, clause, b, out, err in cases:
        v = "nil" if version == "latest" else str(version)
        o = swift_string(out) if out is not None else "nil"
        e = swift_string(err) if err is not None else "nil"
        print("    (%s, %s, 0x%016x, %s, %s)," % (v, swift_string(clause), b, o, e))
    print("  ]")
    print()
    print("  /// (strings version, nil = latest; clause; is uint; value bits; result; error).")
    print("  static let integers: [(UInt32?, String, Bool, UInt64, String?, String?)] = [")
    for version, clause, kind, v, out, err in int_cases:
        ver = "nil" if version == "latest" else str(version)
        o = swift_string(out) if out is not None else "nil"
        e = swift_string(err) if err is not None else "nil"
        bits = v & (2**64 - 1)
        print("    (%s, %s, %s, 0x%016x, %s, %s)," % (ver, swift_string(clause), "true" if kind == "uint" else "false", bits, o, e))
    print("  ]")
    print("}")


if __name__ == "__main__":
    main()
